scandipwa/scandipwa

src/app/component/Image/Image.component.js, src/app/component/ProductCard/ProductCard.style.scss
- Fixed image transition from primitive to real image on Safari browser
- Added timeout to requestIdle, so if it is not supported or takes more than 1 sec will trigger image loading anyway
Fixes #25
=> Fix placeholder image loading of Safari browser

src/app/component/ProductActions/ProductActions.component.js, src/app/component/ProductDetails/ProductDetails.component.js, src/app/route/ProductPage/ProductPage.component.js
Fixed blank page when switching between related products
-Configurable color swatch is initialised only if variant exists and product details are loaded
-Product sku is rendered when it has been loaded
-getthumbnail now checks if configurable exists
=> Page-Dying

src/app/component/CategoriesList/CategoriesList.component.js, src/app/component/CategoriesList/CategoriesList.style.scss, src/app/query/Category/Category.js, src/app/route/CategoryPage/CategoryPage.component.js, src/app/route/CategoryPage/CategoryPage.container.js, src/app/store/Category/Category.action.js, src/app/store/Category/Category.dispatcher.js, src/app/store/Category/Category.reducer.js, src/app/store/Category/index.js
Fixes issue #5 
- Made categories load only once on first category page initialization.
- Category tree is displayed based on all available categories.
- Categories are expanded only if parent category or its children is selected.
=> Show a category tree in the "Available categories"

src/app/route/index.js
When custom items object was not specified - an undefined is returned, therefore app brake. Fixed.
=> Routes custom items fix

src/app/component/TextPlaceholder/TextPlaceholder.component.js
Quick note - the only 'number' that is actually passed to the TextPlaceholder is price, which has the PropType of string anyways.
Are we actually planning to to use TextPlaceholder for pure numbers?
=> Add number as acceptable content type

src/app/component/Field/Field.component.js
This fixes #109 
@alfredsgenkins you for some reason changed `value` to `stateValue` which caused this issue. I have checked form validations and product qty selection, but maybe there were other reasons you changed it.
=> Fix sync between qty of mini-cart and cart

src/app/store/index.js
This approach lets import all base reducers in theme overrides.
Example usage:
```
// Global reducers
import { reducers as baseReducers } from 'SourceStore';
// Our project specific reducers
import { CustomReducer } from 'Store/Custom';
const reducers = combineReducers({
...baseReducers,
CustomReducer
});
```
=> Will export all reducers for use in theme overrides

src/app/component/ProductDetails/ProductDetails.component.js
This is a possible fix for issue where product variant at `configurableVariantIndex === 0` is displaying sku of a parent configurable product and not it's own.
Issue caused by the way Javascript handles Object and number 0 in a logical `&&`
This solution works both on configurable products with variants and on single product, but more explicit checks might be necessary.
Let me know if you want this fix improved
=> Changed product selection

src/app/store/CmsBlocksAndSlider/CmsBlocksAndSlider.reducer.js, src/app/util/Request/Request.js
There is an issue where all resources from batched query fails if one of the requested cms blocks does not exist.
This issue limits such functionality as enable/disable cms block from BE without updating frontend.
=> Fixed issue where menu and all cms blocks fail if one block is disabled

jsconfig.json, package-lock.json, package.json, process-core.yml, process.yml, src/config/FallbackPlugin/index.js, src/config/webpack.core.config.js, src/config/webpack.development.config.js, src/config/webpack.production.config.js, src/config/webpack.sw.config.js
In this PR, the following features were implemented:
- The `FallbackPlugin` is now a resolver hook, not a compiler, this allowed for more versatile extension
- The `PM2`, along with `forever` and `chokidar` were added as development dependencies, which allowed for server reload implementation in two cases:
1. If any file of `.js` or `.scss` was added (because of in memory cache, of `webpack-dev-server` it is necessity for `FallbackPlugin` to work properly)
2. If webpack configuration file was altered
This PR has following dependencies:
- On Docker setup repo to run correct scripts: https://github.com/scandipwa/scandipwa-base/pull/41
- On Installer to bootstrap correct files: https://github.com/scandipwa/installer/pull/6
- On Docs (which is pending)
Fixes: #243
=> The fix for Fallback plugin, the auto-restarting development server

src/app/route/CategoryPage/CategoryPage.component.js, src/app/route/CategoryPage/CategoryPage.container.js
Fixes UX issue when next (ie 2nd) page with 1 product is considered as part of first one. This solution assumes that current page is maximal loaded page as pagination is located at pages bottom part.
=> Fixed duplicate product on PLP

src/app/store/Cart/Cart.dispatcher.js, src/app/util/Product/Product.js
- Fix of category page crash if one of the variants of product(s) in listing was/were null
- Fix of product page if one of the variants of product was null
- Fixed Irregular behaviour of add to cart functionality for selected variant (in case if one or more variants were disabled from backend or were out of stock)
=> fixed configurable product page crash in case any variant is null

src/app/component/ProductActions/ProductActions.component.js, src/app/component/ProductActions/ProductActions.container.js, src/app/component/ProductAttributeValue/ProductAttributeValue.component.js, src/app/component/ProductAttributeValue/ProductAttributeValue.style.scss, src/app/component/ProductConfigurableAttributes/ProductConfigurableAttributes.component.js, src/app/route/ProductPage/ProductPage.component.js, src/app/route/ProductPage/ProductPage.container.js, src/app/util/Product/Product.js, src/app/util/Url/Url.js
Added ability to deselect value of Product Configurable Attribute.
Product Configurable Attribute is grayed out if there is no matching variant or if it is out of stock.
Depends on https://github.com/scandipwa/catalog-graphql/pull/15
=> Availability of Configurable Product Attribute is checked based on variants

src/app/component/ProductActions/ProductActions.component.js
Display price of simple product, if variant is selected. Otherwise price of configurable parent is used.
=> Display price of simple product in PDP

src/app/component/ProductActions/ProductActions.style.scss
=> Added bottom margin to Attributes on ProductActions

src/app/store/Cart/Cart.dispatcher.js, src/app/util/Product/Product.js
Reverted changes from https://github.com/scandipwa/base-theme/pull/284
https://github.com/scandipwa/catalog-graphql/pull/16 filters out items that are out of stock on BE.
BE also handles cases when simple products are disabled. Looks like `product: null` situation should not happen anymore.
New version of [catalog-graphql](https://github.com/scandipwa/catalog-graphql)  is required.
=> Reverted null checks for variant

src/app/query/MyAccount.query.js
Added `getCustmoer` method that got accidently removed in https://github.com/scandipwa/base-theme/commit/d409b0d8405aed7f2658b036044638e5090ad3f6#diff-07da4456b6b75c50f43b40ee72694cb0
`new-checkout` branch already has a fix for it, so maybe we wait for it instead. https://github.com/scandipwa/base-theme/blob/4cb974758fcc6b534c47679e2286e54972fd1267/src/app/query/MyAccount.query.js#L92-L94
=> Fixed error when logged in user open checkout page 

src/app/route/ProductPage/ProductPage.container.js
I think `id` comparison was used to improve performance, however it caused a following side effect:
Steps to reproduce:
1. Add simple product to Cart
2. Open PDP and select different attributes (size/color)
3. Open MiniCart
4. Click on CartItem added in first step
Result:
We stay on the same page, product selected in step 2 is displayed, but not the CarItem.
Refrehing the page updates the selection.
=> Fixed issue when PDP was not update, when simple product is opened from CartOverlay

src/app/component/CategorySort/CategorySort.container.js
Products can be sorted by position in Category page.
Are label texts ok?
Depends on https://github.com/scandipwa/catalog-graphql/pull/17
=> Added option to sort products by Position

src/app/component/ProductList/ProductList.container.js, src/app/component/ProductListWidget/ProductListWidget.container.js, src/app/route/CategoryPage/CategoryPage.component.js, src/app/route/CategoryPage/CategoryPage.container.js
Restored `if` check on [Line](https://github.com/scandipwa/base-theme/compare/2.x-dev...mihailspopovs4:bug/category-multiple-requests?expand=1#diff-d9a0d79ad2ab3e3b086255ffbee9e932R125) as it was before https://github.com/scandipwa/base-theme/pull/286.
Added check for `isNewCategory`. It prevents getting Category info, when filter or sort options are changed.
=> Fixed logic used for getting category info and products

src/app/component/CheckoutAddressBook/CheckoutAddressBook.container.js, src/app/component/CheckoutAddressForm/CheckoutAddressForm.component.js, src/app/component/CheckoutDeliveryOptions/CheckoutDeliveryOptions.component.js, src/app/component/CheckoutDeliveryOptions/CheckoutDeliveryOptions.container.js, src/app/component/CheckoutShipping/CheckoutShipping.container.js, src/app/route/Checkout/Checkout.container.js, src/app/util/Address/index.js, src/app/util/Request/Request.js
- Added support for UPS checkout method
- Fixed loader for checkout methods. Now `isLoading = false` only after all responses for checkout methods were received (before it was set immediately after the first response).
- Added Artjom's debounce feature
Requirements:
- M2 admin panel: `Stores > Configuration > Sales > Shipping methods > UPS` :
* `Enabled for Checkout = Yes`
* For testing purposes `UPS Type = United Parcel Service`, should be `United Parcel Service XML` in production.
=> Checkout methods support: UPS

src/app/component/ProductAttributeValue/ProductAttributeValue.component.js, src/app/component/ProductAttributeValue/ProductAttributeValue.style.scss
- Fixed width for text-swatch
- Fixed non-displaying alt for text/image-swatch
- Added overlay for image-swatch
- Fixed mobile alignment of Image-swatch overlay
- Added consistency in styling for color/image-swatch
Example of text-swatches with different width + image/color-swatches together:
Example of image-swatches `:hover` and `isSelected`:
=> Layered navigation - attribute value types support

src/app/route/Checkout/Checkout.container.js
Using only shipping data returned from shipping address, checkout data is showing precisely. In order to fix it on BE and use then returned data from saveAddress resolver, resolver should be rewritten using totals collection logic I believe. (At least I have seen it in M2 implementation).
=> Fixed grand total in checkout

src/app/component/SliderWidget/SliderWidget.component.js
On the cms page with the url "/page/about-us" the slider was searching for the /page/media/slider/... images, but on the /about-us url it worked. Now it works for both in both of our environments.
=> Fix the image path on the cms pages for the sliders

src/app/query/Category.query.js, src/app/route/CategoryPage/CategoryPage.container.js
Hi @alfredsgenkins,
This is the implementation for SWPWA-196. If a valid default sort order has been defined for the current category, it will be used.
Please take a look. Thanks!
=> Fetch and use category default sort order

src/app/component/MyAccountOverlay/MyAccountOverlay.component.js, src/app/component/MyAccountOverlay/MyAccountOverlay.container.js
Currently, clicking "send reset link" in the reset password overlay doesn't do anything. Fixed:
Now it displays a loading screen, then:
or
...as it did before.
=> Fix bug where resetting a password would not work

src/app/component/CheckoutBilling/CheckoutBilling.container.js
Fixes issue #474 
1. Signup / Login
2. Add exactly one address to address book (__NOT__ more than one)
3. Add a virtual product to cart
4. Go to checkout
5. Try to proceed with selected billing address (the address previously added)
6. Order should be placed without any errors
=> Fixed billing address finding logic in checkoutbilling component

src/app/component/Field/Field.component.js
In one of the use cases, select field was required to be disabled unless a specific condition is met.
This ability was present in other field types but not in Select. Added the same.
=> Added 'disabled' option for select in Field component.

src/app/component/CategoryFilterOverlay/CategoryFilterOverlay.component.js
Layered navigation has the following behaviour now:
* Collection of non-configurable products - show price slider
* Collection of non-configurable products with the same price - no layered navigation
* Empty collection - no layered navigation
=> [SWPWA-387] Always show layered navigation on PLP with products

src/app/component/ProductAttributeValue/ProductAttributeValue.component.js, src/app/component/ProductCard/ProductCard.component.js, src/app/component/ProductCard/ProductCard.container.js, src/app/component/ProductInformation/ProductInformation.component.js, src/app/component/ProductInformation/ProductInformation.container.js
* Adjusted `ProductAttributeValue` component, now it return text value of attribute when `formatAsText` prop is passed. Handles all types of attributes, e.g. swatches, multiselects, dropdowns, yes/no, text.
* Integrated this component into `ProductInformationComponent` and `ProductCardComponent`. Now attribute values are being displayed correctly.
Examples:
* Text attribute
* Swatch
* Multiselect
=> [SWPWA-385] fix attributes are not respecting attribute values

src/app/component/SearchOverlay/SearchOverlay.component.js
Removed attribute placeholder in search when attribute is undefined.
Example (1st product has no placeholder for `brand` anymore):
=> [SWPWA-407] Remove attribute placeholders in search

README.md, composer.json, src/app/component/CheckoutBilling/CheckoutBilling.component.js, src/app/component/CheckoutBilling/CheckoutBilling.container.js, src/app/component/CheckoutBilling/CheckoutBilling.style.scss, src/app/component/CheckoutTermsAndConditionsPopup/CheckoutTermsAndConditionsPopup.component.js, src/app/component/CheckoutTermsAndConditionsPopup/CheckoutTermsAndConditionsPopup.container.js, src/app/component/CheckoutTermsAndConditionsPopup/CheckoutTermsAndConditionsPopup.style.scss, src/app/component/CheckoutTermsAndConditionsPopup/index.js, src/app/query/Config.query.js, src/app/store/Config/Config.dispatcher.js, src/app/store/Config/Config.reducer.js, src/app/style/base/_link.scss
* Added terms and conditions to config store
* Added `TermsAndConditionsPopup` component
* Added support for terms and conditions on checkout step
Depends on https://github.com/scandipwa/store-graphql/pull/1
Screens:
Terms and conditions are Enabled:
* Popup with Terms and Conditions:
Terms and conditions are disabled:
=> [SWPWA-375] Terms and conditions support

src/app/component/CategoryFilterOverlay/CategoryFilterOverlay.component.js, src/app/component/CategoryFilterOverlay/CategoryFilterOverlay.container.js, src/app/route/CategoryPage/CategoryPage.component.js
Behaviour:
* No products - no filters and no price range
* Only products with no attributes - no filters, only price range
=> [SWPWA-387|FIX] Always show layered navigation on PLP with products

src/app/route/ProductPage/ProductPage.container.js
`isConfigurationInitialized` is not used anywhere, therefore it should be removed
=> remove redundant state

src/app/route/CategoryPage/CategoryPage.container.js, src/app/route/ProductPage/ProductPage.container.js
On null category/product redirect to homepage
When user enters `/category`, `/category`, `/product`, `/product/`, he gets redirected to the homepage.
=> On null category/product redirect to homepage

src/app/route/CartPage/CartPage.style.scss
Fix padding for mobile cart
Before:
After:
=> Fix padding for mobile cart

src/app/component/ProductActions/ProductActions.component.js, src/app/route/CartPage/CartPage.component.js, src/app/route/CartPage/CartPage.style.scss
Now
* `Cart page` has H1 tag
* `PDP` has H1 tag
On mobile no need for H1 tags on `menu` and `my account` pages.
=> [SWPWA-457] H1 adjustments

src/app/component/ProductActions/ProductActions.component.js, src/app/component/ProductActions/ProductActions.style.scss, src/app/component/ProductCard/ProductCard.component.js, src/app/component/ProductPrice/ProductPrice.component.js, src/app/component/ProductPrice/ProductPrice.container.js, src/app/component/ProductReviewList/ProductReviewList.component.js, src/app/component/ProductReviews/ProductReviews.component.js, src/app/route/ProductPage/ProductPage.component.js, src/app/route/ProductPage/ProductPage.container.js
Based on earlier implemented schema enhancement https://github.com/scandipwa/base-theme/pull/581
* Integrated Schema on PDP
* Integrated missing fields: URL, review, stock availability  
* Convenient integration of schema for extending it further for simple and grouped product types.
Before:
After:
* No reviews
* With reviews (review criterion were simulated, as reviews do not work properly at the moment)
=> [SWPWA-470] Product Markup / Configurable - Structured Data markup adjustments

src/app/query/ProductList.query.js, src/app/type/ProductList.js
Special price does not disappear after the time of the promotion ends. By adding special_from_date and special_to_date fields to the query - issue gets fixed, the special price is not showing anymore if time has ended.
=> SWPWA-405 - Special price does not disappear

src/app/util/Query/PrepareDocument.js
This PR resolves an issue with multiple, identical arguments being defined for query, if multiple fields with identical argument names have been defined.
i.e query defined as `query { field0(arg: \\), field1(arg: \/) }` would be converted to
```
query($_arg_0: Scalar!, $_arg_0: Scalar!) {
field0(arg: $_arg_0),
field1(arg: $_arg_0)
}
arguments {
$_arg_0: \\
}
```
Instead of
```
query($_arg_0: Scalar!, $_arg_1: Scalar!) {
field0(arg: $_arg_0),
field1(arg: $_arg_1)
}
arguments {
$_arg_0: \\,
$_arg_1: \/
}
```
=> Resolved issue with prepareDocument variables

src/app/route/CartPage/CartPage.container.js
Fixed a bug where if guest_checkout is true then its not possible for the guest to come to the checkout. It was made the other way around.
=> Fixed guest_checkout bug

src/app/component/ProductCustomizableOption/ProductCustomizableOption.component.js, src/app/component/ProductCustomizableOption/ProductCustomizableOption.container.js, src/app/component/ProductCustomizableOptions/ProductCustomizableOptions.component.js, src/app/component/ProductCustomizableOptions/ProductCustomizableOptions.container.js, src/app/component/StoreItems/StoreItems.component.js
Added missing namespaces for following components:
- ProductCustomizableOption
- ProductCustomizableOptionContainer
- ProductCustomizableOptions
- ProductCustomizableOptionsContainer
- StoreItems
As long as they're missing, multistore and several product types won't be working due to exception being thrown while trying to proxy these components for plugins.
=> Added missing namespaces for several components

src/app/component/CheckoutBilling/CheckoutBilling.container.js
Fixed checkout “My billing and shipping are the same” checkbox is always checked, even if different ones are selected in the address book.
=> [issue #770] Same shipping address fix

src/app/component/CategoryFilterOverlay/CategoryFilterOverlay.component.js, src/app/component/CategoryFilterOverlay/CategoryFilterOverlay.container.js, src/app/component/ProductList/ProductList.container.js
Expected behavior with these changes:
- After applying Filter in PLP, if we go back to the homepage and come to the same category, the filter should reset.
- After opening filter, click on any filter > click on delete icon and then if you come back on the category page and close the filter section, the header should be updated.
- After the click of back button on applying more than one filter, page goes to the previous state. If only 1 filter was applied, filters will be cleared and overlay closed.
=> Issue #722 mobile filters fix

.eslintrc, src/config/FallbackPlugin/index.js, src/config/I18nPlugin/index.js, src/config/TranslationFunction/index.js
Since scandipwa guidelines were written for react mainly, it becomes annoying when they warn for level one export in webpack configs and modules.
=> disable export-level-one rule for webpack config and plugins

.vscode/settings.json
Magento_Theme is a generated folder and sometimes search results can become messy because they'll include results from this folder.
This option should fix that and that options can be disabled in vscode search settings, so should be no problem here.
=> Imrpove vscode/settings

.vscode/settings.json, package-lock.json, package.json
To use this feature you need to install [Prettier-Eslint](https://marketplace.visualstudio.com/items?itemName=rvest.vs-code-prettier-eslint) extension.
After that js code will be formatted on-save.
=> enables format-on-save with eslint rules

jsconfig.json
Magento_Theme folder is a generated folder and because of its size VSCode can throw this warning:
Magento_Theme folder should be excluded like node_modules folder.
=> add Magento_Theme to jsconfig excludes

src/app/component/CartCoupon/CartCoupon.style.scss, src/app/component/CartItem/CartItem.style.scss, src/app/component/Footer/Footer.component.js, src/app/component/Header/Header.component.js, src/app/component/Header/Header.style.scss, src/app/component/Menu/Menu.component.js, src/app/component/Menu/Menu.style.scss, src/app/component/MenuItem/MenuItem.component.js, src/app/component/NavigationAbstract/NavigationAbstract.container.js, src/app/component/NavigationTabs/NavigationTabs.component.js, src/app/component/ProductList/ProductList.container.js, src/app/component/ProductWishlistButton/ProductWishlistButton.style.scss, src/app/component/Router/Router.container.js, src/app/component/SearchField/SearchField.component.js, src/app/route/CartPage/CartPage.style.scss, src/app/route/CategoryPage/CategoryPage.style.scss, src/app/route/MenuPage/MenuPage.container.js, src/app/route/ProductPage/ProductPage.style.scss, src/app/store/Config/Config.reducer.js, src/app/style/abstract/_media.scss, src/app/style/base/_reset.scss, src/app/util/Mobile/isMobile.js, src/config/webpack.development.config.js
JS isMobile.tablet API has been removed.
Changes in styles are made to fix some issues on tablets screens <1024px size.
Tested in Chrome Devtools iPads emulation.
=> [Issue #950] remove tablet view

src/app/route/CmsPage/CmsPage.container.js, src/app/store/Meta/Meta.dispatcher.js
Canonical tags on PDP and PLP must be enabled in Magento admin.
_Store > Configuration > Catalog > Catalog > Search Engine Optimization_ and set **Use Canonical Link Meta Tag For Categories** and **Use Canonical Link Meta Tag For Products** to **Yes**.
=> [Issue #927] add canonical tags on pdp plp cms page and homepage

src/app/store/Cart/Cart.dispatcher.js
Namespaces `Store/Cart/Dispatcher/addProductToCartFetchMutationThen`, `Store/Cart/Dispatcher/addProductToCartFetchMutationCatch`, `Store/Cart/Dispatcher/applyCouponToCartFetchMutationThen` and `Store/Cart/Dispatcher/applyCouponToCartFetchMutationError` has been removed due to switch from promise chains to async function.
=> [Issue #711] create new quote only when product is added to cart

src/app/component/Meta/Meta.container.js, src/app/route/CategoryPage/CategoryPage.container.js, src/app/store/Meta/Meta.dispatcher.js, src/app/store/Meta/Meta.reducer.js
Now tag `<meta name="robots" content="index, follow">` will be added to PLP page without applied filters.
If filters are applied there will be used  `<meta name="robots" content="noindex, nofollow">` tag.
=> [Issue #928] add meta tag robots for PLP

src/app/component/Router/Router.container.js, src/app/style/abstract/_media.scss, src/app/util/Mobile/isMobile.js
Now `isMobile` will use [Window.matchMedia API](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) for device screen detection.
This will bring a consistent view to render since we're using the same API that is used in CSS for styling based on [media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries).
=> [Issue #1378] fallback ismobile to matchMedia instead of user agent

composer.json, src/app/component/CartItem/CartItem.component.js, src/app/component/CartItem/CartItem.style.scss, src/app/util/Cart/Cart.js
This is an additional fix to the #973 issue.
Must be used with [this PR](https://github.com/scandipwa/catalog-graphql/pull/68) for BE module [catalog/graphql](https://github.com/scandipwa/catalog-graphql).
The grayscale filter on the product image has been removed.
Out of stock message now appears on top of the cart item.
=> [Issue #1356] product is not available on BE

src/app/util/Product/Product.js
No more review_summary error on FE if there're no reviews on the website.
=> [Issue #1399] use default review_summary object if there's no reviews on BE

src/app/component/Breadcrumbs/Breadcrumbs.style.scss, src/app/component/Header/Header.component.js, src/app/component/Header/Header.style.scss
When the breadcrumb is hidden all pages were going under the header, instead of fixing the margin for
each of them and worring about the breadcrumb being displayed or not, move the margin handing in the header
itself
fixes: #1334
=> Fix header padding for all pages

composer.json, src/app/component/CartOverlay/CartOverlay.component.js, src/app/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js, src/app/query/Cart.query.js, src/app/route/CartPage/CartPage.component.js
Hello!
Changes will work only if add 'applied_rule_ids' field to graphql. (https://github.com/scandipwa/quote-graphql/pull/38)
If applied_rule_ids is null then no discount in cart.
If applied_rule_ids is not null, but coupon_code is null then show discount not as coupon.
=> SWPWA-1406 Discount/Coupon logic adjust render in summary blocks

src/app/component/CartItemPrice/CartItemPrice.component.js, src/app/component/CartOverlay/CartOverlay.component.js, src/app/component/CategoryConfigurableAttributes/CategoryConfigurableAttributes.component.js, src/app/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js, src/app/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js, src/app/component/MyAccountOrderPopup/MyAccountOrderPopup.component.js, src/app/component/MyAccountOrderTableRow/MyAccountOrderTableRow.component.js, src/app/component/ProductCustomizableOption/ProductCustomizableOption.container.js, src/app/component/ProductPrice/ProductPrice.component.js, src/app/component/ProductPrice/ProductPrice.container.js, src/app/component/TierPrices/TierPrices.component.js, src/app/route/CartPage/CartPage.component.js, src/app/util/Price/Price.js
fixes: #1330 
it is probably a breaking change if others use ProductPrice.component directly as its props schema changed, Util/Price/formatCurrency is not used now in the codebase but could be elsewhere so it is left in the utils file, so it is currencyMap
=> Format prices and currency using Intl library

src/app/route/PasswordChangePage/PasswordChangePage.container.js
Fixed #1366 Update Password on Forgot Password Page Doesn't Work
Description:
When we click on Forgot your account password? Click here to reset it. in Email, we landing to Update Password Page.
Fill all inputs
Push Update Password
And nothing is happening.
Demo - https://prnt.sc/urrgix
Local - https://prnt.sc/urrn4t
Versions:
ScandiPWA: 2.16.2 locally and on Demo
=> Fixed #1366 Update Password on Forgot Password Page Doesn't Work

src/app/query/MyAccount.query.js
To reproduce error:
1. No items in cart
2. Clear local storage
Basically in customer-graph-ql last version it is allowed for guest_quote_id to be null https://github.com/scandipwa/customer-graph-ql/commit/7ed84251fe59698c7e5e8876ce7362087a4cbfdd. But in MyAccount.query.js it is not allowed to be null. Since that error appears when receiving data from query and now it is allowed in query also to be null.
Tested. Seems all to work.
=> SWPWA-1459 - Accept getting null value for guest_quote_id

src/app/route/ProductPage/ProductPage.container.js
- Created scrollTopIfPreviousPageWasPLP and added it to ProductPageContainer onMount, to scroll to top if user goes from PLP to PDP
* Fix is both for mobile and desktop.
=> SWPWA-1544 - Product page opens already scrolled down on mobile

src/app/store/Cart/Cart.dispatcher.js
If guest is making an order then cart is not updated on FE since guest_quote_id is null and cart is showing cart_id= error since on BE it is gone. So if guest makes an order then after just create new empty cart for guest.
=> SWPWA-1511 Create new empty cart after guest complete order

src/app/route/CartPage/CartPage.component.js
If cart is empty - in order summary totals tries to calc undefined.
=> SWPWA-1614 Fix NAN in order summary

composer.json, src/config/webpack.development.config.js, src/config/webpack.production.config.js, src/public/index.development.html, src/public/index.production.phtml
While fixing this issue, there was need to create new customizable options for Webmanifest support, so please first check pull request in scandipwa/customization: https://github.com/scandipwa/customization/pull/3
In this task main goal was to replace static .ico file that was located in public/assets/favicon to M2 admin panel defined favicon, for that reason path for favicon is changed to "media/favicon/favicon.png" as Magento uploads files to this folder.
Other issue was that webmanifest nodejs module was overriding icons with static icon, and changing location target path may cause crashes on redeployment, as its only generated on that time. To fix this there new support for webmanifest & favicons was created (_check above mentioned pull request_) that uses M2 favicon as appicon and …
=> #1392 Favicon change through admin / M2 Support

src/app/component/InstallPrompt/InstallPrompt.container.js
Storing promt install event in window scope variable to get it after component was unmounted.
This could fix issue #1619 and others issues related to "Add to Home screen" on Android.
=> Add To Home Screen Fix

src/public/index.development.html, src/public/index.production.phtml
- Updated paths to correct url
- Removed ";" in \<link\> generation
- Favicon updates without Magento cache cleaning (requires local refresh)
Requires this PR to work: https://github.com/scandipwa/customization/pull/5
=> #1392 Fixed url paths for favicon & manifest

src/app/component/CookiePopup/CookiePopup.component.js, src/app/component/CookiePopup/CookiePopup.container.js, src/app/component/Link/Link.container.js, src/app/component/StoreSwitcher/StoreSwitcher.config.js, src/app/component/StoreSwitcher/StoreSwitcher.container.js
Just right after the store was switched, redux took the previous store config from the localStorage.
And after a moment a new store config were arriving from the backend.
But CookiePopup component took old store code and thus it didn't behave correctly.
Now before store is switched the config is removed from the localStorage.
Now after store was switched, it acts like is was loaded in a clean browser.
Additionally i've fixed errors from the console, that appeared when website was loaded in a browser with a clean localStorage.
=> Fixed popup component behaviour on store switch

src/app/component/CheckoutBilling/CheckoutBilling.container.js, src/app/component/CheckoutShipping/CheckoutShipping.container.js, src/app/route/Checkout/Checkout.container.js
Fixes #1436
Added an option for billing request in order to prevent customer address duplicating
=> Customer Address getting duplicated when an order is placed

src/app/component/ProductGallery/ProductGallery.component.js, src/app/store/LinkedProducts/LinkedProducts.dispatcher.js
Fix double wrapping of linked product sku. 
That is, was sending request with each sku quotes double wrapped like : 
filter_1={"sku":{"in":[""n31350783""]}
now : filter_1={"sku":{"in":["n31350783"]}
Also noticed that if try to visit linked product from PDP than error appears: "Cannot read property "current" of undefined"
So just clarify if logic in productGallery.component
=> SWPWA - 1520 - Fix linked products double-quoting + slider issue

src/app/component/ProductAttributes/ProductAttributes.style.scss, src/app/component/ProductInformation/ProductInformation.style.scss, src/app/component/ProductReviews/ProductReviews.component.js, src/app/component/ProductReviews/ProductReviews.style.scss, src/app/component/ProductTab/ProductTab.style.scss, src/app/component/ProductTabs/index.js
Hide product expandable titles in product tabs for desktop/tablet. Increase font-size of tabs to 18px (PM request). Fix eslint (add license commit into ProductTabs/index.js).
=> #1874 - Remove titles from product tabs on desktop + tabs font-size increase

src/app/component/NewProducts/NewProducts.component.js, src/app/component/NewProducts/NewProducts.style.scss
https://github.com/scandipwa/scandipwa/issues/1833
'new product widget' now renders in grid 
product pods are the same size
=> issue #1833 'new product widget' renders in grid

src/app/component/CategorySort/CategorySort.style.scss
#https://github.com/scandipwa/scandipwa/issues/1783
On mozzila arrow by "sort by" now appears at middle
=> issue #1783 Mozzila arrow by sort appears at middle

src/app/component/Slider/Slider.style.scss
In this PR:
* Removed pagination in mobile
* Made Slider full-screen in mobile & tablet
Placeholder
* Placeholder for slider is showing, but due to slow internet images that are displayed may be outputted after widget is loaded.
=> #1881 Slider adjustments + placeholder

src/app/component/ProductBundleItem/ProductBundleItem.container.js, src/app/component/ProductBundleItems/ProductBundleItems.container.js
Requires PR: https://github.com/scandipwa/catalog-graphql/pull/80
1. Moved property access outside loop
2. Changed from regular_price to final_price to include products discount.
=> #1872 Usage of correct price values for bundle products

src/app/component/Slider/Slider.component.js, src/app/component/SliderWidget/SliderWidget.component.js, src/app/component/SliderWidget/SliderWidget.container.js
Original issue: #1881 
* **Slider.component.js** - added slider-height definition on mount to remove slider from changing size when visible... meaning that after load its height is 0 and after some time its height is set to correct height (_popping up effect_).
* **SliderWidget** - added `renderPlaceholder()` instead of return `null`, because `WidgetFactory` & `RenderWhenVisible` does not respond to `null` type returns, instead they are using different criteria to determine if  widget has finished loading, so returning `null` will just make an empty object.
=> #1881 Placeholder + popping up slider fix

src/app/component/CartItem/CartItem.container.js, src/app/route/CartPage/CartPage.component.js, src/app/route/CartPage/CartPage.container.js, src/app/store/Cart/Cart.dispatcher.js, src/app/store/LinkedProducts/LinkedProducts.dispatcher.js, src/app/store/LinkedProducts/LinkedProducts.reducer.js
Fixed #1886, #1887
Took out related product update from the cart dispatcher.
Moved cross-sell product fetching and clearing to the separate methods.
=> Upsell, Cross-sell and related product display issue

packages/scandipwa/src/component/Klarna/Klarna.component.js
Issue was, that when Klarna failed to load, it also did not create DOM element... so when trying to delete it when switching to different payment method js error was outputted and crashed the system... added value check to prevent this from happening.
=> #1690 Fix for unable to change payment after klarna selection

packages/scandipwa/src/store/Config/Config.reducer.js
In this PR:
- Using cached countries when performing page reload, otherwise they are `null`, that causes many dependent components to crash website with message "ooops", as they have `.required` prop type.
=> #1761 Fix for ooops on purchase page when changing currency

packages/scandipwa/src/component/CategoryConfigurableAttributes/CategoryConfigurableAttributes.component.js, packages/scandipwa/src/component/CategoryConfigurableAttributes/CategoryConfigurableAttributes.container.js
* https://github.com/scandipwa/catalog-graphql/pull/82
* Switched from `state.ConfigReducer.default_display_currency_code` to `state.ConfigReducer.currencyData.current_currency_code` as old implementation shows default store currency not current
* Updated price calculations, by multiplying `price` with `currency_rate` _(check catalog-grapql pull request)_
=> #1760 Currency convertion in layerd navigation

packages/scandipwa/src/query/Config.query.js, packages/scandipwa/src/route/CmsPage/CmsPage.container.js
fixes #1554 
fixes #1553 
Get default_description in query.
Also add meta_keywords for cms pages.
=> Get back default_description for meta

packages/scandipwa/src/component/CarouselScroll/CarouselScroll.style.scss
- So as observed in firefox the right side of the frame is being hidden by the slider image and just a little 1px padding from the right made it appear in every resolution, also tried to add right property but then left side starts to disappear in chrome, so in overall this padding works in chrome as well as in firefox.
=> Firefox(Win): Frame (right side) of small photos is missing on the left side of product page #1672

packages/scandipwa/src/component/CartItem/CartItem.style.scss, packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js, packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.config.js, packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.container.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.config.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.container.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss, packages/scandipwa/src/query/Config.query.js, packages/scandipwa/src/query/ProductList.query.js
fixes #1508
fixes #1625 
Related PR :
https://github.com/scandipwa/store-graphql/pull/9
https://github.com/scandipwa/catalog-graphql/pull/85
Adds check if price in catalog and shipping price should excl/incl tax or should be displayed both. 
Atm magento 2 is not providing excl tax price in graphql, so while it is not supported added excl tax price in price range response.
=> Respect price tax diplay settings

packages/scandipwa/src/component/CartOverlay/CartOverlay.component.js, packages/scandipwa/src/component/CartOverlay/CartOverlay.container.js, packages/scandipwa/src/util/Cart/Cart.js
Fixed the setting that configures what to display as price in the delivery method list (see #1982).
Fixed zero tax display in minicart.
=> Some minor minicart and delivery method list fixes

packages/scandipwa/src/route/MyAccount/MyAccount.container.js
Fixes issue #1748.
Fixed as well updateBreadcrumbs as previously this method was triggered always when component did update because prevActiveTab was incorrectly destructed.
=> #1748 - Mobile: Wishlist title stays on my account page

packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/util/CSS/CSS.js
Fixes issue #1444 
Also, resolves an issue where we get `Cannot read property 'current' of undefined` when clicking on a related product.
=> #1444 - Reset qty when navigating from PDP to PDP via click on related products

packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js
Fixes swipe delete. Correction for https://github.com/scandipwa/scandipwa/issues/1918
=> Mobile: Page leads to Ooops page if user deleted product with swipe delete from the Wishlist and then deleted product in edit mode

packages/scandipwa/src/component/AddToCart/AddToCart.container.js, packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js, packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.container.js
Fixes #2062 
Fixed add to cart button behavior for bundled, configurable and customizable products.
Fixed product redirect to 404 before loading product page.
Related PR
scandipwa/compare-graphql/pull/6
=> Add To Cart Button In Compare Page

packages/scandipwa/src/route/CmsPage/CmsPage.component.js, packages/scandipwa/src/route/CmsPage/CmsPage.container.js, packages/scandipwa/src/route/NoMatch/NoMatch.container.js, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.component.js, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.container.js
Fixes issue #1559 
- Added logic that renders a 404 page in cases when the CMS page is disabled and not fetched
- Moved the no match reducer update from UrlRewrites to NoMatch component
I remember that in previous versions of SWPWA we were able to render the 404 page just by setting the `noMatch: true` in the NoMatch reducer but for some reason, it doesn't work anymore - why so? I noticed that in the ContactPage component the NoMatch component is rendered directly so I ended up doing the same.
=> #1559 - 'Not found' page isn't rendered if a disabled CMS page is loaded

packages/scandipwa/src/util/Request/Request.js
Fixes #425
Added window id to broadcast channel name in order to prevent shared contexts between tabs.
Window id is stored in the sessionStorage since it's isolated per tab and is removed on tab close.
=> Broadcast shared context

packages/scandipwa/src/component/ProductAttributes/ProductAttributes.component.js
Removed unnecessary check for whether the Information tab is empty or not, since we don't care of it. We want to render product details if those are loaded
=> Removed unnecessary check for if information tab empty

packages/scandipwa/package.json, yarn.lock
There were an issue in CRA repo, that crashed project startup on Windows.
scandipwa/create-scandipwa-app#11
But after merge `@scandipwa/webpack-i18n-runtime` package version didn't updated in this repo.
Thus fresh installs still fetched old package with the bug.
Updated `@scandipwa/webpack-i18n-runtime` package version in order to fix installs.
=> @scandipwa/webpack-i18n-runtime update

packages/scandipwa/src/component/Field/Field.container.js, packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js, packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.container.js
Bug: https://github.com/scandipwa/scandipwa/issues/2162
**Root cause of the issue:**
Method `validateField` of Field component is able to work only with fields that are part of a form.
https://github.com/scandipwa/scandipwa/blob/master/packages/scandipwa/src/component/Field/Field.container.js#L174
As ProductCustomizableOption text field is not part of any form, current implementation always returns validationStatus equal to `true` => field will always have green borders once you start typing.
Even if you modify `validateField` to work with single fields + add validation rule `not empty` to `ProductCustomizableOption` component, you encounter the problem that error messages are duplicated:
The reason for this is that ProductCustomizableOption already has customized error messages, apart …
=> [QA FIX] #2162 wrong border color in ProductCustomizableOption text field

packages/scandipwa/src/component/CartCoupon/CartCoupon.container.js, packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js, packages/scandipwa/src/component/CheckoutOrderSummaryPriceLine/CheckoutOrderSummaryPriceLine.component.js, packages/scandipwa/src/component/Field/Field.component.js, packages/scandipwa/src/route/Checkout/Checkout.component.js, packages/scandipwa/src/route/Checkout/Checkout.container.js
Fixes #2081
There are two ways how coupon is affecting shipping.
1. When coupon is applied, free shipping delivery method is displayed on the checkout shipping page.
https://docs.magento.com/user-guide/marketing/price-rules-cart-free-shipping.html
2. Selected shipping method gets discount.
https://community.magento.com/t5/Magento-2-x-Admin-Configuration/50-Off-Shipping-Rule/m-p/126798/highlight/true#M3861
We are not calculating cart totals.
Thus for the second case cart totals are updated according to magento cart logic.
We don't update the shipping price / grand total on delivery method change.
And since we don't have ability to select a delivery method on the cart page, we still see same estimated shipping price after coupon is applied.
So i've added ability to reload delivery method …
=> Free Shipping Coupon Fixes

packages/scandipwa/src/component/ClickOutside/ClickOutside.component.js, packages/scandipwa/src/component/Overlay/Overlay.container.js
Fix the error with null refs when using <Overlay> component as direct child of <ClickOutside>.
Reason for the issue is that Overlay is not a DOM element, refs need to be forwarded for "handle click outside target" logic to work correctly.
=> #2181 ClickOutside with overlay

packages/scandipwa/src/component/CheckoutAddressForm/CheckoutAddressForm.component.js, packages/scandipwa/src/component/CheckoutAddressForm/CheckoutAddressForm.container.js, packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js, packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.container.js, packages/scandipwa/src/query/Config.query.js, packages/scandipwa/src/query/Region.query.js
Fixes #2063 
Goes together with:
[directory-graphql/pull/1](https://github.com/scandipwa/directory-graphql/pull/1)
[store-graphql/pull/16](https://github.com/scandipwa/store-graphql/pull/16)
Support setting 'Allow to Choose State if It is Optional for Country', in this case if yes, then for all countries state/province can be added. In case if no, then state/province field is not present if only country is not requiring it from setting above.
=> issue-2063 - Add support for require country state/province

packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js
FE fix to load product tile correctly in wishlist, if for some reason (rare case, but possible) configurable product is added to wishlist without required options. The following logic is implemented:
- Thumbnail and price of base product are loaded and displayed
- On click on Add to cart button user is redirected to product page with info message "Please select required option"
Also includes fix for BE (previously backend threw an error when fetching withlist and no items were displayed to user in wishlist)
=> bugfix #2197 configurable wishlist item without required options

packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.component.js, packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.style.scss, packages/scandipwa/src/component/StoreSwitcher/StoreSwitcher.style.scss
Select currency option was removed from Android devices.
Removing the option broke select layout, which is why style modifications very required.
Also fixed alignment of the 2 dropdowns (currency and country) on mobile version.
=> #1745 Remove currency option and fix styles

packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.config.js, packages/scandipwa/src/component/ProductCard/ProductCard.container.js, packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
Fixes #2041 
Fixes #1996
Previously for product cards it was getting first element from configurable_options property and if it was not containing swatch data then product card was without visual attributes. 
Example:
```
configurable_options: {
{ label: size, swatch_data: null, type null }
{ label: color_images, swatch_data: {....}, type: 2 }
}
```
It was getting only size attribute and since there is no swatch_data: result is empty for product card.
Also implemented support for images type.
=> Fix issue with swatch_data selection for product cards

packages/scandipwa/src/component/MyAccountDownloadable/MyAccountDownloadable.component.js, packages/scandipwa/src/component/MyAccountDownloadable/MyAccountDownloadable.container.js, packages/scandipwa/src/component/MyAccountDownloadableTableRow/MyAccountDownloadableTableRow.component.js, packages/scandipwa/src/component/MyAccountDownloadableTableRow/MyAccountDownloadableTableRow.container.js, packages/scandipwa/src/component/MyAccountDownloadableTableRow/MyAccountDownloadableTableRow.style.scss
Requires PR: https://github.com/scandipwa/customer-downloadable-graphql/pull/1
Original issue: #2270 
In this PR:
* Shows order popup on order id click
* Shows status
* Renders title without link if not provided
* DOM class fix - from 'MyAccountOrderTableRow' to 'MyAccountDownloadTableRow'
=> #2270 Downloadable my-account fixes

packages/scandipwa/src/component/CheckoutAddressForm/CheckoutAddressForm.component.js, packages/scandipwa/src/component/Field/Field.container.js, packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js, packages/scandipwa/src/util/Address/index.js
Fix for https://github.com/scandipwa/scandipwa/pull/2152, which actually turned out to be not working at all, not just http vs https issue. Changes made:
- changed HTTP to HTTPS
- fixed error with city not being set at all (nothing was returned from method `getCityFromZipcode`)
- added autofill for state (as it looks dull, when the city is being autocomplete and the state (= region) is not)
- added autofill to Shipping and Billing steps, not just Address book
- validation status update for `city` field (`onChange` is not triggered in such a case)
=> bugfix #2287 - city and state autofill

packages/scandipwa/package.json, packages/scandipwa/src/route/ProductPage/ProductPage.container.js
The reason for the issue is that after getting back to product (via breadcrumbs, not pure page reload) `productOptionsData` props in `ProductActions` component is empty, while it should contain the list of required options.  As a result client side validation doesn't work => adding to cart fails with a different error message due to server side validation.
Root cause of the issue is in `ProductPage` container. It has logic that compares `prevProps` to  `currentProps` in order to minimize data requests and rerenders (https://github.com/scandipwa/scandipwa/blob/master/packages/scandipwa/src/route/ProductPage/ProductPage.container.js#L199). The steps described in the bug lead to product data being dispatched from `ProductReducer` instead of reloading all product data from the server (the …
=> bugfix #2057 missing required options validation after product revisit  

packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductActions/ProductActions.container.js, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.container.js, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.style.scss, packages/scandipwa/src/query/ProductList.query.js, packages/scandipwa/src/route/ProductPage/ProductPage.component.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js
Original issue: #2304 
Required PR to work: https://github.com/scandipwa/catalog-graphql/pull/89
In this PR:
* Added samples title output
* Position and styling fixes for sample
* Styling fixes for product title 
* Styling and render location changes for links to match luma
* Required '*' for links title
* Hides check-boxes if not required (keeps link list)
* Price update for downloadable product
=> #2304 Downloadable product fixes

packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js
https://github.com/scandipwa/scandipwa/issues/2310
We don't need to perform `isCurrentCategoryLoaded` check or Search page, as it is not a category and no category data request is performed when search page is loaded.
And this category data request is exactly the reason why this check has been added. See explanation here
https://github.com/scandipwa/scandipwa/blob/9377a1434cef23a7b2e38bbdab92f6ab03c4a035/packages/scandipwa/src/component/CategoryProductList/CategoryProductList.container.js#L88
```
* Do not request page, if category is not yet loaded
* without this command the products are requested twice:
* 1. Once with global default sorting
* 2. Once with category default sorting
```
=> #2310 - search page endless loader

packages/scandipwa/package.json
Reverted proxy host and % of browsers in the browserlist query
=> bugfix #2265 - Revert proxy and browserlist percentage

packages/scandipwa/src/component/Footer/Footer.style.scss, packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.style.scss, packages/scandipwa/src/style/base/_link.scss, packages/scandipwa/src/style/cms/block/homepage-category-preview.scss
Issue: https://github.com/scandipwa/scandipwa/issues/1822
- Remove `a + a: { margin-left: 1.2rem }` generic style
- Remove its overrides to `a + a: { margin: 0 }`, as it is not necessary any more
=> #1822 - remove a + a too generic style

packages/scandipwa/src/component/Header/Header.style.scss, packages/scandipwa/src/component/Popup/Popup.style.scss
Actually header behaviour is correct. The problem is that write review form stays in place when the address bar appears and viewport size updates. Write review form should move down when it happens.
=> bugfix #1884 write review header blinking

packages/scandipwa/src/component/Image/Image.style.scss
This PR fixes the following home page image placeholder behavior:
=> Added the lower stack order to the background placeholder

packages/scandipwa/src/component/ExpandableContentShowMore/ExpandableContentShowMore.component.js
Removed explicitly setting filter area height.
Tested in Chrome, FF and even Safari 10 after removal - found no difference in behaviour other than the bug is gone.
=> bugfix #2250 - invalid filter area height

packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.style.scss
Issue: #2400 
1. Samples title is displayed only if samples exist
2. Instead of star, text: "This field is required!" is displayed
3. Negotiated to implement indent as in luma - big indent and not bold link
4. Link option is in line with other elements
=> Bugfix #2400

packages/scandipwa/src/component/CartItem/CartItem.container.js, packages/scandipwa/src/component/ProductCard/ProductCard.container.js, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.component.js, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.container.js, packages/scandipwa/src/util/Url/Url.js
Issue: https://github.com/scandipwa/scandipwa/pull/2426
Related to https://github.com/scandipwa/scandipwa/pull/2183.
**Reason for the problem:**
When we go to Product Page from search results, `ProductPageContainer` receives key equal to product_id (e.g. 1351, for product http://scandipwapmrev.indvp.com//default/n-seventy-transitional-jacket-13.html). When we select another size on Product Page, the key is reset to `null`. When the page is loaded directly, key equals `null` as well. So in order that issue #2426 doesn't appear, it is needed key not to change when changing product options (to have it equal to null, product_id or some other unique identifier of the product).
Using product_id as key when product is loaded directly is tricky, as you still don't know product id, when this line …
=> #2426 - page jumps up

packages/scandipwa/src/route/Checkout/Checkout.container.js
Fixed #2500 
Fixed checkout workflow if purchase order payment method is selected.
Issue happens only if address form is visible on the billing step.
=> Purchase Order Fix

packages/scandipwa/src/component/ProductTabs/ProductTabs.component.js, packages/scandipwa/src/route/ProductPage/ProductPage.component.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js
This commit is a simple logic refactoring since the following code looks really confusing:
```js
if (!item.shouldTabRender()) {
tabRenders.push(item.render(item.name));
}
```
This literally means that we render tab if we shouldn't render it. Doesn't sound optimistic, especially considering that this logic is correct, despite the fact of working vice-versa
=> Refactored product tabs render logic

packages/scandipwa/src/util/History/index.js
Fixes #2506 
Fixed swipe back previews on mobile browser.
The issue happened if you scroll page a bit and swipe back.
This happened due to manual scroll restoration.
Manual scroll restoration was added for a PDP page scroll fix, but this issue was actually fixed in a different way.
So the manual scroll restoration is not needed.
=> Swipe Back Preview Fix

packages/scandipwa/src/component/NewVersionPopup/NewVersionPopup.style.scss, packages/scandipwa/src/component/Popup/Popup.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/2424
Caused by https://github.com/scandipwa/scandipwa/issues/2397, the fact that mobile popup should be placed just below the header was missed out.
=> #2424 - mobile popup invalid top position

packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js
fixes #2484 
Related: https://github.com/scandipwa/customer-graph-ql/pull/17
In case if there is no region selected from options that country can provide (it just doesn't provides them) we send 0  in region_id to BE. 
Also fixed issue when opening address edit and if current country requires state, it was not showing it at first time, only if we select any country and then select back previous it will show us state field.
=> Adjust region handle on myaddress edit

packages/scandipwa/src/component/MenuItem/MenuItem.component.js, packages/scandipwa/src/component/MenuItem/MenuItem.config.js, packages/scandipwa/src/component/MenuItem/MenuItem.container.js
To improve site UX - Have a `250ms` delay for the main menu to open. Now moving the mouse over the menu item opens the submenu even when I do not want it. It is distracting.
This fix will open menu with a slight delay, this will result in menu opening only if user intended to open the menu.
=> Will delay opening menu slightly

packages/scandipwa/src/component/RecentlyViewedWidget/RecentlyViewedWidget.container.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js, packages/scandipwa/src/store/RecentlyViewedProducts/RecentlyViewedProducts.action.js, packages/scandipwa/src/store/RecentlyViewedProducts/RecentlyViewedProducts.reducer.js
Original issue: #1780 
**Issue**:  
Multi-store website setup with same base URL shares recently viewed products, because products are stored locally inside ```localStorege``` without indication of which store is targeted.
**Solution**
Added access by ```store_code``` for recently viewed products to differ between instances.
=> #1780 Multistore recently viewed products

packages/scandipwa/src/component/MyAccountMyOrders/MyAccountMyOrders.style.scss
#2467
1. Applied table width styling also to My downloadables table not only My orders. Fixing the table width.
2. Changed table-layout for My downloadables mobile view. Fixing the column overlapping which was the result of table width change.
=> #2467 bugfix - narrow table in my downloadable in safari

packages/scandipwa/package.json, packages/scandipwa/src/route/Checkout/Checkout.container.js
Current  ScandiPWA logic sends `regionCode` as value of `region` field on billing step. It works fine, unless code is numeric due to the following Magento logic (https://github.com/magento/magento2/blob/aaeadff2f3130f2ddf14018cb64ca259799d1a1c/app/code/Magento/Customer/Model/Address/AbstractAddress.php#L426):
```
public function getRegionId()
{
$regionId = $this->getData('region_id');
$region = $this->getData('region');
if (!$regionId) {
if (is_numeric($region)) {
$this->setData('region_id', $region);
$this->unsRegion();
} else {
$regionModel = $this->_createRegionInstance()->loadByCode(
$this->getRegionCode(),
$this->getCountryId()
);
$this->setData('region_id', $regionModel->getId());
}
}
return $this->getData('region_id');
}
```
If region code is numeric it is being interpreted as …
=> #1829 - billing step failure france

packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js
Fixed [issue#2575](https://github.com/scandipwa/scandipwa/issues/2575)
=> Bugfix #2575 - The text "Choose Option" in the dropdown list isn't diplayed in Firefox 76 or previous versions

packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.container.js, packages/scandipwa/src/component/RecentlyViewedWidget/RecentlyViewedWidget.component.js, packages/scandipwa/src/component/RecentlyViewedWidget/RecentlyViewedWidget.container.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js, packages/scandipwa/src/store/Cart/Cart.reducer.js, packages/scandipwa/src/store/RecentlyViewedProducts/RecentlyViewedProducts.action.js, packages/scandipwa/src/store/RecentlyViewedProducts/RecentlyViewedProducts.dispatcher.js, packages/scandipwa/src/store/RecentlyViewedProducts/RecentlyViewedProducts.reducer.js, packages/scandipwa/src/util/Product/Product.js
Fixes #2628
Localstorage max size is 5mb. In case if we add https://master.d25kd40decjpue.amplifyapp.com/default/ciunas.html into cart or just visit it so it is automatically added into recentView we are getting error, because localstorage is overcrowded. Products has a lot of options to select from => a lot of variations is added into cart_totals for this products. 
1. Add into cart_totals not all variants, but only 1 that is shows in cart, since we don't use others.
2. For recently viewed products we can save only preview of product, when we enter page with recently viewed product widget we can see those products, we can click on them, but options are loading from BE, because we are not holding them in localstorage. (while we waiting for full product data, we are just showing …
=> issue-2628 - Rework adding to localstorage products data

packages/scandipwa/src/component/CategoryConfigurableAttributes/CategoryConfigurableAttributes.component.js, packages/scandipwa/src/component/CategoryConfigurableAttributes/CategoryConfigurableAttributes.container.js
Fixed [issue#2461](https://github.com/scandipwa/scandipwa/issues/2461)
=> #2461 Bugfix - Wrong subcategories are displayed in Layered navigation if the product belongs to few categories

packages/scandipwa/src/component/Header/Header.style.scss
=> fix stretched logo

packages/scandipwa/src/component/StoreInPickUpStore/StoreInPickUpStore.component.js
fixes #2774 
If description is empty for store it brings null as description.
=> Fix description rendering on in-delivery

packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.component.js
Issue: https://github.com/scandipwa/scandipwa/issues/2748
BE PR: https://github.com/scandipwa/performance/pull/20
FE fix was required as ANY value was interpreted as YES, while "0" is actually false and NO.
=> #2748 fix invalid boolean attribute value

packages/scandipwa/src/component/Router/Router.container.js, packages/scandipwa/src/query/ProductCompare.query.js, packages/scandipwa/src/store/ProductCompare/ProductCompare.action.js, packages/scandipwa/src/store/ProductCompare/ProductCompare.dispatcher.js, packages/scandipwa/src/store/ProductCompare/ProductCompare.reducer.js
https://github.com/scandipwa/scandipwa/issues/2735, issue 5.
Code fetching data on page load was removed by Richard when switching to compare-graphql module and refactoring for some reason. I added it back and made required fixes to match the updated version + rewrote logic a bit to require only product ids of products in Compare list instead of all products data for better performance.
=> #2735 getting compare list items ids on PDP and PLP load

packages/scandipwa/src/store/RecentlyViewedProducts/RecentlyViewedProducts.reducer.js
fixes #2673 
If product is removed from website or just disabled it won't return from BE data about it, but since we store preview of products in localstorage it is necessary to update it also so product will be removed from recently viewed.
=> Update recentlyViewdPRoducts after fetch

packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.container.js, packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.container.js
Fixes #2266
Hid out of stock subproducts of bundled or grouped product if they are out of stock, like this is done in luma.
=> Bundle Grouped Out Of Stock Fix

packages/scandipwa/src/component/AddToCart/AddToCart.component.js, packages/scandipwa/src/component/AddToCart/AddToCart.container.js, packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductCompare/ProductCompare.container.js, packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.container.js, packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.container.js, packages/scandipwa/src/component/ProductInformation/ProductInformation.component.js, packages/scandipwa/src/component/SharedWishlistItem/SharedWishlistItem.component.js, packages/scandipwa/src/store/ProductCompare/ProductCompare.dispatcher.js
Fixes #2821
Fixed Add To Cart Button on Compare Page.
Added explicit `disabled` attribute so there is no magic why the button is disabled on the certain pages, but enabled on others.
=> Add To Cart Button Fix On Compare Page

packages/m2-theme/public/index.php, packages/scandipwa/public/index.html, packages/scandipwa/src/component/Link/Link.container.js, packages/scandipwa/src/util/Url/Url.js
Fixes #2818
1. Added reverse sort to `storeList` in order to prevent the issue when some store codes are part of order and replace works incorrectly, like `en` and `en_us`.
2. Fixed `getTo` method.
3. Fixed `storeList` regexp issues, when store code was searched in the middle of the url.
4. Fixed some eslint errors.
=> Multistore Fix

packages/scandipwa/src/util/Query/PrepareDocument.js
Sometimes we have to examine GraphQL requests outside the page context.
1. When we need to make a single request instead of loading all requests on page reload.
2. When we need to reduce the field amount in order to see less distracting info.
3. When the request is cached.
Normally the request can be seen on the Networks tab in the DevTools. But if the request is cached, we see only it's hash id.
In order to solve this issue, i add the code i provided in this PR.
After that i can see all requests in the console in the same order they appear on the Network tab.
Then i can find the request i need, copy it's query to the GraphQL Playground, prettify it, copy variables and launch it.
Pretty useful when investigating backend issues.
I'd like to add it to the project, so everyone can use it. …
=> GraphQL Log Proposal

packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductActions/ProductActions.container.js
fixes #2375 
Show configurable option if exist variant for it on PDP. Same magento 2.4.2 doesn't shows option if attribute exist, but no variant for current store.
=> Not show configurable option if not assigned to current website

packages/scandipwa/src/component/Popup/Popup.component.js, packages/scandipwa/src/component/Popup/Popup.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/2616
Error message is displayed BELOW popup and invisible, as the popup is fullscreen. The solution here is to show the message inside popup as well, so that user sees it. Only applicable to mobile.
=> #2616 - no error message inside mobile pop-up

packages/scandipwa/src/component/NavigationAbstract/NavigationAbstract.container.js, packages/scandipwa/src/component/NavigationTabs/NavigationTabs.component.js, packages/scandipwa/src/component/NavigationTabs/NavigationTabs.container.js, packages/scandipwa/src/util/Url/Url.js
Fixes https://github.com/scandipwa/scandipwa/issues/2856
**Issue 1:** wrong active menu tab, if no trailing slash
**Reason for problem:** `/default` was not treated as Home page and logic failed back to default tab, which is MENU TAB.
**Issue 2:** wrong active menu tab when cache is empty.
**Reason for problem:** default store URL is received from the server, stored to Redux store and taken from there to decide what store prefix should be used. On first page load there is no such data in the store yet. As a fallback store prefix is detected from current URL, but this piece of logic skipped the important URI part (i.e. `/default`) and detected store prefix in a wrong way.
=> #2856 - Fix trailing slash homepage navigation

packages/scandipwa/src/component/ProductActions/ProductActions.component.js
Original issue: https://github.com/scandipwa/scandipwa/issues/2798
In this PR: Added array size check, so that title is not visible, when array is empty.
=> #2798 Hide product samples title when empty

packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.config.js, packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.container.js
Original issue: https://github.com/scandipwa/scandipwa/issues/2716
In this PR: Added delayed check for filled form
react, chrome & IOS doesn't support any kind of event triggering for auto-filled form elements, thus value is not passed to react and onValueChanged is not triggered,... to resolve this requires direct data access from DOM element, ether by delay or loop check.
=> #2716 Chrome & IOS autofil email check on checkout

packages/scandipwa/src/component/RecentlyViewedWidget/RecentlyViewedWidget.component.js
**Original issue**: https://github.com/scandipwa/scandipwa/issues/2899
**Problem**: Component returns React as null
**Solution**: Changed import for React
=> 2899 Recently viewd widget undefined React fix

packages/scandipwa/src/component/ProductCard/ProductCard.component.js
Issue: https://github.com/scandipwa/scandipwa/issues/2923
Problem appeared after migrating from `PureComponent` to `Component` with `componentShouldUpdate`. It turned out that `componentShouldUpdate` had "update component when selected configurable options changed" condition missing.
=> #2923 - fix swatches not selecting

packages/scandipwa/src/component/ProductCompare/ProductCompare.component.js
Original issue: https://github.com/scandipwa/scandipwa/issues/2850
In this PR:
* Added missing label map that outputs labels for product price based on their type (similar as to how it's done in ProductCard), to mach PLP page price labels
=> #2850 Match price label in compare list to be same as in PLP

packages/scandipwa/src/util/Product/Product.js
Original issue: https://github.com/scandipwa/scandipwa/issues/2757
In this PR: Added, so that configurable options are passed to graphql for virtual type products
=> #2757 Costumizable option support for virtual products

packages/scandipwa/src/component/CategorySort/CategorySort.container.js, packages/scandipwa/src/query/ProductList.query.js, packages/scandipwa/src/route/SearchPage/SearchPage.config.js, packages/scandipwa/src/route/SearchPage/SearchPage.container.js
Original issue: https://github.com/scandipwa/scandipwa/issues/2468
In this PR:
* Added option to remove sort from search page to mach same results as in search bar
* Set default search result sort as 'none'
=> #2468 Same results in search page as in search bar

packages/scandipwa/src/component/Header/Header.style.scss, packages/scandipwa/src/component/ProductCard/ProductCard.container.js
Issue: https://github.com/scandipwa/scandipwa/issues/2925
Why problem appears: such data as product variants is not stored in localstorage, some time is needed for secondary product data to be requested from the server. Error `Cannot read property filter of undefined` appears due to variants being undefined during this time. So I'm just setting default value of variants to empty array to avoid errors while data is loading. 
Also fix missing curly brace in this PR.
=> #2925 - error on opening secondary viewed products

packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.container.js
Original issue: https://github.com/scandipwa/scandipwa/issues/2716
In this PR:
* Resetting email status on component load.
=> #2716 Show login form on re-visited shipping step

packages/scandipwa/src/component/ProductCompare/ProductCompare.component.js, packages/scandipwa/src/component/ProductCompare/ProductCompare.style.scss
Issue: https://docs.google.com/spreadsheets/d/1xxtBOYtJdW53N-Gr7OUVnFO7qjnE0bNZKYLaMgIrO6w/edit?ts=60defb5b#gid=2035403278
Problem: Prices don't start from the 1st column in mobile view, which leads prices to be shown below wrong product titles (prices are shifted right by 1 cell)
=> fix compare list: price column mobile scroll

packages/scandipwa/src/component/ProductList/ProductList.component.js
Revert https://github.com/scandipwa/scandipwa/pull/2809/files.
(Do `window.scrollTo({ top: 0 });` on every `componentDidUpdate` is not a good idea).
Fixes https://github.com/scandipwa/scandipwa/issues/2924, https://github.com/scandipwa/scandipwa/issues/2958 and https://github.com/scandipwa/scandipwa/issues/2968.
=> #2958 - remove unneeded scroll to top

packages/scandipwa/src/component/CartOverlay/CartOverlay.component.js, packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.component.js, packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.component.js, packages/scandipwa/src/component/Overlay/Overlay.component.js, packages/scandipwa/src/component/PopupSuspense/PopupSuspense.component.js, packages/scandipwa/src/component/SearchOverlay/SearchOverlay.component.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.style.scss
**Original issues:**
* https://github.com/scandipwa/scandipwa/issues/2896
* https://github.com/scandipwa/scandipwa/issues/2933
**Problem:**
* Chunks contain multiple instances of Overlay style, so when switching to compare page _(as example)_ new overlay style is loaded and then when going back to PLP ```.Overlay``` takes priority over ```.OverlayFilterContainer``` as it's newer.
* Moved Overlay style to new chunk _(```overlay```)_ so that it is only loaded once
* Moved other overlay styles to chunks: ```overlays``` and ```overlays-category``` so that they are loaded after ```overlay``` chunk
* Moved ```CategoryFilterOverlay``` to chunk ```overlays-categry```, so that it is loaded style first.
* Added placeholder to fix glitch where overlay style is loaded, but …
=> #2896 Fixed import order for overlays

packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.component.js
Issue: https://drive.google.com/file/d/1F3JfY4ZwUuQGcEvuVzgz0la8M7DFUoSB/view
Forgot password form opens in Sign in form on submit (instead of sign in attempt)
=> fix forgot password form open on sign in submit

packages/scandipwa/src/component/AddToCart/AddToCart.component.js, packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js
* https://github.com/scandipwa/scandipwa/issues/2069
Problem:
* Add to cart style is located in multiple chunks. On page change it is loaded again, thus overriding compare pages add to cart style.
In this PR:
* Moved Add to cart style to chunk 'cart' so that it is loaded only once.
* Moved Compare style to chunk 'cart' so that it is loaded after add to cart style.
=> #2069 Compare page wishlist btn layout style fix via chunk order

packages/scandipwa/src/component/ExpandableContent/ExpandableContent.component.js, packages/scandipwa/src/component/MyAccountTabList/MyAccountTabList.component.js, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js, packages/scandipwa/src/component/ProductDownloadableSamples/ProductDownloadableSamples.component.js
* https://github.com/scandipwa/scandipwa/issues/2977
**Problem:**
* Expandable content style is located in multiple chunks, thus on page switch expandable content style overrides previous style.
* Moved expandable content into single chunk 'expandable-content', thus only loading it once + fixing order for styles.
=> #2977 Double sample & link title in PDP

packages/scandipwa/src/component/MyAccountDownloadable/MyAccountDownloadable.component.js, packages/scandipwa/src/component/MyAccountDownloadable/MyAccountDownloadable.style.scss, packages/scandipwa/src/component/MyAccountMyOrders/MyAccountMyOrders.style.scss
* https://github.com/scandipwa/scandipwa/issues/3026
**Problem:**
* Style for downloadable was in order component, thus it was only loaded when opening my orders tab.
* Style was outdated.
* Moved style to separate file
* Fixed outdated values
=> #3026 Mobile my downloadables horizontal scroll

packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
* https://github.com/scandipwa/scandipwa/issues/3031
**Problem:**
* Long names aren't wrapped on mobile, thus creates page wide horizontal scroll.
=> #3031 Fix long name for wishlist item in mobile

packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
* https://github.com/scandipwa/scandipwa/issues/3036
**Problem:**
* DIV containing name & options isn't occupying whole given space.
* Added class to DIV containing name & options so that it can be targeted via sass
* Added style rule to occupy 100% of given space.
=> #3036 MyWishlist short name breaks by itself

packages/m2-theme/build-config/before.js
There is an issue when theme doesn't build in magento mode.
This happens because we override default build directory in the webpack configuration, but CRA doesn't get this change and after the build it tries to lookup files in the default directory.
Setting `BUILD_PATH` can override the default path for CRA.
For more info see scandipwa/create-scandipwa-app/issues/68
=> App Build Fix

packages/scandipwa/package.json
Fixes scandipwa/create-scandipwa-app#67
Added a new default proxy that is not connected to cloud flare.
=> Added New Default Proxy

packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js, packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js
* https://github.com/scandipwa/scandipwa/issues/3082
**Problem:**
* No check if element exists;
* Structure of FieldSelect component was changed ([commit](https://github.com/scandipwa/scandipwa/commit/170242e07e8e02b00e1d831514d1d1257e9dd9e4)) by moving select DOM inside div DOM, thus query  `#${selectId} + ul #o${id}` would no longer work as they are no longer together.
**In this PR**
* Added element check
* Added id for wrapper and fixed query selector.
=> #3082 Ooops on select when using keyboard

packages/m2-theme/build-config/before.js, packages/m2-theme/build-config/craco.js
Since `overrideCracoConfig` was async, craco path override function run between `overrideCracoConfig` was executed and result was returned.
Thus no paths were overrided and react scripts took `index.html` template instead of `index.php` template.
=> Fixed m2-theme plugin

packages/scandipwa/src/store/RecentlyViewedProducts/RecentlyViewedProducts.dispatcher.js
* https://github.com/scandipwa/scandipwa/issues/3098
**Problem:**
* No check if store exist in `localStoreage.recentProducts`
* Added check
=> #3098 Multistore RVP widget crash when one store has and other dont

packages/scandipwa/src/component/CartCoupon/CartCoupon.component.js, packages/scandipwa/src/component/Field/Field.config.js, packages/scandipwa/src/component/Field/Field.container.js
Original issue: https://github.com/scandipwa/scandipwa/issues/2863
In this PR:
* Added new option for field to hide both valid and invalid validation statues by passing to ```customValidationStatus``` value ```VALIDATION_STATUS.skip```
* Changed logic in coupon field to show valid field only when something is entered otherwise no color effect, via new validation status
=> #2863 Correct coupon field colors.

packages/scandipwa/src/component/Popup/Popup.component.js
If user or a google bot lands for the very first time on some page with parameters, like `/women.html?page=2` or `/women.html?customFilters=color:395124;size:395234` the "new version" popup will be triggered and parameters will be lost.
This commit fixes that, parameters will be retained
=> Will retain link parameters when popup is opened

packages/scandipwa/src/component/Router/Router.component.js, packages/scandipwa/src/component/Router/Router.config.js
Added component name to router config to make it possible to modify router config easily, when creating plugins (e.g. excluding route or change position). JSX tags with variables that lazily import components don't include info on component name.
```
export const BEFORE_ITEMS_TYPE = (originalMember) => originalMember.filter((route) => route.name !== NAVIGATION_TABS);
```
Why needed: Excluding a route from router completely is a better option than having to fully override component with `return null`. Plus even if you return null, route still exists.
=> add component name to router config

packages/scandipwa/src/component/Menu/Menu.component.js, packages/scandipwa/src/component/MenuItem/MenuItem.container.js
Fixes 2 issues:
1. Current menu stack state not saved to `location.history.state` => not restored when navigating back
2. Menu stack populated incorrectly with menu item ids: when clicking on menu item on lowest level, click on it was propagated to upper menu level, toggle state logic was mistakenly applied (+/- clicks) and id of this menu item was removed from state
Also renamed 2 namespaces as 1. they were incorrect 2. exactly same names were used in another component (I had trouble creating a plugin for this component) 
For QA: if you expand mobile menu (e.g. click Accessories -> Bags -> Handbags), then click Back arrow on Handbags category once, you will get back to menu and you will still see Accessories and Bags expanded.
=> fix storing menu state

packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.config.js, packages/scandipwa/src/component/ProductCompare/ProductCompare.component.js, packages/scandipwa/src/component/ProductCompare/ProductCompare.container.js, packages/scandipwa/src/util/Price/Price.config.js, packages/scandipwa/src/util/Price/Price.js
* https://github.com/scandipwa/scandipwa/issues/2850
Problem:
* Tier prices aren't included in ProductCompare, thus label is not showing for them
In this PR:
* Moved label rendering logic to `util\price`, to remove recurrence in `ProductCompare` and `ProductCard`
* Added price tiers to `ProductCompare` to output correct price.
* Added out of stock check to remove "always loading" price labels.
=> #2850 Compare page price fixes

packages/scandipwa/src/component/SharedTransition/SharedTransition.component.js
Issue: https://github.com/scandipwa/scandipwa/issues/3010
Was broken after theme-redesign multiple left/right replacements. The problem was that left element position was undefined, not correct element position from the left => element jumped after animation finished.
We do need `left` here and it works for RTL mode as well, as we have the following animation logic:
1. get left and top position + its width and height for element to be animated using `getBoundingClientRect()`
2. move from starting position to the calculated one gradually until element is at its correct position
Here `left` is totally replaceable with `right` and `top` is replaceable with `bottom`, as they play role of X and Y coordinates (if element is placed 30px from the left and 60px from the right for LTR, it will be …
=> #3010 - not smooth animation

packages/scandipwa/src/component/ExpandableContentShowMore/ExpandableContentShowMore.component.js
Issue: https://github.com/scandipwa/scandipwa/issues/3104
ExpandableContentShowMore has logic to calculate height of container and set height for the block in order to play animation. The issue is that when layered navigation is applied number of options may change => height of block needs to be recalculated and applied. Change for the number of children has already been handled before (I was fixing this some time ago). But what was not taken into account is that you may have same number of children, but some of children will change from 1 line to 2 lines => and it is the reason to update the height of the block as well.
=> #3104 - show less overlap fix

packages/scandipwa/src/component/CartItem/CartItem.container.js, packages/scandipwa/src/component/CartOverlay/CartOverlay.container.js, packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductActions/ProductActions.container.js, packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.container.js, packages/scandipwa/src/util/Product/Extract.js
* https://github.com/scandipwa/scandipwa/issues/3122
* https://github.com/scandipwa/scandipwa/issues/3123
**Problem:**
* Not all products store their stock status value inside product: stock_status, products with type group, config, bundle require to check their children products.
* For config products only swatch option are displayed on product card, thus when config product contains non-swatch value it is impossible to select active product variant.
* Created function that checks stock status based on their type.
* Added check for config product to redirect if contains non-swatch options.
=> #3122 Out of stock checker

packages/scandipwa/src/util/Product/Product.js
* https://github.com/scandipwa/scandipwa/issues/2757
**Required PR:**
* https://github.com/scandipwa/quote-graphql/pull/81
**Problem:**
* customizable options aren't passed to graphql
* Added customizable options for graphql to all products
=> #2757 Downloadable customizable option support

packages/scandipwa/src/component/CategorySort/CategorySort.container.js, packages/scandipwa/src/route/SearchPage/SearchPage.config.js, packages/scandipwa/src/route/SearchPage/SearchPage.container.js
* #2468 
**Requirements:**
* Replace best match with none in search page, while keeping label as 'best match'
* Changed label from '- None -' to 'Best match'
* Removed position filter from search page
=> #2468 Search page replace none with best match sort

packages/scandipwa/src/component/ImageZoomPopup/ImageZoomPopup.style.scss, packages/scandipwa/src/component/Popup/Popup.container.js
* https://github.com/scandipwa/scandipwa/issues/3159
Problem:
* property `contentMix` was not passed to `Popup.component`, thus style rules where not applied
In this PR:
* added property `contentMix` to `containerProps()` in `PopupContainer`
* Style adjustments
=> #3159 Image popup fix

packages/scandipwa/src/component/Image/Image.component.js, packages/scandipwa/src/component/Image/Image.container.js, packages/scandipwa/src/component/Image/Image.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/2547
- Added back `isPlain` props lost after "no props spreading refactoring"
- Also noticed that image statuses are passed as mods to `<div>` with image => replaced `image_status_0` and `image_status_1` with correct modificators.
=> #3142 - fix lost props

packages/chunk-optimizer/build-config/craco.js
* Chunks break with plugins: https://github.com/scandipwa/scandipwa/pull/3144
**Problem:**
* Due to the way in which we are adding plugins into project, webpack thinks that all of their styles require primary mounting _(meaning that on build they will be attached to <head> in template.php)_, because we are spiting chunks based on their category we are moving those mounting points to different chunks and due to that all those chunks/files are attached to header _(instead there should be only one file in header - main_style.css)_.
* Added check if file is for plugin (by name & path)
* Added check whether or not file should be moved to main chunk.
=> [chunk-opt] Fixed plugin style loading issue.

packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.container.js
Issue: https://github.com/scandipwa/scandipwa/issues/3176
Continue to enlarge my collection of bugs caused by "no props spreading fix" :)
Problem caused by defaultProps value for store address set to `{}` => `{}` evaluated to `true`  and caused wrong data to be populated to shipping and billing addresses.
=> #3176 - fix save shipping address error

packages/scandipwa/src/component/CartOverlay/CartOverlay.container.js, packages/scandipwa/src/query/ProductList.query.js, packages/scandipwa/src/route/CartPage/CartPage.container.js, packages/scandipwa/src/util/Cart/Cart.js, packages/scandipwa/src/util/Product/Extract.js
Required PR:
* https://github.com/scandipwa/catalog-graphql/pull/117
* https://github.com/scandipwa/scandipwa/issues/3177
* https://github.com/scandipwa/scandipwa/issues/3171
Problem
* Used deprecated function to check stock status
In this PR:
* Changed stock check to use new function
=> #3177 CartPage out of stock bundle fix 

packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.component.js, packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.container.js
Original Issue:
* https://github.com/scandipwa/scandipwa/issues/3267
BE fixes:
* https://github.com/scandipwa/catalog-graphql/pull/119
(Will work also without this, but this solves be issue for returning null)
In this PR:
* Added fallback for bundle label.
=> #3267 Fallback label for bundle options

packages/scandipwa/src/component/CmsBlock/CmsBlock.container.js, packages/scandipwa/src/route/Checkout/Checkout.component.js
* https://github.com/scandipwa/scandipwa/issues/3274
**Problem:**
* No check for `DETAILS_STEP`, so on order success outputs cms block for shipping step
* CmsBlock fetches content only on func `componentDidMount`, this function will be called only once after first render... so if identifier is change method will not be called, because component already is mounted.
* Added check for `DETAILS_STEP`.
* Added updating of CmsBlock content on identifier change.
=> #3274 Display correct cms in checkout

packages/scandipwa/src/route/MyAccount/MyAccount.container.js
Issue: https://github.com/scandipwa/scandipwa/issues/3233
Call of static method doesn't trigger component rerender when needed (i.e. when `isNewsletterActive` props updates).
=> #3237 - newsletter tab missing

packages/scandipwa/src/component/SwipeToDelete/SwipeToDelete.component.js, packages/scandipwa/src/component/SwipeToDelete/SwipeToDelete.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/3200
Fixed by removing `display: flex` and changing styles accordingly from a container => flexbox is too clever and always allocates space for text `Delete` first and only then to less important blocks and margins.
=> swipe to delete animation

packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.component.js, packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.container.js
* https://github.com/scandipwa/scandipwa/issues/3298
**Problem:**
* Due to checkbox changing state for parent element, form is re-rendered, thus invoking validation check on checkbox change.
* Validating each field separately.
=> #3298 Registration sepperate field validation

packages/scandipwa/src/store/Config/Config.reducer.js
* https://github.com/scandipwa/scandipwa/issues/3296
**Problem:**
* Default value for `newsletter_general_active` is set to false, and is updated to true only when graphql has fetched value, thus MyAccount when performing check if requires redirect will always redirect, becouse on first check `newsletter_general_active` will always be false.
* By removing default value in reducer it seems to use last retrieved value, which in the end is the best solution in this case. (works same as wishlist tab now)
=> #3296 Redirects from newsletter to dashboard on reload

packages/scandipwa/src/route/MyAccount/MyAccount.container.js
* https://github.com/scandipwa/scandipwa/issues/3306
**Problem:**
* User is redirected to homepage instead of login page
* When opening MyAccount page directly from icognito mode, there will be no graphql responses yet, thus `base_link_url` will be null. Due to that we have loop in method `componentDidUpdate` where prop for history is updated to the same URL (thus invoking componentDidUpdate again, and again). We are getting error: Max update count exceeded. 
* Checking for prop `base_link_url` to be loaded, and then redirecting.
=> #3306 Redirect fix for myaccount

packages/scandipwa/src/route/MyAccount/MyAccount.container.js, packages/scandipwa/src/util/Url/Url.js
* https://github.com/scandipwa/scandipwa/issues/3306
**Problem**
* Due to base URL not  existing on first open in icognito mode _(due to graphql still fetching it)_, redirectred URL in header will contain original URL + '/account/login', due to how `appendWithStoreCode` function works.
* `navigateToSelectedTab` will be always executed so it will always append `my-account/{ active-tab }` to end of URL.
**In this PR**
* Added new URL function that replaces path section based on regex rule
* If URL is not yet fetched use replace to redirect from my-account
* Redirect to different my-account tabs only if signed-in
=> #3306 Correct URL redirect on non-logged + icognito

packages/scandipwa/src/component/Header/Header.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/3202
Center welcome message in FF and Chrome (as it looked different):
FF:
Chrome:
=> #3202 - center welcome message firefox

packages/scandipwa/src/component/NewVersionPopup/NewVersionPopup.container.js, packages/scandipwa/src/component/Popup/Popup.component.js, packages/scandipwa/src/component/Popup/Popup.container.js
Issue: https://github.com/scandipwa/scandipwa/issues/3248
There is difference between closing popup via hitting BACK button in browser and closing popup via click on Cross button, click outside or Escape key.
In first case we subscribe to `popstate` event. Popstate event  is fired when the active history entry changes while the user navigates the session history ( = so it occurs naturally).
```
window.addEventListener('popstate', this.hidePopUp);
```
When we close popup in some other ways, we also need to go back through history one step.
=> #3248 - no go back after popup close

packages/scandipwa/src/component/ProductAttributes/ProductAttributes.component.js, packages/scandipwa/src/query/ProductList.query.js
We have problems with query complexity, especially on PDPs. query to get PDP required info has 1044 complexity which is definitely very high. Others request have max 400 complexity.
**Relaited PR:**
* https://github.com/scandipwa/persisted-query/pull/25
* https://github.com/scandipwa/catalog-graphql/pull/121
* Reduce product list query complexity from 1044 to 604 by removing unnecessary query calls.
=> #3103 - Remove unused query fields for productlist

packages/scandipwa/src/component/ResetAttributes/ResetAttributes.container.js
Issue 1 from https://github.com/scandipwa/scandipwa/issues/1864, i.e. Not all products displayed belong to the specific price step that is selected.
BE PR: https://github.com/scandipwa/catalog-graphql/pull/115
The problem was that labels range was used instead of values range for price filter. If search is in non base currency, values in base currency should still be used for search. In this case labels and values will be different.
=> #1864 - price filter wrong products

packages/scandipwa/src/component/GroupedProductList/GroupedProductList.component.js, packages/scandipwa/src/component/Product/Product.container.js
* https://github.com/scandipwa/scandipwa/issues/3392
**Problem:**
* Missing default qty for bundle
* Incorrect order from graphql
* Added default qty for bundle and sorted items before render
=> 3392 BUndle product default qty & order

packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
**Issue:**
* https://github.com/scandipwa/scandipwa/issues/2934
**Problem:** isCategoryAnchor condition is not enough to make decision whether to show filter or not
**Solution:** show filter button category is anchor or it is search page
=> #3364 - fix no message after compare list clear

packages/scandipwa/src/component/GroupedProductsItem/GroupedProductsItem.component.js
* https://github.com/scandipwa/scandipwa/issues/3409
**Problem:**
* Passing src when it not yet set.
* Keeping as placeholder while url is not set.
=> [3409] Image loading status for group

packages/scandipwa/src/component/GroupedProductsItem/GroupedProductsItem.style.scss
* https://github.com/scandipwa/scandipwa/issues/3402
**Problem:**
* Grid items are aligned to center
* Aligned items to start
=> [3402] Align bundle items to top

packages/scandipwa/src/component/CartItem/CartItem.container.js
**Issue:** https://github.com/scandipwa/scandipwa/issues/3372, issue 7 (a separate PR as not related to iOS 15)
**Problem:** One loader is from SwipetoDelete, another one is from CartPage
**Solution:** Don't set loading state for CartPage if delete on Swipe is active
=> #3372 - fix 2 loaders on swipe to delete

packages/scandipwa/src/component/Product/Product.component.js, packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.component.js
**Original issues:**
* https://github.com/scandipwa/scandipwa/issues/3394
* https://github.com/scandipwa/scandipwa/issues/3393
**Problem:**
* Due to production mode code is minified, thus class name no longer can be accessible.
* Added class names for ProductActions and ProductCard
* Added fallback name for Product
=> #3393 Missing class names for ProductAction & Card

packages/scandipwa/src/component/CheckoutPayment/CheckoutPayment.component.js, packages/scandipwa/src/component/CheckoutPayment/CheckoutPayment.style.scss, packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.container.js, packages/scandipwa/src/util/Address/index.js
* https://github.com/scandipwa/scandipwa/issues/3410
**Problem:**
* Incorrect address format passed when using saved address
* Incorrect attribute used for checkbox
* Added function that filters out saved address to be usable for checkout
* Fixed incorrect attribute.
=> [3410] Payment selection & saved address fix

packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.style.scss
**Issue:**
- https://github.com/scandipwa/scandipwa/issues/3430
**Problem:**
- the whole overlay is scrollable. Applying padding equal to `--safe-inset-area-bottom` doesn't have effect, as bottom of overlay is hidden below bottom of the screen.
**Solution:** 
- fix position of main overlay container on screen by forbidding scroll, apply padding equal to `--safe-inset-area-bottom`, make only inner div scrollable => as a result the very bottom area is never covered with content.
=> 3430 - chrome gap below bottom bar

packages/scandipwa/src/component/Product/Product.container.js
* https://github.com/scandipwa/scandipwa/issues/3392
**Problem:**
* `typeof quantity !== 'object'` was used inside function that should return default quantity... this is incorrect, as it should return qty based on type, ignoring other values, thus if product wasn't loaded the `setQuantity` will set  `quantity` as `{}` on first time, and then function will return `null`, thus not updating quantity.
=> [3392] Default grouped qty

packages/scandipwa/src/component/ProductCard/ProductCard.component.js
* https://github.com/scandipwa/scandipwa/issues/3421
**Problem:**
* Renders empty ProductPrice instead of null when configurable product is out of stock
=> [3421] Hide price on out of stock for conifurable

packages/scandipwa/src/route/NoMatch/NoMatch.container.js
**Issue:**
- Fixes https://github.com/scandipwa/scandipwa/issues/3411
**Problem:**
- `NoMatchReducer` still contains {noMatch: false} after user leaves 404 page, which may affect consequent page visits.
**Solution:**
-  reset `NoMatchReducer` state when leaving 404 page
=> #3411 - fix 404 after 404

packages/scandipwa/src/component/GroupedProductsItem/GroupedProductsItem.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3451
**Problem:**
* Height was set 100%
=> [3451] Grouped item image height is 100%

packages/scandipwa/src/component/Footer/Footer.component.js
* Fixes #3475 
**Problem:**
* Newsletter block visibility can be configured by `newsletter_general_active` option in the `ConfigReducer`. By default it is undefined until the config is fetched from the backend and placed to the localstorage. Then cached config is reused as fallback on each page reload. This is why Newsletter block doesn't render on first page visit.
* Footer component implemented own `shouldComponentUpdate` method, but didn't check properties that are comming from the Redux. This is why Newsletter block didn't appear once the config was fetched from the backend.
* Added checks to `shouldComponentUpdate` in order to rerender footer contents once config options are available.
=> See #3475 Fixed footer rerender on props change

packages/scandipwa/src/component/Router/Router.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3367 
**Problem:** 
No request to the server retrieving info on what products are in compare list on PDP load
**Solution:**
Added such a request
=> #3367 - pdp compare icon status

packages/scandipwa/src/component/Link/Link.container.js, packages/scandipwa/src/store/UrlRewrites/UrlRewrites.dispatcher.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3436
**Problem:**
* NoMatch, that is uesd for outputing 404, isn't restored when redirecting to different page, thus if request returns error and sets no match value to true, then by default next opened page will open 404.
* Added reset for no match when redirecting to different page
=> 3436 Product opens 404 if prev page had error

packages/scandipwa/src/component/ProductCard/ProductCard.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3498
**Problem:**
* Promise is rejected due to `cartId` equal to empty string. `CartId` equals empty string, as it is props default value.
* Remove default props value. `CartId` is resolved inside dispatcher logic, if not passed when calling add to cart method.
=> #3498 - add to cart PLP

packages/scandipwa/src/component/PureForm/FieldNumber/FieldNumber.container.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3521
**Problem:**
* `onChange` handler is attached to Counter input (field of type number). This `onChange` handler makes an API call to update wishlist item quantity in DB  (which is correct, it should happen when user clicks PLUS or MINUS). The problem is that exactly same handler is called on initial component load, when setting default value to input. 
**Solution:**
* Distinguish `onChange` and `onLoad` logic. Most of logic is the same (i.e. setting value to input and to state), but additional `onChange` should not occur on initial load. I added `handleInitialLoad` handler, so that it is possible to perform some additional logic on component load, in case it is needed.
=> #3521 - too many requests wishlist

packages/scandipwa/src/component/NewVersionPopup/NewVersionPopup.container.js
* Fixes #2833 
**Problem:**
* Popup new version is shows each time user first time visit website 
* Add check if controller exist (if exist means it is not first visit)
**How I tested:**
1.Go to website with incognito
2. See that no new version popup appear
3. Make changes in code so SW will fire life cycle and popup appear to suggest reload.
=> issue-2833 - Disable show new version popup on first website visit

packages/scandipwa/src/util/Address/index.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3660
**Problem:**
* `region_string` field data is lost after several data tranformations
* fix transformation logic
=> #3660 - region string data lost

packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.style.scss
* Fixes #3653 
**Problem:**
* font-weight of SampleTitle was set bold.
* Price written in brackets without spaces.
* Unset bold font-weight to SampleTitle.
* Removed brackets around Price and added the needed spaces.
=> [3653] Same styled option names of downloadable and other products

packages/scandipwa/src/util/Request/Request.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3627
**Problem:**
* HTTP 503 response error was totally ignored
* Request handler did not return reject to JSON parse error
* Request handler did not return reject to connection fail error
* Error notification was implemented but never called
* Return reject to 503 response error on request promise
* Ignore `console.error()` returning `false` on `parseResponse()`, returning `reject(err)` to promise.
=> [3627] Solve 503 error response being ignored by parseResponse().

packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
* Fixes #3662 
**Problem:**
* Shows error on token revoke, because request is send without token and it fails to check user authorization
* Send request before token is removed from localstorage
=> issue-3662 - Move revoke mutation before token delete from storage

packages/scandipwa/src/util/Product/Extract.js
* Fixes https://github.com/scandipwa/scandipwa/issues/2846
**Problem:**
* Incorrect field accessed for downloadable product calculations.
* Switched to correct field `maximum_price`
=> [2846] Price calculation with discount for downloadable

packages/scandipwa/src/component/Breadcrumb/Breadcrumb.component.js, packages/scandipwa/src/component/Breadcrumb/Breadcrumb.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3641
**Problem:**
* search query name redirects to home.
* make "pointer-event" to last child of breadcrumb unclickable
=> #3641 Home page opens if user click on name of search query in breadrums on search page

packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3668
**Problem:**
* z-index for checkbox & radio is 10, so if select options have z-index to 5, then checkbox will be selected instead of clicked option as they would be technically above.
* Fixed order, so that select options are above checkbox, when opened
=> [3668] User can select checkbox options if click on field between options in dropdown

packages/scandipwa/src/component/Header/Header.style.scss
* Fixes #3734 
**Problem:**
* svg was not centralized vertically inside the button
* added a vertical alignment
=> [3734] Arrow back centralized near title

packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3531
**Problem:**
* Due to display flex, when field contains error msg its container height changes, thus flex elements are not aligned correctly
* Moved error message to absolute position, same logic as in Message
=> [3531] Shifted error msg for confirm account page

packages/scandipwa/src/component/NewsletterSubscription/NewsletterSubscription.style.scss
- Fixes https://github.com/scandipwa/scandipwa/issues/3774
Problem:
- The margin from the top of the 'Subscribe' button is 32px in the footer section.
In this PR:
- I have changed the margin-top from 32px to 24px in the NewsletterSubscription.style.scss file.
=> [3774] Fix Subscription Button Margin

packages/scandipwa/src/component/Footer/Footer.style.scss, packages/scandipwa/src/component/Menu/Menu.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3769
Problem:
* Line-height differ from Line-height in mockup:
- Copyright in Footer
- links on pages (about, men and other)
In this PR:
* I have changed the line-height in Footer.style.scss to fix the style of links and copy-right section.
=> [3769] Fix-Footer-Copyright-Links-Line-Height

packages/scandipwa/src/component/NewsletterSubscription/NewsletterSubscription.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3773
Problem:
* Height of field for entering email in the footer in Newsletter is not the same as other input fields = 43.6px
In this PR:
* I have changed the height of the input field in the NewsletterSubscription.style.scss file to 44.6px.
=> [3373] Fix Height of field of Newsletter

packages/scandipwa/src/component/ProductCompareAttributeRow/ProductCompareAttributeRow.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3706
Problem:
* The values of attributes are cut in Compare Page, like Capital letters and numbers.
In this PR:
* I have changed the overflow value from hidden to visible in ProductCompareAttributeRow.style.scss file.
=> [3706] Fix Product Compare Attribute Style

packages/scandipwa/src/component/CartOverlay/CartOverlay.style.scss, packages/scandipwa/src/route/CartPage/CartPage.style.scss, packages/scandipwa/src/route/Checkout/Checkout.style.scss
Increased padding for order total to match padding around buttons
* Fixes https://github.com/scandipwa/scandipwa/issues/3791
* Fixes https://github.com/scandipwa/scandipwa/issues/3793
**Problem:**
* Order total is not in line with cart buttons at the bottom
* Distance from the bottom of title on cart, shipping, billing page is wrong
* Changed order total padding to match padding around cart buttons
* Changed margins and paddings from the bottom of title on cart, shipping and billing page
=> #3791 Increased padding for order total

packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss, packages/scandipwa/src/component/Menu/Menu.style.scss, packages/scandipwa/src/component/StoreSwitcher/StoreSwitcher.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3727
**Problem:**
* Wrong line-height for some element in header on mobile:
- For store and currency dropdowns: Line-Height 23px
- For categories items in menu: Line-Height 16px
* I have added line-height: 20px; in FieldSelect.style.scss file to storeSwitcher and CurrencySwitcherList IDs.
* I have added line-height: 20px; in Menu.style.scss for Menu-ItemCaption_type_main class.
=> [3727] Fix line height for element on menu

packages/scandipwa/src/component/CartCoupon/CartCoupon.style.scss, packages/scandipwa/src/component/CartOverlay/CartOverlay.component.js, packages/scandipwa/src/component/CartOverlay/CartOverlay.style.scss, packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js, packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.style.scss, packages/scandipwa/src/component/CheckoutOrderSummaryPriceLine/CheckoutOrderSummaryPriceLine.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3815
**Problem:**
* Coupon name wasn't showing on discount line
* Added coupon name to discount line on cart overlay and cart page
=> [3815] Added coupon code name to cart overlay and cart page

packages/scandipwa/src/component/Footer/Footer.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3770
**Problem:**
* Social media icons were not rounded
* Added border radius property to social media icons
=>  [3770] Made footer social media icon edges rounded

packages/scandipwa/src/component/Header/Header.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3712
**Problem:**
* When the focus is on search products field bottom border of the header disappears
* Changed border-block-end from none to using the same border as when not focused on search field in Header_name_search
=> [3712] Header bottom border style

packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.style.scss, packages/scandipwa/src/component/ProductDownloadableSamples/ProductDownloadableSamples.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3680
Problem:
* Mobile: Text is shifted up in checkboxes on PDP.
In this PR:
* I have added margin: auto; to ProductDownloadableLink-SampleTitle class in ProductDownloadableLinks.style.scss file.
=> [3680] Fix Text Shifted Up On Mobile

.gitignore
* Fixes https://github.com/scandipwa/scandipwa/issues/3765
**Problem:**
* Label in file input was aligning left if the label is too long
* Forced label to stay centered and added word breaking so that the label doesn't stretch container if the label is too long.
=> [3765] Force centering file input label (recreated)

packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
* Fixes #3824 
**Problem:**
* Bullet points were overlapped by text in product description
* Changed position property of bullet points in item description
Recreated PR from #3840 in order to run amplify instance
=> [3824] Changed position of bullet points in product description from absolute to static

packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.style.scss
Fixes https://github.com/scandipwa/scandipwa/issues/3800
**Problem:**
Fields for date/time/date&time on PDP has wrong high, it is about 51.7 and 51.8px now
set fixed height= 44.6
=> [3800] Fixing the fields for date/time/date&time on PDP

packages/scandipwa/src/component/Header/Header.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3875
**Problem:**
* Line under search field in mobile menu should not be there
* Changed headers bottom border in mobile menu to none
=> [3875] Border under search in mobile menu

packages/scandipwa/src/util/Request/Request.js
**Problem:**
* Sometimes graphql request can be not cached due to setting empty string for max-age
* Check if integer and fallback to default value if it not integer.
=> Add fallback for cacheTTL in case if it is not intereger

packages/scandipwa/src/component/ProductActions/ProductActions.style.scss, packages/scandipwa/src/component/ProductCard/ProductCard.style.scss, packages/scandipwa/src/component/ProductLinks/ProductLinks.style.scss, packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss, packages/scandipwa/src/component/ProductReviewRating/ProductReviewRating.style.scss, packages/scandipwa/src/component/ProductReviews/ProductReviews.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3737
**Problem:**
* Issue 1 - Line-height from H1 should be inherited for product name
* Issue 2 - Product name of related products don't use Line-height: var(--paragraph-line-height)
* Issue 3 - Wrong line-height for brand = 20px
* Issue 4 - Text '{rate} / {numberOfReviews} reviews' doesn't use h2 styles
* Issue 5 - Title for Related and upsells products doesn't inherit line-height and font-weight for h2
* Issue 6 - Price doesn't use style for h2 Line-height 1
* Issue 7 - Wrong color for product price before discount
In this PR:
* I have removed the Line-height styling of product name from ProductActions.style.scss to allow it to use the styling of H1
* I have changed the the value of the line-height of product name …
=> [3737] Fix Font Settings on PDP

packages/scandipwa/src/util/Auth/Token.js, packages/scandipwa/src/util/Request/Request.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3835
**Problem:**
* Missing logic
* Added refreshAuthToken call to every post and get request
* Remove refreshAuthToken call from isSignedIn check => as token is updated on API call, this is a dupe update, I suppose
* add debounce, as method is called too often otherwise
=> #scandipwa-3835 - refresh token on every request

packages/scandipwa/src/component/MyAccountForgotPassword/MyAccountForgotPassword.component.js, packages/scandipwa/src/route/ForgotPassword/ForgotPassword.component.js, packages/scandipwa/src/route/ForgotPassword/ForgotPassword.style.scss, packages/scandipwa/src/route/LoginAccount/LoginAccount.component.js, packages/scandipwa/src/route/LoginAccount/LoginAccount.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3714
**Problem:**
* Create an account button on login page has the wrong width
* Create an account button on forgot password page has the wrong width
* Sign in button on forgot password page has the wrong width
* Added classes to all the buttons to make them easily identifiable
* Added width: 100% to all of the new classes
=> [3714] Sign In and Create An Account button width

.gitignore, packages/scandipwa/src/component/NewsletterSubscription/NewsletterSubscription.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3822
**Problem:**
* Newsletter subscription error won't go away when user changes pages
* Tied NewsletterSubscriptionContainer to react router so it refreshes on every page change
=> [3822] Tied NewsletterSubscriptionContainer to router (recreated)

packages/scandipwa/src/query/Config.query.js, packages/scandipwa/src/route/Checkout/Checkout.container.js
**Related PR(s)**
* https://github.com/scandipwa/store-graphql/pull/21
* Fixes #2333 
**Problem:**
* If checkout contains downloadable + simple in cart with enabled setting in admin panel, then nothing happens.
* Add support for setting.
=> issue-2333 - Add support for check if downloadable in checkout

build-packages/scandipwa-cli/actions/override/lib/extender.js, build-packages/scandipwa-cli/actions/override/lib/options/withStyles.js, build-packages/scandipwa-development-toolkit-core/src/extend/config.ts, build-packages/scandipwa-development-toolkit-core/src/extend/index.ts, build-packages/scandipwa-development-toolkit-core/src/extend/scss-generation.ts, build-packages/scandipwa-development-toolkit-core/src/templates/stylesheet.scss, build-packages/scandipwa-development-toolkit-vscode/package.json, build-packages/scandipwa-development-toolkit-vscode/src/commands/go-to-child-theme/index.ts, build-packages/scandipwa-development-toolkit-vscode/src/commands/go-to-child-theme/suggest-extend.ts, build-packages/scandipwa-development-toolkit-vscode/src/commands/warn-in-source/index.ts, build-packages/scandipwa-development-toolkit-vscode/src/extension.ts
No issue is linked. This is an improvement suggestion diverged from the FE team.
**Problem:**
- The VSCode extension had no easy way of overriding a file. Now, when browsing source files, we can press a button to override it.
- The source code in node_modules was easy to modify, now it shows warnings when done
- Added option to pass style postfix, so it is configurable
All above mention features are implemented
=> CLI & VSCode tool improvements

packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.component.js, packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3888
**Problem:**
* Sign In and Confirm Account forms' required fields do not have a star for label
* Added addRequiredTag for Sign In form's password and email fields, and for password in Account Confirm form
=> [3888] Stars for required fields

packages/scandipwa/src/component/Field/Field.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3874
**Problem:**
* "Field is required" error message is centered in mobile after submitting empty subscribe form
* Added text-align: left to error messages
=> [3874] "Field is required!" error positioning on mobile

packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.container.js
* Fixes #3882 
**Problem:**
* MyAccountOverlay doesn't check if it is overlay before clicking on forgot passoword so it tries to redirect to other page and closes overlay
* Set check if it is overlay
=> #3882 - Set check before history push if it is overlay

packages/scandipwa/src/component/Popup/Popup.style.scss, packages/scandipwa/src/component/VideoPopup/VideoPopup.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3853
**Problem:**
* Video does not fit the popup, creating scrollbars.
* Added max height variable for popup, set it to none for video player.
=> [3853] Removed max width and max height for video player popup.

packages/scandipwa/src/route/SearchPage/SearchPage.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3065
**Problem:**
* Sort page was not receiving PLP view type props from redux
* Connected PLP view types in search page to redux
=> [3065] Connected PLP view types in search page to redux

packages/scandipwa/src/route/CartPage/CartPage.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3646
**Problem:**
* Icons of Compare and wish list are absent in Cross-sell products on Cart page
* changed the display of ProductCard-ProductActions in CartPage.style.scss from none to flex
=> Fixed whishlist and compare icones absence on cart page

packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.style.scss, packages/scandipwa/src/route/LoginAccount/LoginAccount.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3912
**Problem:**
* Different size of buttons on the pages(sign in, create an account and forgot password)
* On pages larger than the mobile version, the button sizes are the same
=> #3912 - Equalize buttons width

packages/scandipwa/src/component/MyAccountCustomerForm/MyAccountCustomerForm.component.js, packages/scandipwa/src/component/MyAccountCustomerForm/MyAccountCustomerForm.container.js, packages/scandipwa/src/component/MyAccountCustomerForm/MyAccountCustomerForm.form.js, packages/scandipwa/src/component/MyAccountCustomerTable/MyAccountCustomerTable.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3890
**Problem:**
* VAT number is not displayed in the 'Account Information' section
* VAT number is displayed in the Account Information section when viewing and editing
=> #3890 - Display VAT number in account section

packages/scandipwa/src/component/ProductTabs/ProductTabs.component.js, packages/scandipwa/src/route/ProductPage/ProductPage.component.js
* Fixes [[link for issue]](https://github.com/scandipwa/scandipwa/issues/3901)
**Problem:**
* We store tab index in state to know what tab is active. Default number of tabs is 3, but one of the tabs doesn't render always (there is `shouldTabRender` check which checks if data received from the server includes data for the tab). Sometimes (when user clicks on Reviews tab when still loading) active tab index will be 2 and it will be saved to state, but after `shouldTabRender` check number of tabs to render will be 2 => error appears when we try to access 3rd element (= element with index 2) of a 2 member array.
* the solution here is to get rid of indexes and replace them with tab names, as using indexes proves to be insecure in this case
=> #scandipwa-3901 - fix error write review render

packages/scandipwa/src/route/Checkout/Checkout.container.js
* Fixes #2333 
**Problem:**
* Cart is not open if user click back on login page and page was open after click on secure checkout
* Replace history instead of push, so that user can redirect back to prev page instead of checkout which will redirect him again to login
=> issue-2333 - Replace history instead of push

packages/scandipwa/src/util/Validator/Config.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3643
**Problem:**
* The email with numbers in the high-level domain validation is not valid
* Add numbers to high-level domain validation
=> #3643 - Add numbers to high-level domain validation

packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.form.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3828
**Problem:**
* Browser doesn't offer to autofill a form in checkout
* Added autocomplete: "email" to CheckoutGuestForm component
=> [3828] Autocomplete in checkout guest form

packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3679
**Problem:**
* Checkboxes in filters on mobile shown like a rectangle but not square
* Fix shape of checkboxes in the filter on mobile
=> #3679 - Correct the shape of checkboxes in the filter on mobile

packages/scandipwa/src/component/FieldGroup/FieldGroup.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3568
**Problem:**
* Green line shown from the left side when user selected options with checkboxes or radio buttons on PDP with RTL
* Fix positioning of the green line on PDP with RTL
=> #3568 - Correct positioning of the green line on PDP with RTL

packages/scandipwa/src/component/MyAccountAddressPopup/MyAccountAddressPopup.component.js, packages/scandipwa/src/component/MyAccountAddressPopup/MyAccountAddressPopup.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3508
**Problem:**
* Loader animation is shown only at the beginning popup
* Loader animation is displayed in the whole popup address window
=> #3508 - Change loader position on address popup

packages/scandipwa/src/component/CartOverlay/CartOverlay.component.js
* Fixes #3996
**Problem:**
* Shows oops page when rendering coupon code in cart overlay
* Set check for coupon code rendering
=> issue-3996 - Set check before rendering coupone code

packages/scandipwa/src/component/MyAccountDownloadable/MyAccountDownloadable.container.js, packages/scandipwa/src/component/MyAccountDownloadableTableRow/MyAccountDownloadableTableRow.component.js, packages/scandipwa/src/component/MyAccountDownloadableTableRow/MyAccountDownloadableTableRow.container.js, packages/scandipwa/src/query/Order.query.js, packages/scandipwa/src/type/Order.type.js
* https://github.com/scandipwa/customer-downloadable-graphql/pull/7
* Fixes #4008
**Problem:**
* When clicking or order row in downloadable orders, it redirect to not existing orders.
* Get and set correct order id for redirect
=> issue-4008 - Set correct order id for downloadable orders on redirect

packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3983
**Problem:**
* Price is displayed for out of stock products in Wishlist
* Disable price for out of stock product in Wishlist
=> #3983 - Disable price for out of stock product in Wishlist

packages/scandipwa/src/component/Field/Field.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3980
**Problem:**
* Error message is displayed from the left side for RTL
* Error message is displayed from the right side for RTL
=> #3980 - Error message is displayed from the right side for RTL

packages/scandipwa/src/component/Header/Header.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3976
**Problem:**
* Search is not centrally aligned before authorization
* Set center align for search before authorization
=> #3976 - Set center align for search before authorization

packages/scandipwa/src/route/ForgotPassword/ForgotPassword.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4019
**Problem:**
* opening forgot password for an authorized user
* Redirect to my account when opening forgot password like authorized user
=> #4019 - Redirect to my account when opening forgot password

packages/scandipwa/src/query/ProductList.query.js, packages/scandipwa/src/query/Wishlist.query.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3991
**Problem:**
* request fetching wishlist data is executed on PLP with `isPlp` parameter set to true, which means less fields are requested from the server for product variants. Among these fields is product's small image.
* Don't restrict fields list for variants if requesting data for wishlist.
=> 3991 - configurable product in wishlist no image fix

packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.style.scss, packages/scandipwa/src/component/Footer/Footer.style.scss, packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.style.scss, packages/scandipwa/src/component/NavigationTabs/NavigationTabs.container.js, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss, packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js, packages/scandipwa/src/route/Checkout/Checkout.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3725
**Problem:**
* We want navigation tabs to be hide-able on all pages.
* Removed logic telling whether to hide navigation tabs or not on a particular page.
* Improved componentDidUpdate logic
* Added logic for moving fixed positioned bottom page blocks down, when navigation tabs hide.
This is reacreated PR from @tappiola https://github.com/scandipwa/scandipwa/pull/4033
=> scandipwa-3725 - hide navigation tabs on all pages

packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3922
**Problem:**
* Wrong position of prices in product card on PLP for bundle products with discount
* Right position of price for bundle products with discount
=> #3922 - Fix position of price for bundle products with discount

packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
* Fixes [#3931 SKU for bundle products has left alignment on PDP on mobile ](https://github.com/scandipwa/scandipwa/issues/3931)
**Problem:**
* SKU for bundle products has left alignment on PDP on mobile, its need to be right-aligned
* adding text-align:end to ProductActions-Sku class
=> SKU bundle to right alligment on mobile

packages/scandipwa/src/component/Header/Header.style.scss
* Fixes [#4047 Account icon is shifted left on checkout ](https://github.com/scandipwa/scandipwa/issues/4047)
**Problem:**
* Account icon is shifted left on checkout
* change MyaccountContainer margin-inline-start from 44px to auto
=> #4047 Account icon is shifted left on checkout 

packages/scandipwa/src/component/CartItem/CartItem.style.scss
* Fixes #3940
**Problem:**
* Line height set to 28px if the price of the product is in mini cart
* Line height set to 20px
=> #3940 Line height if price of product is in mini cart adjusted

packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js, packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3803
**Problem:**
* Shipping price isn`t displayed Including and Excluding Tax at the same time
* Shipping price is display tax according to the parameters selected in the admin panel
=> #3803 - Add including and excluding tax for shipping method

packages/scandipwa/src/component/CartOverlay/CartOverlay.component.js, packages/scandipwa/src/route/CartPage/CartPage.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3294
**Problem:**
* Loader icon is displayed for all product in cart
* Loader icon is displayed separately for each product
=> #3294 - Loader icon is displayed separately for each product

packages/scandipwa/src/component/CheckoutPayment/CheckoutPayment.component.js, packages/scandipwa/src/component/CheckoutPayment/CheckoutPayment.style.scss, packages/scandipwa/src/component/Field/Field.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3956
**Problem:**
* Hover effect is absent on billing options
* changed .Field_type_checkbox pointer-events from none to auto
* wraped billing options title in label pointed to billing options input checkbox
=> #3956 Hover effect is absent on billing options

packages/scandipwa/src/component/Menu/Menu.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3928
**Problem:**
* Wrong space between last subcategory and category in the mobile menu it should be 22px
* adding margin-bottom: 22px to _isVisible mobile state
=> #3928 Wrong space between last subcategory and category in mobile menu

packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.component.js, packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3190
**Problem:**
* The onSignOn callback that was supposed to be called after successful login on the Checkout page is 'undefined' thus a misleading error message appears.
* Added an empty 'onMyAccountSignIn' handler to the 'CheckoutGuestForm' container.
=> #3190 Add missing callback after successful login.

packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3699
**Problem:**
* Header 'Confirm Your Account' has fixed font size
* Header 'Confirm Your Account' font size inherited from H1
=> #3699 - Fix style for Confirm Your Account header

packages/scandipwa/src/component/MyAccountCustomerForm/MyAccountCustomerForm.component.js, packages/scandipwa/src/component/MyAccountInformation/MyAccountInformation.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3930
**Problem:**
* Space is absent in 'Account Information' after selected checkboxes
* Add space in 'Account Information' after selected checkboxes on mobile
=> #3930 - Add space after account information on mobile

packages/stylelint-config/build-config/stylelint.js
* Fixes #4084
**Problem:**
* If `overrideCracoConfig` is async, it breaks the build process for `m2-theme` plugin. In this case HTML template is build instead of PHTML.
* Fixed stylelint plugin and build process.
=> See #4084 Fixed issue when wrong template file was applied.

packages/scandipwa/src/route/LoginAccount/LoginAccount.container.js
* Fixes [#3281 Mobile: Make pages start from the top when you switch to them](https://github.com/scandipwa/scandipwa/issues/3281)
**Problem:**
When you are on mobile, it might be that you change to a different page and it will be scrolled down if you had scrolled down before. Please, make pages start from the top when you switch to them. This include:
1. Sign in
2. Create account
3. Forgot password
4. Compare products
* adding scroll to top in LoginAccount container when componentDidMount() function
=> adding scroll to top

packages/scandipwa/src/route/CmsPage/CmsPage.style.scss
* Fixes [#3312 Text overlaps to bullets on CMS page](https://github.com/scandipwa/scandipwa/issues/3312)
**Problem:**
* Text overlaps to bullets on CMS page
* adding margin-inline-start for ul / ol
* adding inset-inline-startfor li:before
=> #3312 Text overlaps to bullets on CMS page

packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js, packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4010
**Problem:**
* Star for customizable product option is in the next line of its fields
* Now required start is on the same line as required field
=> #4010 Required star on the same line as required field

packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
* Fixes #3705 
**Problem:**
* When manually using log out compare uid still present.
* Remove compare uid on log out
=> issue-3705 - Remove compare uid on log out

packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.style.scss, packages/scandipwa/src/component/CmsBlock/CmsBlock.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3551
**Problem:**
Space is absent between promotion block and summary block on shipping and billing steps
added a margin to CmsBlock-Wrapper by 15px
=> Fixed spaces absence between blocks on ship and billing steps

packages/scandipwa/src/component/Html/Html.component.js
**Problem:**
All scripts have the same hash, only one script per page can be parsed.
Adjusting code to use the content of the script tag that is a `string` when generating a hash for the script
=> Fix for html script hash generation

packages/scandipwa/src/component/Html/Html.component.js, packages/scandipwa/src/component/RenderWhenVisible/RenderWhenVisible.component.js
Problem:
All scripts have the same hash, only one script per page can be parsed.
In this PR:
Adjusting code to use the content of the script tag that is a string when generating a hash for the script
Fix implemented for `script` tags previously in https://github.com/scandipwa/scandipwa/pull/4100 but now also for styles.
Use case where this is relevant - several similar widgets or cms blocks on a page
=> Fix for html style hash

packages/scandipwa/src/component/MyAccountCustomerForm/MyAccountCustomerForm.container.js
* Fixes [#3954 Field auto fulled if user delete last symbol of previous password in Edit email in Account information](https://github.com/scandipwa/scandipwa/issues/3954)
**Problem:**
* Endless delete of email address possible in Edit email in Account information
Field auto fulled if user delete last symbol of previous password
* change checker to only return currentCustomerEmail when email is null
note : branch got swapped but code is fine
=> #3954 Field auto fulled if user delete last symbol of previous password in Edit email in Account information

packages/scandipwa/src/route/CartPage/CartPage.container.js, packages/scandipwa/src/util/Cart/Cart.js
* Fixes [#2608 Cross-sells products getting duplicated if user added config products to cart with different attributes options](https://github.com/scandipwa/scandipwa/issues/2608)
**Problem:**
* Cross-sells products getting duplicated in the cart if user added config products with different options to cart
* add filtering for duplicate product (configurable product) items that will be used to search Cross-sell Product
=> #2608 Cross-sells products getting duplicated if user added config products to cart with different attributes options 

packages/scandipwa/src/component/Footer/Footer.component.js, packages/scandipwa/src/component/Footer/Footer.container.js
* Fixes scandipwa/scandipwa/issues/3782
**Problem:**
* There was nothing happening when the user was clicking footer category item if the page was already loaded
* Modified Footer component and container files to add page scroll to top logic
=> [3782] Extended Footer logic to scroll page up on category item click

packages/scandipwa/src/component/Header/Header.component.js
* Fixes scandipwa/scandipwa/issues/3105
**Problem:**
* '+' symbol is present in the title instead of space.
* Header.component.js
* line 409 modified the returned title and added a conditional statement in case title was undefined
=> [3105] plus symbol is displayed in title fix

packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
* scandipwa/scandipwa/issues/4069
**Problem:**
* cross sign was not aligned with the product name or starts whichever comes first.
* WishListItem.style.scss
* line 169 added a margin
=> [4069] product name and cross sign alignment fix

build-packages/csa-generator-theme/index.js, build-packages/csa-generator-theme/template/package.json, packages/scandipwa/package.json
**Problem:**
* when installing with npm error appears: Class extends value undefined is not a constructor or null. It is related to how npm install packages and since new package style-lint requires postcss to be version 8, other require it to be 7. Adding dependency to top-level requires version 8.
=> Set postcss version

packages/scandipwa/src/route/CreateAccount/CreateAccount.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3280
**Problem:**
* The 'Sign Up' button on 'Create Account' form is half hidden, even if you scroll down as much as possible.
* Add padding bottom in Create Account route for IOS devices
=> [3280] Add padding bottom to IOS devices

packages/scandipwa/src/store/Cart/Cart.dispatcher.js
* Fixes scandipwa/scandipwa/issues/3766
**Problem:**
* PDP page shows Incorrect message when adding product to cart in offline mode
* Added condition in cart dispatcher which will detect if the page is offline and send the correct message
=> #3766 added correct notification when adding product to cart in offline mode

packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4164
**Problem:**
* Bottom border on MyOrder subfield
* Remove mobile border on MyAccountOrderItemsTableRow-RowWrapper
=> [4164] Remove border on MyOrder subfield

packages/scandipwa/src/component/MyAccountDownloadable/MyAccountDownloadable.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3067
**Problem:**
* The navigation bar is cropped on My downloadable and My wishlist pages
* Width parameters adjusted on MyAccountDownloadable to respect screen size
=> [3067] MyDownloadable width parameters adjusted on mobile

packages/scandipwa/src/route/MyAccount/MyAccount.container.js
If not logged user opens link /default/customer/account on mobile it doesn't redirect to login page fix
* Fixes scandipwa/scandipwa/issues/4161
**Problem:**
* If not logged user opens link /default/customer/account on mobile it doesn't redirect to login page and it causes incorrect header load.
* Only changed MyAccount.container.js file under /route folder, Removed part which was disabling redirect on mobile.
=> [4161] If not logged user opens link /default/customer/account on mobile it doesn't redirect to login page fix

packages/scandipwa/src/component/Html/Html.component.js
**Problem:**
Scripts with external source all have empty script content and have the same hash
Added changes to calculate hash from script src and content to cover also cases with scripts with external sources
=> Fix for script tags with external source

packages/scandipwa/src/component/CartItem/CartItem.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3270
**Problem:**
* Options for product are cropped in cart/mini-cart 
* Add line-height to cart item option
=> [3270] Add line-height to cart item option

packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
* Fixes scandipwa/scandipwa/issues/4202
**Problem:**
* Name of the product is cut in Wishlist on IOS
* Change line-height to normal on the corresponding tag
=> [4202] Fix wishlish item names cut on IOS

packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.style.scss
* Fixes scandipwa/scandipwa/issues/4063
**Problem:**
* Mobile: Horizontal scroll appears on checkout if the delivery method has a long title and/or method name
* deleted "white-space: pre;" on corresponding tag which was causing unusual behavior
=> [4063] Fix Mobile horizontal scroll on long delivery method name

packages/scandipwa/src/component/Field/Field.style.scss, packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3058
**Problem:**
* Text area is highlighted by green if text entered
* Text field is grey if text deleted from field
after click on free space or other object on page
* added empty placeholder value
* added style when isValid and placeholder is shown
=> [3058] added empty placeholder value, added style when isValid and placeholder is shown

packages/scandipwa/src/component/FieldGroup/FieldGroup.style.scss, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.style.scss
* Fixes scandipwa/scandipwa/issues/3181
**Problem:**
* Hover effect and checkmark do not appear when hovering on the label of the option of downloadable product.
* label is not part of the checkbox and acts as an independent element.
* Passed independent label in checkbox attribute label, so now it is a part of checkbox and behaves normally.
=> [3181] Make downloadable product labels clickable/hoverable

packages/scandipwa/src/style/base/_reset.scss
* Fixes scandipwa/scandipwa/issues/4242
**Problem:**
* If a paragraph contains a long word it goes out from the screen, the word is not breaking and starting on another line.
* Set the word-break property to paragraph styles.
=> [4242] Add word break to paragraphs

packages/scandipwa/src/component/ProductGallery/ProductGallery.component.js, packages/scandipwa/src/component/ProductGallery/ProductGallery.style.scss, packages/scandipwa/src/component/Slider/Slider.component.js, packages/scandipwa/src/component/Slider/Slider.style.scss
* Fixes scandipwa/scandipwa/issues/3760
**Problem:**
* Dots overlap image and PDP does not look good if the product has a lot of images
* Passed showcounter property instead of showcrumbs to Slider on PhotoGallery.
* Defined counter render method at Slider component and styled.
=> [3760] Add counter to the slider on mobile PDP

packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js, packages/scandipwa/src/component/TierPrices/TierPrices.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3456
**Problem:**
* Advertising message shows Price value per item.
* Product Card rendered "As Low As" tag price
* Modified string for advertising message
* Removed As Low As tag
=> [3456] modified advertising string, removed TierPrice rendering

packages/scandipwa/src/component/CartItem/CartItem.component.js, packages/scandipwa/src/component/CartItem/CartItem.style.scss
* Fixes scandipwa/scandipwa/issues/3572
**Problem:**
* Name of option with radio button selector is written in LTR order in cart / mini cart.
* Make option parent element flex so now LTR/RTL modes have an effect.
=> [3572] Fix ltr order of options in cart in rtl mode

packages/scandipwa/src/component/Product/Product.component.js
* Fixes scandipwa/scandipwa/issues/3588
**Problem:**
* Sample for downloadable product opens in the same window if setting Open Links in New Window is set to yes. 
* The thing is that ProductDownloadableSamples component is called instead of the container and that cause use of component without business logic.
* Import ProductDownloadableSamples from its index in the Product component.
=> [3588] Fix ProductDownloadableSamples not using business logic

packages/scandipwa/src/component/Breadcrumb/Breadcrumb.component.js, packages/scandipwa/src/component/SearchField/SearchField.component.js, packages/scandipwa/src/component/SearchOverlay/SearchOverlay.container.js, packages/scandipwa/src/route/SearchPage/SearchPage.component.js, packages/scandipwa/src/route/SearchPage/SearchPage.container.js, packages/scandipwa/src/util/Common/index.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3972 (issue + failed QA comments)
**Problem:**
* `&` in URL is normally used for separating pairs of query params. It should be encoded if used as part of query param.
* Ooops page appears when searching '%' symbol Error message 'URIError: URI malformed' appears in the console
* Error messages 'Error fetching Product List Information!' and 'Error fetching Product List!' when searching '+' symbol
* Removed replacement of ' ' to '+', used URL encoding instead (which handles `&` in search param among other cases). 
* make + symbol to empty space and prevent redirect to search page 
* problem with encode % symbol need to change it manually
This is a reacreated PR from @tappiola …
=> #3972 Search functionality throwing error if search word contains & (Fix failed QA) 

packages/scandipwa/public/index.html
**Problem:**
When admin in some CMS page adjusts some paddings or margins, Magento will generate special classes to apply those styles to page elements. F.E. A padding on CMS column (https://i.imgur.com/SygvKDn.png) Class like this will be generated https://i.imgur.com/f9sqlJq.png
`id=html-body` is needed on `<body>` tag so these automatic styles work 
Will add `id=html-body` on `<body>` tag so these page builder styles work
=> Fix for page builder style support

packages/scandipwa/src/route/Checkout/Checkout.component.js, packages/scandipwa/src/route/Checkout/Checkout.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3551
**Problem:**
* Missing space between order summary and promo block
* Added new wrapper (Checkout-Promo) and added top-padding
=> [3551] Added div wrapper Checkout-Promo, applied 24px padding on desktop

packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js, packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.style.scss
* Fixes scandipwa/scandipwa/issues/4078#event-6025353507
**Problem:**
* Duplicate loader block on order summary mobile.
* loader is not visible on long carts.
* removed the duplicated loader from checkout order summary component
* Added a separate height style to the summary block loader.
=> [4078] Loader missing on checkout (QA comment fix)

packages/scandipwa/src/component/ProductBundleOption/ProductBundleOption.component.js, packages/scandipwa/src/component/ProductBundleOption/ProductBundleOption.container.js, packages/scandipwa/src/util/Product/Transform.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4263
**Problem:**
* Product option isn't selected by default for bundle product in dropdown on PDP
* Return isDefault prop in Util/Product/Transform bundleOptionsToSelectTransform()
* setDefaultOption on mount in ProductBundleOption Container
* set value equal to activeOption in ProductBundleOption component in render renderSelectValue()
=> [4263] Set DefaultOption in ProductBundleOption

packages/scandipwa/src/component/Header/Header.component.js, packages/scandipwa/src/component/Header/Header.style.scss, packages/scandipwa/src/component/Logo/Logo.style.scss, packages/scandipwa/src/component/SearchField/SearchField.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3976
**Problem:**
* Centering of the search depends on the number of icons and the size of the logo, when changing, it is necessary to align with margin/padding
* A grid is used to build a desktop header
=> #3976 - Use grid for desktop header

packages/scandipwa/src/component/MyAccountOrderItemsTable/MyAccountOrderItemsTable.component.js, packages/scandipwa/src/component/MyAccountOrderItemsTable/MyAccountOrderItemsTable.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4092
**Problem:**
* Wrong comments order for Refund tab
* Add sorting for comments using date
=> #4092 - Add date sorting for comments

packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.component.js
* Fixes #4282 
**Problem:**
* Count for options is moved to the next line without the last word in Layered Navigation
* The above happened only when there was is an additional white space at the end of the string.
* Attribute label now gets trimmed before rendering
=> [4282] attribute label gets trimmed before rendering

packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.style.scss
* Fixes scandipwa/scandipwa/issues/4295
**Problem:**
* Quantity control buttons for product option is shifted down for bundle product on PDP
* Added property margin-block-start to DropdownWrapper_customQuantity Field_type_number in ProductBundleOptions.style
* Modified the height of the Quantity Control Buttons to 48 instead of 44
=> #4295 added property margin-block-start to Quantity Control Buttons

packages/scandipwa/src/component/TierPrices/TierPrices.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4304
**Problem:**
* 'discount each' is written by bold font for bundle product with tier price
* I removed bold font for 'discount each' for bundle products and now it is written in normal font.
=> 'discount each' for bundle product  is now written in normal font instead of bold.

packages/scandipwa/src/component/CartItem/CartItem.component.js, packages/scandipwa/src/component/CartItem/CartItem.style.scss, packages/scandipwa/src/style/cms/block.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4283
**Problem:**
* When uploading a file with a long name in the cart the name gets cropped at the end
* Made the cartItem option overflow auto instead of hidden so when the file name is long a scrollbar appears to the user
=> #4283 Made the cartItem option overflow auto instead of hidden

packages/scandipwa/src/util/Url/Url.js
* Fixes #4285
**Problem:**
* Described in issue.
* Added string decoding and in case if it fail, then make it as usual. So it will try to decode and in most cases fail, but it will helpful for 3-rd tools.
=> issue-4285 Add string decoding for get params in url

packages/scandipwa/src/component/Field/Field.style.scss, packages/scandipwa/src/component/NewsletterSubscription/NewsletterSubscription.style.scss, packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.style.scss, packages/scandipwa/src/style/base/_input.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4315
**Problem:**
* Height of text field is 44.6 px, same for any other text input fields, not only customizable options on PDP
* Added height property inside .ProductCustomizableItem-Wrapper Field_type_text input in ProductCustomizableOptions.Style
* Removed height property inside .ProductCustomizableItem-Wrappe .Field_type_text input in ProductCustomizableOptions.Style
* Removed height property inside .NewsletterSubscription .FieldForm-Fieldset .Field input in file NewsletterSubscription.style
* Added new input selector with height property in file _input.scss
=> #4315 added height property inside .ProductCustomizableItem-Wrapper Field_type_text input in ProductCustomizableOptions.Style

packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4314
**Problem:**
* Height of dropdown fields is less than 48 px in the mobile view.
* Removed the height property from the Clickable Selector in the file FieldSelect.style
* Added the height property in the Select selector in the file FieldSelect.style
=> Issue 4314

packages/scandipwa/src/component/CartItem/CartItem.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4283
**Problem:**
* When uploading a file with a long name in the cart the name gets cropped at the end
* Made the cartItem bundle options overflow appears as three dots
=> #4283 added a div selector  inside the selector Option with the properties overflow, text-overflow, and white-space

packages/scandipwa/src/store/Cart/Cart.dispatcher.js
* Fixes #4327 
**Problem:**
* Infinity loader if user goes to cart after logout
* Set loading state to false when loading Empty guest cart
=> [4327] set loading cart to false when loading guest empty cart

packages/scandipwa/src/component/ProductCompare/ProductCompare.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4231
**Problem:**
* Scroll can not be moved till the end on Compare page if user deleted one of products
* Changed the condition inside the componentDidUpdate method in the file ProductCompare.container
=> #4231 Changed the condition inside the componentDidUpdate method

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.style.scss, packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss, packages/scandipwa/src/component/StoreSwitcher/StoreSwitcher.style.scss
* Fixes #4350 
**Problem:**
* Lines between currency and store switchers, store switcher and compare list are bold
* Fixed the bold lines
=> fixed bold line under currency and store switcher

packages/scandipwa/src/component/CmsBlock/CmsBlock.container.js, packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.container.js, packages/scandipwa/src/component/Menu/Menu.container.js, packages/scandipwa/src/component/ProductListWidget/ProductListWidget.container.js, packages/scandipwa/src/component/SliderWidget/SliderWidget.container.js, packages/scandipwa/src/component/StoreSwitcher/StoreSwitcher.container.js, packages/scandipwa/src/route/CmsPage/CmsPage.container.js, packages/scandipwa/src/route/ContactPage/ContactPage.container.js, packages/scandipwa/src/route/ProductComparePage/ProductComparePage.container.js, packages/scandipwa/src/util/Request/DataContainer.js
* Fixes #4376 
**Problem:**
* Updates not only 1 widget, but all with same type of datacontainername
* Handle listen for broadcast not for all datacontainers
=>  issue - 4376 - Handle listen for broadcast not for all datacontainers

packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4325
**Problem:**
* Price/Nickname, Quality/Summary and Value/Review on different lines 
* Moved fields on the right side up so they are on the same line as left side fields
=> Price/Nickname, Quality/Summary and Value/Review are on the same line in a  review popup

packages/scandipwa/src/component/MyAccountOrderItemsTable/MyAccountOrderItemsTable.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4092
**Problem:**
* Wrong comments order on IOS
* Change symbols in timestamp for right comments order on IOs
=> #4092 - Change symbols in timestamp for IOs

packages/scandipwa/src/component/MenuItem/MenuItem.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4371
**Problem:**
* Placeholder for breadcrumbs is missing on PLP when loading page if user goes from PLP to PLP
* Remove breadcrumbs between categories
=> #4371 - Remove breadcrumbs between categories

packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.container.js, packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.form.js
* Fixes #4338
**Problem:**
* Name of state saved for field without dropdown when user selected other country
* initialized current address values, set input values to current values
* #4359
=> [4338] initialized current address values, set input values to current values

packages/scandipwa/src/component/Menu/Menu.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4433
**Problem:**
* Space appeared between slider and header line. It was due to wrapper that had height more than a header actual height.
* adjusted menu total height
=> #4441 - adjusted menu total height

packages/scandipwa/src/component/ShareWishlistPopup/ShareWishlistPopup.container.js
* Fixes #4247 
**Problem:**
* Mobile: Title 'Share Wishlist' stays in wishlist after sharing wishlist
* Update navigation state on share wishlist
=> [4247] update navigation state on share wishlist

packages/scandipwa/src/component/Popup/Popup.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/1657
**Problem:**
* For older firefox and edge browsers, padding-bottom wasn't showing. According to this - https://stackoverflow.com/questions/48687129/padding-bottom-not-working-in-firefox-ie11 , I did use pseudo element to make it work.
* instead of, set padding on every side, but the bottom. then, in pseudo element, set padding-bottom
=> fixed padding bottom issue in older firefox and older edge

packages/scandipwa/src/component/Field/Field.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4251
**Problem:**
* Gave error 'Incorrect File extension upload!' if uploaded a correct file extension but capitalized.
* Converted the file field's value to lower case (only if type===file) when it gets passed to the validation function.
=> [4251] - File's name toLowerCase on validation

packages/scandipwa/src/component/Breadcrumb/Breadcrumb.component.js, packages/scandipwa/src/component/Breadcrumb/Breadcrumb.style.scss
* Fixes #4365
**Problem:**
* One of letters is written as capital letter in the middle of word in breadcrumbs in my account and compare list
* Set name to lowercase and then capitalize with css
=> [4365] set name to lowercase and then capitalize with css

packages/scandipwa/src/util/Url/Url.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4351
**Problem:**
*  If someone changed " : " with " = " in the url, app would redirect you to the oops, not found page.
* Added a bit of parsing logic, it now changes = with : so that app works as intended
=> #4468 - fixed url not parsing = instead of :

packages/scandipwa/src/component/ShareWishlistForm/ShareWishlistForm.component.js, packages/scandipwa/src/component/ShareWishlistPopup/ShareWishlistPopup.component.js, packages/scandipwa/src/component/ShareWishlistPopup/ShareWishlistPopup.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4451
**Problem:**
* Loader was missing in share wishlist pop-up
* Added a bit of state logic to the parent element, made sure that the component gets isFormLoading prop so that it can determine if the loader should show up
=> #4451 - fixed share whishlist not showing loading state

packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4427
**Problem:**
* 404 page opened for a sec when adding product to cart from wishlist if product has required options
* I couldn't reproduce the issue, no matter what - tried incoginito, other browser's and so on. The error was caught in the dispatcher. Changed how the redirection, error is treated in that case (re-used the logic that will be executed if configurableVariantIndex isn't found) - set the state first, did history.push();
=> fixed not found page error when redirected from the wishlist page

packages/scandipwa/src/component/ProductWishlistButton/ProductWishlistButton.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4463
**Problem:**
* Disabled concurrent add/remove from wishlist requests
* Removed the function that returns null if WishlistReducer.isLoading (isAddingWishlistItem)
=> [4463] - Enabled concurrent add/remove from wishlist requests

packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js, packages/scandipwa/src/component/CheckoutOrderSummaryPriceLine/CheckoutOrderSummaryPriceLine.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3307
**Problem:**
* Tax line is displayed in empty cart on a mobile phone
* Created a check that looks at price
=> #3307 Tax line is displayed in empty cart on a mobile phone

packages/scandipwa/src/route/CartPage/CartPage.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4226
**Problem:**
* extra border-bottom was showing on the mobile view. had to remove it. in the process, because of the specificity, I had to use a trick which had already been used(did global find).
* removed border-bottom on the Expandable element on mobile view.
=> #4226 - removed extra bottom border

packages/scandipwa/src/style/cms/block/homepage-category-preview.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4329
**Problem:**
* The Buttons weren't centralized
* Text inside the Buttons wasn't aligned correctly when hovering over the Buttons.
* Added Property align-self inside Button selector in file homepage-category-preview.scss
* Added Property padding-inline inside Button selector in file homepage-category-preview.scss
* Removed Property display-block from Button selector in file homepage-category-preview.scss
* Added Selector -Button:not([disabled]):hover in file homepage-category-preview.scss
=> #4329 Fix for the buttons in 40kSKU

packages/scandipwa/src/component/CheckoutSuccess/CheckoutSuccess.style.scss, packages/scandipwa/src/route/Checkout/Checkout.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4454
**Problem:**
* On very small devices, like iphone 7 or older, two buttons were covering each other on the Thank You page. The 'continue Shopping button' was position fixed and it's okay when the device height is big enough. However, on very small devices, that positioning didn't really work.
*  So, what I did was to, instead of fixed, make the button position absolute. Now, by default, all the wrappers between the button and the main (the element I wanted the button to be relative to) had position relative by default. Made sure that all the wrappers has a position relative. that way, you get the default fixed position behaviour, but also no covering when device height is too small.
=> #4454 - fixed button covering another button on small height devices

packages/scandipwa/src/component/Field/Field.style.scss, packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.style.scss, packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4400
**Problem:**
* Radio buttons and checkboxes are narrowed on window resizing and their sizes depended on their ProductBundleItem-Labels
* Assigned width and word-breaking to the labels
* Assigned max-width to the inputs (instead of width - width is assigned in px in later codes)
=> [4400] - Radio and Checkbox inputs on resizing - Fixed

packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.container.js, packages/scandipwa/src/route/Checkout/Checkout.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4077
**Problem:**
* Form were nested and react was yelling about that. Plus, submitting one form caused submitting the other. hence, unnecessary validations. Also, parent form form had a scrolling logic, if something wasn't right, it was scrolled to the top of the form.
* Removed the parent form, so that submitting on form isn't causing the next one to submit as well. Plus, move the scrolling logic on the child form(previously child form, now it's a standalone form)
=> #4077 - removed nested form, added scroll logic to inner form

packages/scandipwa/src/route/SearchPage/SearchPage.container.js, packages/scandipwa/src/route/SearchPage/SearchPage.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4455
**Problem:**
* title and breadcrumbs are written in capital letters on search result page
* removed text-transform: uppercase; on the element
=> #4455 - removed uppercasing of the user input

packages/scandipwa/src/route/MyAccount/MyAccount.style.scss
* Fixes #4558 
**Problem:**
* Loader in MyWish item and in MyOrders table was shifted to the bottom of components
* Removed property that replaced the loader to the bottom
=> removed propery which replaced loader to the bottom of a card in mywishlist mobile

packages/scandipwa/src/style/abstract/_icons.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3230
**Problem:**
* iOS: RTL: Icon is broken in Add to home screen banner
* Rotate 315deg
=> [3230] - IOS-RTL: Fixed the icon in Add to home screen banner

packages/scandipwa/src/component/CartCoupon/CartCoupon.style.scss
* Fixes #4529 
**Problem:**
* Buttons in cart page shifted down and submit button was filling 100% of available space in 1020 size, but in local PC this behavior was seen in 850px
* removed some properties for submit button which caused this bug
=> fixed buttons in cart when resizing

packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.style.scss
* Fixes #4541 
**Problem:**
* Shipping method title and rate wrap to second line if they are long
* Fixed so it stay on the same line
=> Fixed shipping method to stay on same line

packages/scandipwa/src/component/OfflineNotice/OfflineNotice.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4379
**Problem:**
* Offline mode icon was broken in RTL mode
* Mirrored the cloud and stick icons 
* The rest of SVGs follow Amazon's RTL pattern
=> [4379] - Fixed the offline mode icon in RTL mode

packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.container.js, packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4437
**Problem:**
* checkbox is checked only when the default shipping === default billing (customer data in the redux store), not accounting for changing the address (custom address or choosing another previously saved address (non-default)) in the checkout shipping step.
* In the checkout shipping file:
When selecting a previously saved address other than the default, the checkout reducer.shippingFields are updated.
* In the checkout billing file:
> New constants were created: newShippingStreet, newShippingId - (from the checkout reducer's shippingFields)
> -- newShippingId is:
> ----- undefined: if the default shipping address is used, and if custom shipping address
> ----- number: if a …
=> [4437] - 'Same shipping and billing addresses' checkbox is no longer checked if user has different default billing address

packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.style.scss
* Fixes #4228 
**Problem:**
* In mobile checkout page summary block had a double border, one is from ExpandableContent's and one CmsBlock's
* Removed the border bottom for CmsBlock because its parent, ExpandableContent has
=> removed border for cms block cuz parent block has border-bottom

packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.style.scss
* Fixes #4548 
**Problem:**
* Colon after qty of ordered item drop down on IOS if there is multiple lines
* Fix to stay at top
=> Fixed Colon after qty moved down on IOS

packages/scandipwa/src/route/CmsPage/CmsPage.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4573
**Problem:**
* Text hovers on bullets and numeration
* Bullets, numbers and list items are separated now
=> List item text doesn't overlap bullet and number

packages/scandipwa/src/route/Checkout/Checkout.component.js
* Fixes #4604 
**Problem:**
* Tries to destruct value from null
* If null, we set empty object
=> Add default value for promo block rendering in case of null

packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3146
**Problem:**
* Cross sign shifted down in compare list around 2-3 pixels.
* Aligned Compare's close-buttons with their product's title
=> [3146] - Aligned Compare's close-buttons with their product's title

packages/scandipwa/src/route/CmsPage/CmsPage.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4594
**Problem:**
* Long word in table on CMS page is not moved to second line
* Added styles to long words
=> #4594 Long word in table on CMS page is not moved to second line

packages/scandipwa/src/component/ProductCard/ProductCard.component.js
* Fixes #4506 
**Problem:**
* User didn't redirect from PLP if the visual_swatch or text attribute was inside PDP 
* Added check condition if there is value for attribute in PLP
=> added check for attributes if they have attribute_values

packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
* Fixes #4069 
**Problem:**
* Product name or stars is not aligned with the cross in Wishlist on mobile
* Fixed alignment
=> Fixed product name not aligned with cross on IOS

packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4035
**Problem:**
* Minus button activated if product only 1 in stock available, and it is less than minimum salable quantity (= 2 items)
* Added checks to the minus and plus buttons
=> #4035 Minus and plus button disabled if product only 1 in stock

packages/scandipwa/package.json, packages/scandipwa/src/component/FieldFile/FieldFile.container.js
* Fixes #3511 
**Problem:**
* File input display an infinite loader (+ and error in console) if user canceled the input on the second time
* Fixes the error but checking if there is a file input or not
=> Fixes Never-Ending loader if user canceled second file input

packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js, packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4364
**Problem:**
* Background is visible in dropdown lists
Issue couldn't be produced directly. It's shown in this [comment](https://github.com/scandipwa/scandipwa/issues/4364#issuecomment-1075339302) with pics 
* Wrapped the list items with a div to which I specified max-height and auto overflow
* Changed the parent's overflow to auto
By this, I made dropdown lists support any number of options + no visible background.
=> [4364] - Background is no longer visible in dropdown lists

packages/scandipwa/src/component/Html/Html.component.js, packages/scandipwa/src/component/Router/Router.component.js, packages/scandipwa/src/component/Router/Router.style.scss
* Fixes scandipwa/scandipwa/issues/4273
**Problem:**
* Footer jumping on clicking HomepageCategoriesButtons on the homepage as a result of collapsing the components above the footer and rendering new ones.
Made the page scroll to top on clicking those buttons and therefore not focusing the screen on the collapsing part and the footer.
The new functions added:
* scrollToTopFunction
* domToReactFunction:
The purpose is to add onClick prop to those 3 buttons.
So, it checks the links' children, 
-- if the right class (intended buttons) -> modifies the button and uses domToReact to return the rest of the siblings,
-- else returns domToReact(children)
* the original **replaceLinks** function is modified to use the new domToReactFunction instead of …
=> [4273] - Footer jumping on HomepageCategoriesButtons clicking - Fixed

README.md
* None.
**Problem:**
* There was a demo with two broken links.
* Those links had double "https://"s, which prevented them from working.
=> Fixing README.md demo URLs

build-packages/scandipwa-dev-utils/composer.js
* Fixes #4618 
**Problem:**
* Can't change version of BE module in composer.json if source files package.json requires strict version of module.
* At the moment CSA goes through all package.json files to find scandipwa: { composer: {} } deps and it means that root dependencies that we defined in root folder are with lowest priority. So we can just save them for later use.
In case if we need to update module, we need to set correct version in composer.json same as in package.json for scandipwa: composer section! In this case Developer will have full control on what versions should be installed.
Test cases:
1. 
- Downgrade version of pwa to 5.2.0 (Requires scandipwa/cache to be 1.1.4)
- Set version of cache module in composer.json to 1.1.5
- Set version …
=> issue-4618 - Set high priority for checking composer deps in root packages.json in CSA

packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss, packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4530
**Problem:**
* List/Grid icons and Sort by dropdown is shifted left on PLP
* Aligned all items and fixed mobile version
=> #4530 List/Grid icons and Sort by dropdown is shifted left on PLP

packages/scandipwa/src/component/ProductInformation/ProductInformation.component.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js
* Fixes #4480 
**Problem:**
* Description (About tab) was not shown if the description contains only an image
* state isInformationTabEmpty is true in this case
* Fixed the function isProductInformationTabEmpty to return false if HTML contain only image
* now about tab show even if it is only an image
=> Fixed product description not shown if only image

packages/scandipwa/src/component/CartCoupon/CartCoupon.component.js, packages/scandipwa/src/component/CartCoupon/CartCoupon.container.js, packages/scandipwa/src/component/Field/Field.component.js, packages/scandipwa/src/store/Cart/Cart.dispatcher.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3125
**Problem:**
In/Valid coupons checks were not connected to the input styling
1 - In CartDispatched, applyCouponToCart function is set to return true if valid coupon, else null.
2 - In CartCoupon.container, created a state variable isBadCoupon whose update depends on the applyCouponToCart function. And it's passed to the CartCoupon.component
3 - In CartCoupon.component, created a state variable isFieldWithError that changes to
--- true if bad coupon
--- false on input change (input returns to green)
-- isFieldWithError is updated in getSnapshotBeforeUpdate, where is prevProps is compared with the current
and when the component's state is updated, I also update isBadCoupon in the container …
=> [3125] - /cart coupon's input turns red on entering an invalid coupon Code

packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
* Fixes #4228 
**Problem:**
* CmsBlock was absent in mobile phones in checkout page summary block
* Made the logic of render same as for desktop
=> fixed cmsBlock render in expandable checkout block

packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4478
**Problem:**
* Mac: vertically cropped dropdowns
* Added `min-height: max-content` to select tags
=> [4478] - Mac: vertically cropped dropdowns - Fixed

packages/scandipwa/src/component/Html/Html.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4273
**Problem:**
* The original merged 
PR https://github.com/scandipwa/scandipwa/pull/4431 (commit 24cf3b0950a34420ecea4986d8e4c199537ca76f) 
focused on the buttons (scrollToTop on clicking HomepageCategoriesButtons not all redirects)
Reverted commit 24cf3b0950a34420ecea4986d8e4c199537ca76f (undid parsing buttons and domToReactFunction)
But kept the same idea of scrolling to top on changing pages
Only expanded it to all links (not just buttons)
Also added scrollToTop to the onClick function of Products' cards since the issue was reproduced on clicking on Products cards
(Also merged master)
*ScrollToTopFunction is on line 138 in the new commit*
=>  [4273] - Fixed the footer's jumping when clicking on (Links and ProductCards) on CMS

packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
* Fixes scandipwa/scandipwa/issues/4676
**Problem:**
* Items count and category sort elements were absent when q of items was 0
* Changed the rendering logic of these two components to achieve the desired UI.
=> [4676] - Qty of items on PLP and dropdown are absent if user opened PLP without products - fixed

packages/scandipwa/src/component/MyAccountAddressPopup/MyAccountAddressPopup.container.js
* Fixes scandipwa/scandipwa/issues/4627
**Problem:**
* Changing/deleting/editing addresses in MyAccount didn't trigger a success notification
* Added the appropriate logic into methods responsible for processing the aforementioned operations
=> #4627 - Adding/deleting/editing addresses now includes a success message

packages/scandipwa/src/store/Cart/Cart.dispatcher.js
* Fixes #4660 
**Problem:**
* Cart dispatchers (createGuestEmptyCart and updateInitialCartData) are dispatched so there is a time gap between them the loader is stopped
* Removed the stopping the loader for the first dispatch that is triggered
=> removed dispatcher for stoppping the loader for the first dispatch 

packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.config.js, packages/scandipwa/src/route/MyAccount/MyAccount.config.js
**Problem:**
* Config URL strings weren't uniformly prepended with slashes
* Prepended the URL strings with slashes, tested for possible issues with store codes - everything works fine
=> Prepended config URL strings with slashes for the sake of convention

packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
* Fixes scandipwa/scandipwa/issues/4679
**Problem:**
* Placeholder for Sort by category button on PLP was missing
* Added new logic to display it
=> [4679] - No placeholder for Sort dropdown - fixed

packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
* Fixes #4664
**Problem:**
* Row-gap wasn't supported with older IOS versions
* Used margin-bottom instead of row-gap
=> replaced row-gap with margin bottom because older IOS versions

packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.style.scss
* Fixes #4543 
* Fixes #4707 
**Problem:**
* Indent between select field and error label was too big
* corrected styles
=> fixed padding for error messages

packages/scandipwa/src/component/Image/Image.style.scss
* Fixes #4661 
**Problem:**
* The alt text of the images was visible in Firefox
* Made color transparent
=> made color for text transparent TEST

packages/scandipwa/src/component/ProductCompareButton/ProductCompareButton.container.js
* Fixes #4651 
**Problem:**
* Request sent every time when the user clicked on compare button even if it Is loading and loader is shown.
* Added check if loading then return
=> added check if it is loading for compare btn

packages/scandipwa/src/component/GroupedProductsItem/GroupedProductsItem.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4233
**Problem:**
* Grouped product is not added to cart if it contains Out of stock child product
* Grouped product is added to cart if it has Out of stock child product
=> #4233 - Create filter for out of stock grouped product

packages/scandipwa/src/route/MyAccount/MyAccount.container.js
* Fixes scandipwa/scandipwa/issues/4736
**Problem:**
* Older IOS devices may not support the Object.fromEntries syntax, resulting in errors on pages that use it
* Replaced the aforementioned syntax with equivalent logic written in a more widely supported syntax.
=> #4736 - oops page on IOS 12.1 - fixed

packages/scandipwa/src/component/AddToCart/AddToCart.container.js, packages/scandipwa/src/component/ProductCompareButton/ProductCompareButton.component.js, packages/scandipwa/src/component/ProductWishlistButton/ProductWishlistButton.component.js
* Fixes scandipwa/scandipwa/issues/4686
**Problem:**
* In the registerSharedElement method at ProductCard.component, there's a line of code that causes the viewport to scroll to the top of the document when a product card is clicked
* added a stopPropagation method call to the product card action buttons so that interacting with them won't trigger the scoll
=> [4686] - Page is scrolled up if user added some product to wishlist from PLP - fixed

packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.component.js, packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.container.js, packages/scandipwa/src/query/Config.query.js, packages/scandipwa/src/store/Config/Config.dispatcher.js, packages/scandipwa/src/store/Config/Config.reducer.js, packages/scandipwa/src/util/Currency/Currency.js
* Fixes scandipwa/scandipwa/issues/4637
**Problem:**
* The Currency switched displayed currencies for which the exchange rate wasn't specified in the admin panel
* Created a new query that fetches the exchange rates
* Used this new data to filter out the currencies for which no rate was specified
* Wired the currency switcher to the new filtered list so that only the proper values are displayed
=> [4637] - Currency Switcher displays currencies for which rates were not set - fixed

packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.style.scss
* Fixes scandipwa/scandipwa/issues/4642
**Problem:**
* Putting more than a couple of products into the wishlist would have caused the Loader's parent container to grow taller than the viewport and therefore the Loader wouldn't be centered properly. 
* Set the loader's position to be fixed so as to position it against the viewport instead of its parent.
=> [4642] - Wishlist loader wasn't centered on mobile - fixed

packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.style.scss, packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.style.scss, packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.style.scss, packages/scandipwa/src/component/NavigationTabs/NavigationTabs.style.scss, packages/scandipwa/src/component/Popup/Popup.style.scss, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss, packages/scandipwa/src/route/Checkout/Checkout.style.scss, packages/scandipwa/src/route/CmsPage/CmsPage.style.scss, packages/scandipwa/src/style/abstract/_parts.scss
* Fixes scandipwa/scandipwa/issues/4165
**Problem:**
* On mobile devices without a physical home screen, the navbar would disappear and leave transparent space in it's place.
* Added the navbar's height to the action wrapper UI as whitespace to make up for the navbar disappearing
* Moved the ruleset defining that UI to _parts.scss so that it's reusable across the codebase
=> [4165] - transparent footer background on mobile

packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js, packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.style.scss
* Fixes scandipwa/scandipwa/issues/4293
**Problem:**
* Excl. tax element wasn't properly aligned with the rest of the elements in its scope
* Changed layout/CSS so that it aligns properly now
=> [4293] - the excl. tax element is now aligned to the left

packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.component.js, packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.container.js, packages/scandipwa/src/component/CheckoutDeliveryOptions/CheckoutDeliveryOptions.component.js, packages/scandipwa/src/component/CheckoutDeliveryOptions/CheckoutDeliveryOptions.container.js, packages/scandipwa/src/route/Checkout/Checkout.component.js, packages/scandipwa/src/store/Cart/Cart.dispatcher.js
* Fixes scandipwa/scandipwa/issues/4757
**Problem:**
* The full-page loader was preventing the order success message from rendering because the isCartLoading prop (Checkout.component) was always true for guest users.
* Added a line of code to Cart.dispatcher that sets the isCartLoading state to false once all the async operations are over
* Removed payment method auto-selection on checking the Terms and Conditions box on the billing page
* Removed redundant code
=> [4757] - Endless loader on the Thank You page - fixed

packages/scandipwa/src/component/Header/Header.component.js
* Fixes #3718
**Problem:**
* Promotional block was hardcoded into the website and did not update on CMS block change. 
* Edited the promotional block into CMS block so it would update according to the admin settings for CMS blocks.
=> #3718 - added promotion block to header

packages/scandipwa/src/component/Breadcrumb/Breadcrumb.style.scss, packages/scandipwa/src/component/CategoryDetails/CategoryDetails.style.scss, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
* Fixes scandipwa/scandipwa/issues/4765
**Problem:**
* Each word of product name and breadcrumbs is written with a capital letter
* Removed CSS rules that capitalized both
=> [4765] - Each word on product page and breadcrumbs capitalized - fixed

packages/scandipwa/src/util/Price/Price.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4782
**Problem:**
* Ooops page opens on PLP when switch currency
* Set default currency as USD in formatPrice, Oops page not opening when switching currency
**Notice:**
* PR solves only the problem with the Oops page, the problem with the correct display of the selected currency was not affected
=> #4782 - Set default currency as USD in formatPrice

packages/scandipwa/src/component/Breadcrumbs/Breadcrumbs.component.js
-  Fixes https://github.com/scandipwa/scandipwa/issues/4773
**Problem:**
- Breadcrumbs are missing on /customer/account and /customer/account/edit page
- Remove condition pathname match for ACCOUNT_URL on Breadcrumbs component class
=> [4773] remove condition related to breadcrumbs visibility on my account page

packages/scandipwa/src/route/MyAccount/MyAccount.style.scss
* Fixes scandipwa/scandipwa/issues/4770
**Problem:**
The content of the MyAccount page wasn't aligned with the rest of the content on Mobile
* Added padding to the element
=> [4770] - MyAccount content width fix

packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js
* Fixes #4747 
**Problem:**
* Price did not appear if it was equal to 0
* Made price only disappear if it's undefined, instead of 0.
=> #4747 - made price appear if it's 0

packages/scandipwa/src/component/CategorySort/CategorySort.component.js, packages/scandipwa/src/component/CategorySort/CategorySort.container.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4797
**Problem:**
* PLP not use default sort field for category
* Display right default sort field on PLP
=> #4797 - Display default sort on PLP

packages/scandipwa/src/component/CartCoupon/CartCoupon.component.js
* Fixes #4730 
**Problem:**
* Red outline appeared when deleting coupon text. 
* Removed the "isRequired" rule that made that happen.
=> 4730 - removed red outline on deleting coupon

packages/scandipwa/src/component/CartItem/CartItem.component.js, packages/scandipwa/src/component/CartOverlay/CartOverlay.component.js, packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js, packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.style.scss, packages/scandipwa/src/component/CheckoutOrderSummaryPriceLine/CheckoutOrderSummaryPriceLine.component.js
* Fixes #4803 
* Fixes #4796
**Problem:**
* Order total and subtotal were not appearing when the items total cost was 0. 
* Font size did not match the one in Luma. 
* Removed some conditionals and changed numbers to strings for order totals. 
* Edited font size to 12px.
=> #4803 - added order total and subtotal fields to orders equal to 0

packages/scandipwa/src/component/Field/Field.style.scss, packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
* Fixes #4705
**Problem:**
* Line height for textareas was inconsistent for other places in the app
* Made line height 0 and 1 for the labels
=> fixed line height for textareas from other places

packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
* Fixes scandipwa/scandipwa/issues/3468
* Fixes scandipwa/scandipwa/issues/4798
**Problem:**
* On PLP, the Add to Cart buttons inside of Product Cards are viewable/clickable even though the product hasn't finished loading yet, which causes errors on click
* For Grid view: removed the hover state from product cards that haven't finished loading
* For list view: same problem solved by making the buttons invisible and non-interactive.
=> [4798] - error on clicking Add to Cart while the product is loading

packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4340
**Problem:**
* Wrong meta title for dynamic pages
* Remove meta update when category is not yet received
=> #4340 - Remove meta update when category is not yet received

packages/scandipwa/composer.json, packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/package.json, packages/scandipwa/src/query/MyAccount.query.js, packages/scandipwa/src/route/Checkout/Checkout.container.js, packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.container.js, packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
* Fixes #4122 
**Problem:**
* In Magento 2.4.4 there is strict checking for an email while resetting a customer password via email
* The email message provides a customer with a link that leads to a resetting page and it contains `customer_id ` as one of the params, so in order to get the customer's email, I pass this id to BE and get the email from that id, and further pass the email to the reset method. Before this PR `null` was sent instead of email
* scandipwa/customer-graph-ql#34
=> Created customer_id field and pass to BE to get its email

packages/scandipwa/src/route/Checkout/Checkout.component.js, packages/scandipwa/src/store/Cart/Cart.dispatcher.js
* Fixes scandipwa/scandipwa/issues/4660
**Problem:**
* The issue reappeared after one of the latest PR merges 
* Another issue that appeared as a result of this - on checkout, the full page loader would render twice on sign-in
* Changed the conditions on which the full page loader renders so that it only appears when the cart is empty
* in Cart.dispatcher, removed the updateIsLoadingCart method calls from createGuestEmptyCart since they're not really needed there
=> [4660] - double Order Summary loader on singn-in on checkout - fixed

packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4820
**Problem:**
* Mobile: Padding above subtotal is absent in Cart and Checkout.
* Added padding above subtotal.
=> [4820] added padding top to subtotal on mobile

packages/scandipwa/src/component/StoreInPickUpPopup/StoreInPickUpPopup.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4688
**Problem:**
* Title for pop-up 'Select Store' stays on shipping page after selecting store
* Change header state after selecting store
=> #4688 - Close store in popup on mobile after store change

packages/scandipwa/src/route/Checkout/Checkout.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4952
**Problem:**
* Number of checkout steps was 3, had to be 2
* Modified `Checkout.component.js` to show 1 less step on checkout.
=> #4952 Wrong Qty of steps on Checkout

packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.component.js, packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.component.js
* Fixes scandipwa/scandipwa/issues/4660
**Problem:**
* The rendering of the login fields in checkout depended on a prop that was always undefined.
* Replaced that prop with a util method that returns correct login status.
=> [4660] - login fields don't disappear on checkout after sign-in from header - fixed

packages/scandipwa/src/component/ProductGallery/ProductGallery.container.js, packages/scandipwa/src/component/VideoPopup/VideoPopup.config.js
* Fixes [product gallery disappears if there is no base image and yt videos with hyphens don't work ](https://github.com/scandipwa/scandipwa/issues/4938)
**Problem:**
* product that only has a video and no other thumbnails, the video gallery carousel disappears
* product that has a youtube video with a link that contains a hyphen in the videocode, playback does not happen
* changed the base image position to zero instead of -1 if there is no base image for the video
* changed the youtube video regex to support videos with a hyphen in the videocode
=> fix yt videos with hyphens, set base image position to a valid one

packages/scandipwa/src/component/ProductCompare/ProductCompare.component.js, packages/scandipwa/src/component/ProductCompare/ProductCompare.container.js, packages/scandipwa/src/component/ProductCompare/ProductCompare.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4899
**Problem:**
* Scrollbar and scroller block element were overriding each-other's `scrollLeft` parameter, which caused noticeable product twitching in Safari and Firefox in Product Compare component.
* I modified `ProductCompare.continer.js` to correctly handle scroll events and ignore calls depending on whether they come from the user or function.
* I also modified `ProductCompare.component.js` to not include scrollbar inside the scrolling component, otherwise, that caused another conflict with scroll events.
=> #4899 Stop scrollbar and scroller block from overriding each-others' `scrollLeft`

packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4340
**Problem:**
* If open category -> CMS -> same category, title wasn`t updated
* Update title if category the same(after CMS page)
=> #4330 - Update meta if category didn`t changed after CMS

packages/scandipwa/public/index.html
* Fixes scandipwa/scandipwa/issues/4932
**Problem:**
* Mobile address view was user-resizeable
* Everything in the app is non-resizable on mobile
=> [4932] -  page with address can be resized on Android - fixed

packages/scandipwa/src/component/ProductCard/ProductCard.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4957
* Also depends on https://github.com/scandipwa/scandipwa/pull/4956
**Problem:**
* Couldn't add grouped or bundle items with no required options
* I modified `requiresConfiguration()` function to consider more cases for items. Now you can add items without options without getting redirected.
* This PR also depends on #4956 because otherwise redirect would happen every time, because of link issue.
=> #4957 Edited `requiresConfiguration()` to check grouped items for options too

packages/scandipwa/src/component/Router/Router.component.js
* Fixes #2948 
**Problem:**
* The Navigation Tabs were rendered with suspense on mobile
* Took out from suspense the before components
=> 2948 nav tab blink

packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.style.scss
Fixes https://scandiflow.atlassian.net/browse/CTO2-543
Problem:
Filter overlay in mobile appears slowly, but disappears instantly
In this PR:
Removed the transition animation for filter overlay
=> [543] removed the animation for filter overlay

packages/scandipwa/src/component/Loader/Loader.style.scss, packages/scandipwa/src/component/Router/Router.component.js, packages/scandipwa/src/component/Router/Router.style.scss
* Fixes scandipwa/scandipwa/issues/4949
**Problem:**
* On initial load, there were a lot of loaders that had different CSS rulesets applied to them, making them jump on the viewport.
* Added specific CSS rulesets to these initial loaders so that they behave identically.
=> 4949 - jumping loaders - fixed

packages/scandipwa/src/util/Request/QueryDispatcher.js, packages/scandipwa/src/util/Request/Request.js
* Fixes scandipwa/scandipwa/issues/3731
**Problem:**
* QuereyDispatcher's fetch cancel functionality didn't work. On a slow connection, the app would send loads of requests quickly which would all try to update the same state, resulting in race conditions. 
* Introduced AbortController, an API designed specifically to allow developers to cancel fetch requests programmatically.
=> [3731] - wrong content on quick route changes w/ slow internet - fixed

packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/5020
**Problem:**
* Plus and minus buttons are not centered for bundle product on mobile
* Plus and minus buttons are centered for bundle product on mobile
=> #5020 - Centrilize plus/minus button for bundle products

packages/scandipwa/public/index.html, packages/scandipwa/src/component/Draggable/Draggable.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4710
**Problem:**
* Highlight color is blinking if user zoom first image
* Background for first image on PDP painted by Secondary color 'Highligh'
* Highlight color shown in image popup is user click on default image (if custom image is absent)
* changed the secondary light color variable to white color
=> [4710] changed the secondary light color

packages/scandipwa/src/component/Field/Field.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4690
**Problem:**
* Not required fields stays grey after submit
* Not required fields becomes green after submit
=> #4690 - Field stay green after submit if not required

packages/scandipwa/src/component/Field/Field.style.scss
* Fixes #4970
**Problem:**
* Checkboxes and Radio were resized for Bundle Product
* let the label shrink and not resize the checkboxes and radio
=> let the label shrink for customizable items

packages/scandipwa/src/component/SearchOverlay/SearchOverlay.component.js, packages/scandipwa/src/component/SearchOverlay/SearchOverlay.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4945
**Problem:**
* Excessive padding on search overlay
* Edited `SearchOverlay.style.scss` to remove `padding-block-start`.
=> remove-padding

packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4859#event-6718689509
**Problem:**
* Long file name overlaps to the next product card in Wishlist
* File Name is moved to the second line in wishlist
=> #4883 - Add wrap for options in wishlist

packages/scandipwa/src/component/ProductGallery/ProductGallery.component.js
* Fixes #4710 
**Problem:**
* The placeholder has only base src, zoom image component uses only large src of the image
* if large src is not defined then use base src
=> passing base src if large is absent

packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4881
**Problem:**
* Products are displayed in grid view when resizing to the desktop view if list view is set
* Products are displayed in list view when resizing to the desktop view if list view is set
=> #4881 - Change default plp type value

packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4923
**Problem:**
* Different indent between two placeholders for product card in widget and on PLP
* The same indent between two placeholders for product card in widget as on PLP
=> #4923 - Made the same indent for product placeholder on widget

packages/scandipwa/src/component/ProductActions/ProductActions.style.scss, packages/scandipwa/src/component/ProductInformation/ProductInformation.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/5005
**Problem:**
* PDP layout is broken if short or long description contain long word without spaces
* PDP layout isn`t broken if short or long description contain long word without spaces
=> #5005 - Add wrap for short name

packages/scandipwa/src/component/ShareWishlistForm/ShareWishlistForm.form.js
* Fixes https://github.com/scandipwa/scandipwa/issues/5050
**Problem:**
* Field for Message stays grey after validation in Share Wishlist form in My Account
* Field for Message becomes green because it's not required
=> #5050 - Validate message field in share wishlist form

packages/scandipwa/src/component/ProductBundleOption/ProductBundleOption.component.js, packages/scandipwa/src/util/Product/Transform.js
* Fixes https://github.com/scandipwa/scandipwa/issues/5060
**Problem:**
* By default None option isn't selected for not required bundle option on PDP
* None option is selected by default if this option isn't required
=> #5060 - Select none for not required bundle radio option

packages/scandipwa/src/component/MyAccountNewsletterSubscription/MyAccountNewsletterSubscription.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/5046
**Problem:**
* Checkbox 'General subscription' is not selected if customer is subscribed
* Checkbox 'General subscription' is selected if customer is subscribed
=> #5046 - Not set subscribe status if customer is empty

packages/scandipwa/src/component/SwipeToDelete/SwipeToDelete.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/5090
**Problem:**
* Area colored in secondary color is displayed in the cart and Wishlist
* Area is white
=> #5090 - Set swipe background color transparent

packages/scandipwa/src/component/Menu/Menu.style.scss, packages/scandipwa/src/component/MenuItem/MenuItem.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3025
**Problem:**
* Menu Item CSS Class - Menu-ItemFigure_type_hideOnDesktop doesn't work
* This menu item is displayed only on mobile layout
**Support for 'Available CSS classes' section:**
* https://manual.scandipwa.com/progressive-web-app/menu-manager
=> #3025 - Add support for hideOnDesktop class

packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3777
**Problem:**
* Subscribed guest automatically unsubscribes when creating an account
* User stays subscribed after sign up as in default Magenta
=> #3777 - Don`t send not selected subscribition status when sign up

packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3654
**Problem:**
* Counter of Qty of grouped product present in Wishlist
* Counter of Qty of grouped product absent in Wishlist
=> #3654 - Hide qty for grouped product in wishlist

packages/scandipwa/src/route/MyAccount/MyAccount.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4999
**Problem:**
* Vertical scrollbars appear when the screen is resized in the wishlist tab on the account page
* Included `overflow-y: hidden` to stop it from appearing on desktop.
=> 4999 Hide vertical scroll bars on wishlist tab when screen is resized 

packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.container.js, packages/scandipwa/src/type/Price.type.js
* Fixes https://github.com/scandipwa/scandipwa/issues/5032
**Problem:**
* The tier price is displayed on PDP and PLP when the tier price is higher than the regular price
* Updated how the tier price is passed to the price component from just a string to an object containing the currency, value and formatted value
* Added a tier price type for props validation
=> #5032 - Hide tier price if higher than regular price

packages/scandipwa/src/route/StyleGuidePage/StyleGuidePage.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4752
**Problem:**
* Error messages under fields, checkboxes or radio buttons are not red on /styleguide page
* Uses correct template for error message on styleguide page
=> #4752 - Use correct template for error message on styleguide page

packages/scandipwa/src/route/CartPage/CartPage.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4922
**Problem:**
* 0 tax and 0 subtotal are shown in Cart if there are no products
* 0 tax and 0 subtotal are absent in Cart if there are no products
=> #4922 - Hide totals if cart is empty

packages/scandipwa/package.json, packages/scandipwa/src/util/Auth/Token.js, yarn.lock
* Fixes #5072
**Problem:**
* Magento is using JWT for auth tokens now. JWT has it's own expiration mechanism, and the token lifetime cannot be prolonged, like it's done for the session.
* Added the additional check of the JWT expiration field in order to trigger logout action once the token becomes invalid.
=> See #5072 Added additional check if JWT is expired

packages/scandipwa/src/query/Cart.query.js, packages/scandipwa/src/store/Cart/Cart.reducer.js
* Fixes #5112
**Problem:**
* The virtual product graphql fragment was missing, thus the request didn't get virtual product specific fields.
* Added necessary fields to the request.
=> Virtual Product Customizable Options

packages/scandipwa/src/component/NavigationTabs/NavigationTabs.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/5101
**Problem:**
* The cart items quantity was not displaying on the mobile minicart when products are added to the cart.
* Updated the `renderMinicartItemsQty` method to use the `total_quantity` which contains the total quantity of items in the cart
=> #5101 - Show cart items quantity on mobile minicart

packages/scandipwa/src/route/OrderPrintPage/OrderPrintPage.style.scss
* Fixes #5124
**Problem:**
* The navigation appeared in the mobile layout.
* Hid the navigation.
=> See #5124 Hid footer navigation on mobile view for the order print page

packages/scandipwa/src/route/CartPage/CartPage.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4826
**Problem:**
* The warning container had a height lesser than that of the checkout button.
* Adds the same height used by the button to the warning container and also aligns the text horizontally.
=> #4826 - Added height to the warning container displayed in the cart for mobile

packages/scandipwa/src/component/MyAccountMyOrders/MyAccountMyOrders.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4987
**Problem:**
* Content under the status column in the downloadable orders table overlapped once you resized the safari browser.
* Removes the `display: grid` and its related properties from the `MyAccountMyOrders` css class which seems redundant.
=> #4987 - Fixed overlapping downloadable orders table cell content when resized in safari  

packages/scandipwa/src/component/FieldNumberWithControls/FieldNumberWithControls.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4890
**Problem:**
* Plus button is disabled for child of grouped product if Qty of child product in stock is 1 and user clicked 'minus' button
* User can increase Qty from 0 to 1
=> #4890 - Change condition for max salable qty is 1

packages/scandipwa/src/component/MyAccountForgotPassword/MyAccountForgotPassword.container.js, packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4908
**Problem:**
* No notification message and user stays on Forgot password page when clicking on send reset link on mobile
* User redirects to Sign in page and notification message is displayed on mobile for forgot password page
=> #4908 - Don`t check if forgot pass overlay active on mobile

packages/scandipwa/src/component/CheckoutAddressTable/CheckoutAddressTable.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4994
**Problem:**
* Long text content added to any field that appears in the checkout address book would make the table scroll horizontally.
* Added `overflow-wrap: anywhere` to break the text as it fills the container.
=> #4994 - Fixed overflowing content in checkout address table on mobile

packages/scandipwa/src/component/MyAccountAddressTable/MyAccountAddressTable.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4996
**Problem:**
* Long text content added to any field that appears in the address book would make the table scroll horizontally.
* Added `overflow-wrap: anywhere` to break the text as it fills the container.
=> #4996 - Fix overflowing content in Address book on mobile

packages/scandipwa/src/component/ProductCompare/ProductCompare.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/5089
**Problem:**
* The product tier price was not shown on the products on the compare page.
* Added the tier price by passing `price_tiers` from the product to the `ProductPrice` component.
=> #5089 - Include product tier price on compare page

packages/scandipwa/src/component/CartItem/CartItem.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/5041
**Problem:**
* Product card isn’t clickable for out of stock product in the cart
* Product card is clickable for out of stock product in the cart
**Notice:**
* The work of the fix can be checked after fixing [issue-5087](https://github.com/scandipwa/scandipwa/issues/5087)
=> #5041 - Set link for out of stock product in cart

packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/5098
**Problem:**
* The first and last name inputs on registration were invalidating names written in some languages such as Cyrillic and Mandarin.
* Removed character validation on the first and last name input fields, as validation rules vary from region to region.
=> #5098 - Removed character validation for first and last name inputs on registration

packages/scandipwa/src/component/CategoryDetails/CategoryDetails.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/5099
**Problem:**
* PLP layout is broken if description contain long word without spaces
* PLP layout is not broken if description contain long word without spaces
=> #5099 - Add wrap for category description

packages/scandipwa/src/route/Checkout/Checkout.container.js, packages/scandipwa/src/store/Cart/Cart.dispatcher.js, packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
* Fixes https://github.com/scandipwa/scandipwa/issues/5040
**Problem:**
* After checkout/logout the cart is cleared, however, this introduces a loader on the cart page infinitely. 
* Updates the `createGuestEmptyCart` method to optionally take a `disableLoader` argument to determine whether to show the loader or not.
=> #5040 - Fix infinity loading on cart page after checkout/logout

packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js, packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.container.js, packages/scandipwa/src/component/CheckoutDeliveryOptions/CheckoutDeliveryOptions.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4805
**Problem:**
* Error Message for unavailable shipping - static value on FE
* Error Message for unavailable shipping taken from the admin panel, and if empty - static value on FE
=> #4805 - Use error message from admin panel for shipping

packages/scandipwa/src/component/Router/Router.component.js
* Fixes #5164 
**Problem:**
* Shows 404 pages and some time oops page. Overall just typo on passing match from react router to routes.
* Fix typo for passing match to routes
=> issue-5164 - Fix typo for passing match to routes

packages/scandipwa/src/util/Request/Request.js
* Fixes https://github.com/scandipwa/scandipwa/issues/5181
**Problem:**
* `putPersistedQuery` wasn't ever called.
* Modified `executeGet` in `Request.js` to fixed logic for handling getFetch errors.
=> #5181 Fix `executeGet` logic for calling `putPersistedQuery`

packages/scandipwa/src/component/ProductList/ProductList.container.js
* Fixes scandipwa/scandipwa/issues/5152
**Problem:**
* After updating the page with infinite scrollbar, the scrollbar's thumb element's position wasn't updated. which also caused the page not to update it's state correctly
* After updating the page, we should scroll to the top. this will fix both issues
=>  [5152] Fixed infinite scroll on PLP

packages/scandipwa/src/component/CheckoutTermsAndConditionsPopup/CheckoutTermsAndConditionsPopup.component.js, packages/scandipwa/src/component/ImageZoomPopup/ImageZoomPopup.container.js, packages/scandipwa/src/component/MyAccountAddressPopup/MyAccountAddressPopup.component.js, packages/scandipwa/src/component/MyAccountCustomerPopup/MyAccountCustomerPopup.component.js, packages/scandipwa/src/component/NewVersionPopup/NewVersionPopup.component.js, packages/scandipwa/src/component/Popup/Popup.component.js, packages/scandipwa/src/component/Popup/Popup.container.js, packages/scandipwa/src/component/ShareWishlistPopup/ShareWishlistPopup.component.js, packages/scandipwa/src/component/StoreInPickUpPopup/StoreInPickUpPopup.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4870
**Problem:**
* `clickOutside` prop not working, because it was missing in `containerProps`
* Added missing prop
=> [4870] Added missing clickOutside prop

packages/scandipwa/src/component/CategoryDetails/CategoryDetails.style.scss
=> issue-5245 - Adjust description text break for category description

packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.container.tsx
* Fixes [5197 Never-ending loader appears when opening order page without order id](https://github.com/scandipwa/scandipwa/issues/5197)
* Added redirect to order history when opening order page without order ID.
=> 5197 Added redirect to order history

packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.container.tsx
* Fixes https://github.com/scandipwa/scandipwa/issues/5359
**Problem:**
* `shippingMethod` was saved instead of `shipping_method`, so `shipping_method` would always be undefined in `Checkout.container`
* renamed variable
=> Fixed incorrect `shippingMethod` reference in `CheckoutShipping.container`

packages/scandipwa/src/query/Config.query.ts, packages/scandipwa/src/query/Config.type.ts, packages/scandipwa/src/query/ProductList.query.ts, packages/scandipwa/src/route/CategoryPage/CategoryPage.container.tsx, packages/scandipwa/src/route/CategoryPage/CategoryPage.type.ts
* Fixes #5354.
**Problem:**
* PLP didn't use default global sort by if category default sort was not defined.
* Used global default sort by for categories without defined sort by.
=> 5354 Added option to use global default sort by on PLP

packages/scandipwa/src/query/Menu.query.ts, packages/scandipwa/src/query/Menu.type.ts, packages/scandipwa/src/query/UrlRewrites.query.ts, packages/scandipwa/src/query/UrlRewrites.type.ts, packages/scandipwa/src/route/CategoryPage/CategoryPage.component.tsx, packages/scandipwa/src/route/CategoryPage/CategoryPage.container.tsx, packages/scandipwa/src/route/CategoryPage/CategoryPage.type.ts, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.component.tsx, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.container.tsx, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.type.ts, packages/scandipwa/src/util/History/History.type.ts, packages/scandipwa/src/util/Menu/Menu.ts, packages/scandipwa/src/util/Menu/Menu.type.ts
Fixes #5334.
Issue: category page was showing incorrect placeholders for static content only.
In this PR: added displayMode to menu items to load correct placeholders.
=> Fixed category page placeholders

packages/m2-theme/public/index.php, packages/scandipwa/src/type/Global.type.ts, packages/scandipwa/src/util/Currency/Currency.ts
* Fixes #5355.
**Problem:**
* If USD was removed from allowed store currencies, user could see an error on the first website load.
* [Added current store currency to window variables](https://github.com/scandipwa/customization/pull/34).
* Used default currency from window variables.
=> Added storeCurrency to window

packages/scandipwa/src/component/Breadcrumbs/Breadcrumbs.style.scss, packages/scandipwa/src/component/DemoNotice/DemoNotice.style.scss, packages/scandipwa/src/component/Header/Header.style.scss, packages/scandipwa/src/component/Menu/Menu.style.scss, packages/scandipwa/src/component/OfflineNotice/OfflineNotice.style.scss, packages/scandipwa/src/component/Router/Router.component.tsx, packages/scandipwa/src/component/Router/Router.style.scss, packages/scandipwa/src/style/base/_root.scss
**Problem:**
* Fixed jumping header on initial load
* Fallback for the BEFORE_ITEMS, which include a placeholder for the header and breadcrumbs, based on their total height
* Moved root variables to the root.scss to have them available initially
* Removed duplicates of root variables
* Fixes for breadcrumbs height
=> Performance jumping header and breadcrumbs fix

packages/scandipwa/src/component/TranslateOnCursorMove/TranslateOnCursorMove.component.tsx
* Fixes https://github.com/scandipwa/scandipwa/issues/5405
**Problem:**
* Zoomed image is not shown in popup
* Moved `handleLoad` usage from `onLoad` attribute value of `.TranslateOnCursorMove` element to `componentDidMount` method because `componentDidMount` is called after the component is mounted (inserted into the tree) which is similar to `onLoad` behavior.
=> ISSUE-5405 - solve image is not shown on pop-up

packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.container.tsx
* Fixes [[link for issue](https://scandiflow.atlassian.net/browse/TEAMS-851)]
**Problem:**
* MyAccount icons doesn't open with first click
* removed the unnecessary toggle at component mounting
=> TEAMS-851 - removed redundant action on myAccountOverlay mounting

packages/scandipwa/src/component/ProductGallery/ProductGallery.component.tsx, packages/scandipwa/src/component/ProductGallery/ProductGallery.style.scss
* Fixes [[link for issue](https://scandiflow.atlassian.net/browse/TEAMS-773)]
**Problem:**
* Product gallery blinks when going from PLP to PDP.
* Added an already loaded image from PLP until the product image loads in product Slider
=> TEAMS-773 - fixed PDP blinking when navigating from PLP to PDP

packages/scandipwa/src/route/UrlRewrites/UrlRewrites.component.tsx, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.container.tsx, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.type.ts, packages/scandipwa/src/store/ProductList/ProductList.dispatcher.ts
* Fixes [[link for issue](https://scandiflow.atlassian.net/browse/TEAMS-771)]
**Problem:**
* [product cards blinks when navigation between categories]
* [the issue was due to the sort_by value the has 2 possible values so instead of it used sort key coming from productList Reducer but this seems to fix the issue but not sure if this it provide the wanted value]
=> TEAMS-771 - remove blinking when navigation between categories

packages/scandipwa/src/route/UrlRewrites/UrlRewrites.container.tsx
* Fixes [[link for issue](https://scandiflow.atlassian.net/browse/TEAMS-860)]
**Problem:**
* "Products are loading..." label stays visible all the time although the products are loaded
=> TEAMS-860 - fixed issues with UrlRewrites initialization

packages/scandipwa/src/store/Wishlist/Wishlist.dispatcher.ts
* Fixes [[link for issue](https://scandiflow.atlassian.net/browse/TEAMS-878)]
**Problem:**
* Success message shown if user click on 'Add all to cart' in Wishlist, but there are no items which can be added to cart
* handled try catch block correctly to dispatch correct actions
=> TEAMS-878 - fixed wrong dispatched message

packages/scandipwa/src/component/Product/Product.component.tsx, packages/scandipwa/src/component/ProductActions/ProductActions.component.tsx, packages/scandipwa/src/component/ProductActions/ProductActions.container.tsx, packages/scandipwa/src/component/ProductPrice/ProductPrice.component.tsx
* Fixes https://scandiflow.atlassian.net/browse/TEAMS-582
**Problem:**
1. (Self-reported) Meta content is undefined for price by default:
2. The discounted product should have schema:
lowPrice - Discounted price value
highPrice - Original price value
Currently, highPrice just uses final price of product
* meta content price is not undefined anymore
* highPrice displays final price if product has no discounts or variants
* highPrice displays Original price value if product has variants or has discount
* lowPrice displays minimum(final price) of product if product has variants or has discount
=> TEAMS-582 update highPrice and lowPrice logic

packages/m2-theme/public/index.php, packages/scandipwa/public/index.html, packages/scandipwa/src/component/Meta/Meta.component.tsx, packages/scandipwa/src/component/Router/Router.container.tsx
* Fixes https://scandiflow.atlassian.net/browse/TEAMS-578
**Problem:**
* Flickering titles due to default titles being replaced with rendered titles. This caused double Titles registered and recurring SEO problems on projects.
* Default titles are removed, now only rendered titles will be used. Only one title will be rendered now.
=> TEAMS-578 fix flickering titles

packages/scandipwa/src/component/Router/Router.container.tsx, packages/scandipwa/src/component/Router/Router.type.ts, packages/scandipwa/src/route/CategoryPage/CategoryPage.container.tsx
* Fixes https://scandiflow.atlassian.net/browse/TEAMS-585
**Problem:**
* Category pages with page URL parameters didn't have self-canonical URLs. This caused search engines to treat the paginated pages as duplicate pages.
* [Self-reported] Sometimes, canonical URLs get deleted if navigating page with refresh, because router update overrides it
* Made canonical URL include page parameter for categories.
* Fixed issue with canonical being deleted by router update
=> TEAMS-585 Canonicals for paginated pages to be self-referencing

packages/scandipwa/src/component/ProductGallery/ProductGallery.component.tsx, packages/scandipwa/src/component/ProductGalleryThumbnailImage/ProductGalleryThumbnailImage.component.tsx, packages/scandipwa/src/component/ProductGalleryThumbnailImage/ProductGalleryThumbnailImage.type.ts
* Fixes https://scandiflow.atlassian.net/browse/TEAMS-584
**Problem:**
* Product Gallery component misses Alt for images, this caused SEO or even legal problems in some countries like US
* The recurring issue has to be fixed on each new project
* Product Gallery images will use Alt label or fallback to product name in case if alt is missing
=> TEAMS-584 Add alt to images for product gallery

packages/scandipwa/src/component/Menu/Menu.component.tsx, packages/scandipwa/src/component/Menu/Menu.style.scss
* Fixes https://scandiflow.atlassian.net/browse/TEAMS-586
**Problem:**
* Menu subitems are not rendered for bots, thus not providing good data for crawling. The recurring issue has to be fixed on each project.
* Menu subitems will be rendered for bots (but invisible), for users it will not be rendered if not hovered.
=> TEAMS-586 render menu for bots

packages/scandipwa/src/component/StoreItem/StoreItem.component.tsx, packages/scandipwa/src/component/StoreItem/StoreItem.container.tsx, packages/scandipwa/src/component/StoreItem/StoreItem.style.scss, packages/scandipwa/src/component/StoreItem/StoreItem.type.ts
* Fixes https://scandiflow.atlassian.net/browse/TEAMS-587
**Problem:**
* Storeswitcher is using Buttons instead of Links, which causes issues with website crawling and doesnt allow bots to find other stores, the recurring issue is fixed on projects
* Replaced buttons with links in storeswitcher
=> TEAMS-587 storeswitcher links

README.md, build-packages/csa-generator-blank/template/README.md, build-packages/csa-generator-cra/template/README.md, build-packages/csa-generator-theme/template/README.md
* Fixes #5176
**Problem:**
* There is a typo in README.md
* Change 'expirience' to 'experience'.
* Change 'Exlins' to 'Eslint'.
=> Fix typo in README template

packages/scandipwa/src/component/ProductGallery/ProductGallery.component.tsx, packages/scandipwa/src/component/ProductGalleryThumbnailImage/ProductGalleryThumbnailImage.component.tsx, packages/scandipwa/src/component/ProductGalleryThumbnailImage/ProductGalleryThumbnailImage.type.ts
* Fixes https://github.com/scandipwa/scandipwa/issues/5381
**Problem:**
* All product images have empty alt tags. From an SEO standpoint. All images should have alt tags,
* Added product name as a value for alt tag.
=> 5381 - Added alt tags to PDP images

packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.container.tsx, packages/scandipwa/src/route/CategoryPage/CategoryPage.container.tsx, packages/scandipwa/src/util/Preload/CategoryPreload.ts, packages/scandipwa/src/util/Url/Url.ts
* Fixes `category_uid` escape issue from the URL
**Problem:**
* `category_uid` can't be processed correctly because of incorrect escape of `=` signs.
* prevent the escape of `customFilters` param
=> TEAMS-920 - fix unnecessary escape for "customFilters"

packages/scandipwa/src/util/Url/Url.ts
* Fixes [TEAMS-905](https://scandiflow.atlassian.net/browse/TEAMS-905)
**Problem:**
* PLP breaks when there are multiple parameters in the URL which start with "?"
[TEAMS-905]: https://scandiflow.atlassian.net/browse/TEAMS-905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEAMS-905: fix query parameter from url
