package-lock.json, package.json, src/app/component/CategoriesList/CategoriesList.component.js, src/app/component/CategoryProductList/CategoryProductList.component.js, src/app/component/CategoryProductList/CategoryProductList.style.scss, src/app/route/CategoryPage/CategoryPage.component.js
=> Fixed infinite scroll bug. Removed react-visibility-sensor dependency.

src/sw/index.js
Fixes #8 
Added the '/' to Workbox pre-cache.
=> Added '/' to pre-cached routes.

src/app/component/Html/Html.component.js
=> Fixed image path being incorrectly replaced.

src/app/route/CmsPage/CmsPage.component.js, src/app/route/CmsPage/CmsPage.container.js
Fixed #3 : 
-Added enableBreadcrumbs funciton to cmsPage,
-Breadcrumbs are now always shown in CMS Pages
=> CMS-Breadcrumbs

src/app/component/ProductCard/ProductCard.component.js, src/app/component/ProductCard/ProductCard.style.scss, src/app/style/abstract/_abstract.scss, src/app/style/abstract/_button.scss, src/app/style/base/_button.scss
-Cart now shows correct configurable product when adding from product list
-Button now lands to product page if multiple variants were found
in product list
=> Product-Cart-Image:

src/app/component/CategoryProductList/CategoryProductList.component.js, src/app/component/Figure/Figure.component.js, src/app/component/Image/Image.component.js, src/app/component/ProductActions/ProductActions.component.js, src/app/component/ProductCard/ProductCard.component.js, src/app/component/Slider/Slider.component.js, src/app/type/ProductList.js
-Placeholders for PDP images are shown only when details are loading
-Placeholders no longer visible when switching configurable products
=> Remove-Placeholder-PDP

composer.json
Related to #39 Packagist link: https://packagist.org/packages/scandipwa/customer-graph-ql
=> Added composer dependency on scandipwa/customer-graph-ql

src/app/component/CartItem/CartItem.component.js, src/app/component/MiniCart/MiniCart.style.scss, src/app/component/ProductCard/ProductCard.component.js, src/app/route/CartPage/CartPage.style.scss, src/app/route/ProductPage/ProductPage.component.js, src/app/util/Url/Url.js, src/app/util/Url/index.js
-PDP links now point to configurable products
-Added search param to query in PDP and redirecting to PDP
-Changed empty MiniCart styling to be consistent
=> Preserve-Option-PDP

src/app/store/Category/Category.dispatcher.js, src/app/store/Product/Product.dispatcher.js
Category and product page was not showing 404.
- Implemented a fix to correct this issue
=> Fixed issue that 404 was not displayed for category and product page

src/app/component/Field/Field.component.js, src/app/component/Form/Form.component.js, src/app/component/Form/Form.config.js, src/app/component/Form/index.js
=> Implemented Form validation

src/app/component/Field/Field.component.js, src/app/component/Form/Form.component.js, src/app/component/MyAccount/MyAccount.component.js, src/app/store/MyAccount/MyAccount.dispatcher.js
Introduced functionality allows user to register an account.
=> My account create account

src/app/component/Image/Image.component.js, src/app/component/Image/Image.style.scss
- Added new keyframe to hide mask after the image is loaded.
- This PR fixes #68
=> Fix image loading on new android devices

src/app/component/Breadcrumbs/Breadcrumbs.style.scss
-Fixed sub-category breadcrumb color to awlays be gray
=> Wrong-Breadcrumb-Color

src/app/component/Field/Field.component.js, src/app/component/ProductActions/ProductActions.component.js
PDP input accepts non-integer values such as "e", "," and "."
=> PDP Input accepts wrong values

src/app/component/Loader/Loader.component.js, src/app/component/Loader/Loader.style.scss, src/app/component/Loader/index.js, src/app/component/MyAccount/MyAccount.component.js, src/app/component/MyAccount/MyAccount.style.scss, src/app/component/Notification/Notification.style.scss, src/app/query/MyAccount.query.js, src/app/route/PasswordChangePage/PasswordChangePage.component.js, src/app/route/PasswordChangePage/PasswordChangePage.container.js, src/app/route/PasswordChangePage/PasswordChangePage.style.scss, src/app/route/PasswordChangePage/index.js, src/app/route/index.js, src/app/store/MyAccount/MyAccount.dispatcher.js, src/app/store/MyAccount/MyAccount.reducer.js
When a user receives forgot password email and clicks the link he will be redirected to the Change Password screen, where he will be able to change his password. Token will be taken from URL.
This implements Change password functionality for #39
=> My account Change password

src/app/component/MyAccount/MyAccount.component.js, src/app/component/MyAccount/MyAccount.style.scss, src/app/style/abstract/_variables.scss
Changed all links to buttons and adjusted styles
=> Change links to buttons on My Account

src/app/component/Select/Select.component.js
-Removed unneeded code
-Fixed keyboard sort switching
=> Select-Sort-Keyboard

src/app/component/Breadcrumbs/Breadcrumbs.style.scss, src/app/component/CartItem/CartItem.style.scss, src/app/component/ProductActions/ProductActions.style.scss, src/app/component/ProductCard/ProductCard.style.scss, src/app/component/ProductDetails/ProductDetails.style.scss, src/app/component/RelatedProducts/RelatedProducts.style.scss, src/app/route/CartPage/CartPage.style.scss
-Fixed pdp related product styling
-Fixed product card padding on mobile/tablet
-Fixed pdp add to cart button height
-Added margin for PDP manufacturer
-Fixed cart page width styling
=> Frontend-styles

src/app/component/CartItem/CartItem.component.js, src/app/component/GroupedProductsItem/GroupedProductsItem.component.js, src/app/component/ProductCard/ProductCard.component.js, src/app/component/ProductGallery/ProductGallery.component.js, src/app/component/Slider/Slider.component.js, src/app/query/ProductList/ProductList.js, src/app/route/index.js
=> #97 Fix image path

src/app/component/GroupedProductsItem/GroupedProductsItem.component.js, src/app/component/GroupedProductsList/GroupedProductsList.component.js, src/app/component/GroupedProductsList/GroupedProductsList.container.js, src/app/component/GroupedProductsList/index.js, src/app/store/Product/Product.reducer.js
=> Fix grouped product persisted quantity

src/app/component/Slider/Slider.component.js, src/app/route/index.js
=> Fix for slider's animations and irrelevant focus on slide change

src/app/component/Image/Image.component.js, src/app/component/ProductGallery/ProductGallery.component.js, src/app/component/Slider/Slider.component.js, src/app/route/index.js, src/app/store/CmsBlocksAndSlider/CmsBlocksAndSlider.reducer.js
=> Allow absolute paths only in Image and slider routes fix

src/app/route/MyAccountDetails/MyAccountDetails.component.js, src/app/store/MyAccount/MyAccount.dispatcher.js
-User is now notified when incorrect old password is entered
-Added notification if new password does not match confirm password
Fixes: #129
=> My-Account-Passwords-Match

src/app/component/Select/Select.component.js, src/app/component/Select/Select.style.scss
Make native <select> element get rendered when user is using a phone or tablet to make it easier to interact with #88
=> Native select on mobile

src/app/query/Cart.query.js, src/app/store/Cart/Cart.dispatcher.js
-Changed naming convetion
-Added missing argument parameters
=> Add-To-Cart-Frontend

composer.json, src/app/component/ProductActions/ProductActions.component.js, src/app/component/ProductActions/ProductActions.style.scss, src/app/component/ProductCard/ProductCard.component.js, src/app/component/ProductCard/ProductCard.style.scss, src/app/component/ProductWishlistButton/ProductWishlistButton.component.js, src/app/component/ProductWishlistButton/ProductWishlistButton.container.js, src/app/component/ProductWishlistButton/ProductWishlistButton.style.scss, src/app/component/ProductWishlistButton/index.js, src/app/query/Wishlist.query.js, src/app/query/index.js, src/app/route/RouterTemplate/index.js, src/app/route/index.js, src/app/store/MyAccount/MyAccount.dispatcher.js, src/app/store/Wishlist/Wishlist.action.js, src/app/store/Wishlist/Wishlist.dispatcher.js, src/app/store/Wishlist/Wishlist.reducer.js, src/app/store/Wishlist/index.js, src/app/store/index.js
- Product Action and Product Card components modified to include Wishlist button
- Wishlist button styled simillary to Add to cart Button
- Added wishlist-graphql dependency
=> Added wishlist button functionality for PDP and PLP

src/app/component/CategoriesList/CategoriesList.component.js, src/app/query/Category.query.js, src/app/store/Breadcrumbs/Breadcrumbs.dispatcher.js
A possible improvement would be to move the `maxCategoryDepth` constant to some application level config
=> Adding support for more than two level deep category trees

src/app/component/CartSummary/CartSummary.componet.js, src/app/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js, src/app/component/MiniCart/MiniCart.component.js, src/app/component/ProductPrice/ProductPrice.component.js, src/app/query/Cart.query.js, src/app/util/Price/Price.js, src/app/util/Price/index.js
Removed hard-coded currencies from:
- ProductPrice
- CartSummary
- CheckoutOrdersSummary
Fixes #133
=> Added support for currencies

src/app/component/CartItem/CartItem.component.js, src/app/component/Field/Field.component.js, src/app/style/base/_input.scss
CarItem disable the minus button when 1.
=> Prevent qty input from decreasing when it reaches 1

src/app/component/CheckoutPreviewAndPaymentsStep/CheckoutPreviewAndPaymentsStep.component.js, src/app/component/CheckoutShippingStep/CheckoutShippingStep.component.js, src/app/component/Field/Field.component.js, src/app/component/Field/Field.style.scss, src/app/component/Form/Form.component.js, src/app/query/CheckEmail.query.js, src/app/query/index.js
1. Adding validation for telephone in checkout and in my account
2. Refactored `onChange` in `Field` component to the same approach as other `onSomething`
3. Added validation for if the email address is already registered in the back-end. Address check functionality is dependent on https://github.com/scandipwa/customer-graph-ql/pull/2
4. Noticed that email address is not present in `review-and-payments` checkout step, but component code had email in `fieldMap` definition list. Removed the dead code.
Comments and improvement ideas welcome :)
=> Adding additional validations

src/app/component/CheckoutShippingStep/CheckoutShippingStep.component.js
Fixed issue where region selector is available only after changing country
=> Initialize available regions in constructor

src/app/component/CartSummary/CartSummary.componet.js, src/app/component/CartSummary/CartSummary.style.scss, src/app/component/MiniCart/MiniCart.component.js, src/app/component/MiniCart/MiniCart.style.scss
Will prevent minicart link from redirecting user to `/cart` if there are no items in cart
Will not show link to checkout if there are no items in cart
Fixed issue with subtotal being `NaN` in minicart
=> Will not let users to cart and checkout with empty cart Issue #169

src/app/store/Wishlist/Wishlist.dispatcher.js
- Fixed wishlist undefined error when no data in wishlist
=> Added support for wishlist notification translations

src/app/query/ProductList.query.js, src/app/route/CategoryPage/CategoryPage.component.js, src/app/route/CategoryPage/CategoryPage.container.js, src/app/store/Category/Category.action.js, src/app/store/Category/Category.dispatcher.js, src/app/store/Category/Category.reducer.js
This functionality is dependent on https://github.com/scandipwa/catalog-graphql/pull/8
=> Adding dynamic limits for price ranges for category price filter

src/app/component/CheckoutShippingStep/CheckoutShippingStep.container.js, src/app/route/CheckoutPage/CheckoutPage.container.js, src/app/route/MyAccountDetails/MyAccountDetails.container.js
=> Updated Reducers

src/app/store/CmsBlocksAndSlider/CmsBlocksAndSlider.reducer.js, src/app/util/Request/Request.js
Reverts scandipwa/base-theme#219 due functionality failing the cart.
=> Revert "Fixed issue where menu and all cms blocks fail if one block is disabled"

composer.json, src/app/component/CheckoutShippingStep/CheckoutShippingStep.component.js, src/app/query/CheckEmail.query.js, src/app/query/MyAccount.query.js
removed hardcoded 2.3.2 version check, updated isEmailAvailable query to match new M2 GraphQL API
=> Upgrade to match Magento 2.3.2 

README.md, src/app/component/Link/Link.component.js, src/app/component/ProductGallery/ProductGallery.component.js, src/app/component/SearchOverlay/SearchOverlay.container.js, src/app/route/UrlRewrites/UrlRewrites.component.js, src/config/webmanifest.config.js
=> codacy fixes

src/app/component/CartSummary/CartSummary.componet.js
=> Fixed discount bug

src/app/component/CartItem/CartItem.style.scss, src/app/route/CartPage/CartPage.style.scss
- Fixed cart overlay action buttons display issue on before-desktop screen width
- On cart page fixed cart item action button alignment, overlay with item name
=> 2.0 cart overlay styling

src/app/component/MenuOverlay/MenuOverlay.component.js, src/app/store/SearchBar/SearchBar.reducer.js, src/app/style/abstract/_icons.scss
- Menu overlay "go back" button click fix
- "Clear search" button for mobile devices alignment fix
- Search bar overlay initial state change (now search placeholders appear immediately after the first click)
=> 2.0 menu items

src/app/component/ProductActions/ProductActions.style.scss, src/app/component/ProductPrice/ProductPrice.style.scss
Stylized price for products with discount
=> stylized price

src/app/component/CartItem/CartItem.component.js, src/app/component/ProductCard/ProductCard.component.js, src/app/component/ProductGallery/ProductGallery.component.js
Fixes Schema.org proptype="image" in ProductCard, CartItem and PDP ProductGallery
=> Fixes PDP schema image source issue

src/app/component/CartItem/CartItem.style.scss
- fixed alignment issues in cart-item price (CartPage)
=> fixed alignment issues in cart-item price

.eslintrc
Fixes https://github.com/scandipwa/base-theme/issues/131
=> Lint no bind

src/app/route/NoMatchHandler/NoMatchHandler.component.js
=> Fix scrolling issue when navigating back to CategoryPage

composer.json, src/app/component/CartCoupon/CartCoupon.component.js, src/app/component/CartCoupon/CartCoupon.container.js, src/app/component/CartCoupon/CartCoupon.style.scss, src/app/component/CartCoupon/index.js, src/app/component/CartOverlay/CartOverlay.component.js, src/app/component/CartOverlay/CartOverlay.style.scss, src/app/query/Cart.query.js, src/app/route/CartPage/CartPage.component.js, src/app/route/CartPage/CartPage.container.js, src/app/route/CartPage/CartPage.style.scss, src/app/store/Cart/Cart.action.js, src/app/store/Cart/Cart.dispatcher.js
Added functionality to apply and remove coupon codes.
The result is visible in Cart page and Cart overlay.
This functionality required changes in [scandipwa/quote-graphql](https://github.com/scandipwa/quote-graphql) repository. PR for it will be submitted soon.
=> Added support for coupons

src/app/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
Display Coupon code in checkout Order Summary
=> Display Coupon code in checkout Order Summary

src/app/component/ProductCard/ProductCard.container.js
Fix for https://github.com/scandipwa/base-theme/issues/227
=> Display configurable product image if variant thumbnail is missing in ProductCard

src/app/component/ProductActions/ProductActions.component.js
Fixes bug cause by https://github.com/scandipwa/base-theme/pull/304
=> Fixed error caused by displaying variant price on Product Description Page

src/app/component/AddToCart/AddToCart.container.js, src/app/component/ProductActions/ProductActions.container.js, src/app/query/ProductList.query.js, src/app/store/Breadcrumbs/Breadcrumbs.dispatcher.js, src/app/util/Media/Media.js
Fixes related to field optimization.
Related to https://github.com/scandipwa/catalog-graphql/pull/25
=> Optimization fixes

src/app/component/ProductList/ProductList.container.js
Implemented `debounce` methodology for Filters switching in order to prevent  DoS attacks on server that leads to more optimized response times.
=> Layered navigation - optimized loading time

src/app/component/SliderWidget/SliderWidget.component.js
Reverts scandipwa/base-theme#341
=> Revert "Fix the image path on the cms pages for the sliders"

src/app/component/MenuOverlay/MenuOverlay.component.js, src/app/util/Menu/Menu.js, src/app/util/Menu/index.js
- Remove side effects from Menu.getSortedItems, refactor to separate function + add docs
- In MenuOverlay, sort items before rendering
=> Menu sort order

src/app/component/MenuOverlay/MenuOverlay.component.js
There will be only one root category for menu items
=> Menu items can be enabled and disabled

src/app/query/MyAccount.query.js
Depends on:
https://github.com/scandipwa/customer-graph-ql/pull/5
https://github.com/scandipwa/quote-graphql/pull/14
=> Pass guest quote id along with a login request

src/app/component/MenuOverlay/MenuOverlay.component.js, src/app/component/MenuOverlay/MenuOverlay.style.scss, src/app/component/ProductAttributeValue/ProductAttributeValue.style.scss
line-height: 3.2rem is added because without image height shrinks, and its because current height holds the image with - 3.2rem height.
=> Menu manager missing image display.

src/app/component/MyAccountOrderPopup/MyAccountOrderPopup.container.js, src/app/component/ProductAttributeValue/ProductAttributeValue.style.scss
=> Security vulnerability in order detail.

composer.json, src/app/query/Category.query.js, src/app/route/CategoryPage/CategoryPage.container.js, src/app/store/Category/Category.reducer.js
* 404 page when category is disabled
Depends on https://github.com/scandipwa/catalog-graphql/pull/39
=> [SWPWA-370]  Category disabling support

src/app/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js
Shipping methods to be rounded up to second decimal
=> [SWPWA-386] Shipping methods to be rounded up to second decimal

src/app/query/ProductList.query.js, src/app/style/cms/block/homepage-category-preview.scss
fixed cross-sell product do not appear in cart
=> [SWPWA-395] fixed cross-sell product do not appear in cart

src/app/component/ProductGallery/ProductGallery.component.js
Now image slider resets when going to another PDP by decreasing transition time to 0
=> [SWPWA-429] Reset image slider on product switch

src/app/component/ProductGallery/ProductGallery.component.js, src/app/component/ProductGalleryBaseImage/ProductGalleryBaseImage.container.js
Now zoom resets when going to another PDP.
=> [SWPWA-428] Reset zoom when going to another PDP

src/app/route/index.js
=> Fix import of PasswordChangePage & SomethingWentWrong components

src/app/route/Checkout/Checkout.component.js
=> Fixed issues failing PRs

src/app/route/CategoryPage/CategoryPage.container.js
Now links on product attributes correspond to actual link of category with filters
=> Fix for product attribute link

src/app/route/MenuPage/MenuPage.container.js
Redirect to homepage when entering menu on desktop
=> Redirect to homepage when entering menu on desktop

src/app/style/abstract/_media.scss
=> Fix SCSS issue failing PRs

src/app/route/Checkout/Checkout.container.js
Bugfix for the issue:
No Shipping methods appear for logged in users without saved addresses.
=> No Shipping methods appear for logged in users without saved addresses

src/app/component/App/App.component.js, src/app/component/CategorySubcategories/CategorySubcategories.container.js, src/app/component/Header/Header.container.js, src/app/component/MyAccountOverlay/MyAccountOverlay.container.js, src/app/component/NavigationAbstract/NavigationAbstract.container.js, src/app/component/NavigationTabs/NavigationTabs.container.js, src/app/component/Router/Router.component.js, src/app/index.js, src/app/route/CartPage/CartPage.container.js, src/app/route/CmsPage/CmsPage.container.js, src/app/route/ProductPage/ProductPage.container.js, src/app/util/History/index.js
Return original extension import sequence in app initialization
Store history separately from App component
=> Fix circular dependencies causing issues in extensions

src/app/store/Cart/Cart.dispatcher.js
Fixed: https://github.com/scandipwa/base-theme/issues/644
=> #664 - Fixed update qty for cartpage

src/app/component/CartOverlay/CartOverlay.component.js, src/app/component/CartOverlay/CartOverlay.container.js, src/app/component/CategoryDetails/CategoryDetails.component.js, src/app/component/Draggable/Draggable.component.js, src/app/component/Header/Header.component.js, src/app/component/Header/Header.container.js, src/app/component/Header/Header.style.scss, src/app/component/NavigationAbstract/NavigationAbstract.container.js, src/app/component/SearchField/SearchField.style.scss, src/app/component/SearchOverlay/SearchOverlay.style.scss, src/app/component/Slider/Slider.component.js, src/app/route/SearchPage/SearchPage.container.js
-Fixed mobile bug where search results would overlap cart/login pages
CR & QA required before merge
=> PWA-628 Search field bugs

src/app/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js, src/app/route/Checkout/Checkout.component.js
Shipping Price Removed from checkoutOrderSummary on ShippingStep
=> Shipping Price Removed from checkoutOrderSummary on ShippingStep

extensions.json, scandipwa.json, src/config/FallbackPlugin/index.js, src/config/babel.config.js, src/config/loaders/extension-import-injector.js, src/config/webpack.development.config.js, src/config/webpack.extract-translations.config.js, src/config/webpack.production.config.js, src/config/webpack.sw.config.js
Allow parent theme custom path
Transform corresponding configs
=> Deprecate extensions.json

src/app/component/Header/Header.container.js
=> SWPWA-555 - fix for menu and customer account buttons not working

src/app/component/CartOverlay/CartOverlay.container.js, src/app/component/ProductList/ProductList.component.js
Fixes that when clicking, for example, on 2nd pagination link, then the url gets updated and items are loaded instead of showing loaders all the time
Fixes #609
=> SWPWA-554 - Category pagination

src/config/ExtensibleClasses/ExtensibleClass/index.js, src/config/ExtensibleClasses/ExtensibleComponent/index.js, src/config/ExtensibleClasses/ExtensiblePureComponent/index.js, src/config/ExtensibleClasses/ExtensibleUnstatedContainer/index.js, src/config/ExtensibleClasses/ProxyInstance.js, src/config/FallbackPlugin/index.js, src/config/Middleware/generateApplyHandler.js, src/config/Middleware/generateConstructHandler.js, src/config/Middleware/generateGetHandler.js, src/config/Middleware/generateMiddlewaredFunction.js, src/config/Middleware/index.js, src/config/Middleware/sortPlugins.js
Fix fallback plugin working incorrectly with plugins
Refactor extensibility logic: reuse handlers throughout the proxies
=> 3.0.0-beta.2 changes

src/app/util/Extensions/index.js, src/config/ExtensibleClasses/ProxyInstance.js, src/config/Middleware/generateApplyHandler.js, src/config/Middleware/generateConstructHandler.js, src/config/Middleware/generateGetHandler.js, src/config/Middleware/sortPlugins.js, src/config/webpack.development.config.js, src/config/webpack.extract-translations.config.js, src/config/webpack.production.config.js, src/config/webpack.sw.config.js
Simplify plugin type names
Fix context loss in get handler
Refactor configuration generator
Improve plugin sorting, describe in comment
Reference parent theme relative to a/d/f
=> 3.0.0-beta.3 changes

src/config/webpack.development.config.js, src/config/webpack.production.config.js
**Fixes**: #725, #686
**Depends on**: https://github.com/scandipwa/scandipwa-base/pull/106
=> Made URL and PATH to project dynamic

src/app/component/MyAccountOverlay/MyAccountOverlay.component.js
Translation of Label in  My Account Overlay
=> Translation of Label in  My Account Overlay

package-lock.json, package.json, src/app/component/SearchOverlay/SearchOverlay.container.js, src/app/route/index.js, src/config/webpack.core.config.js, src/config/webpack.production.config.js, src/config/webpack.sw.config.js
See release notes for more info
=> 2.14.2 - Build time optimization

.github/workflows/build-theme-v2.yml, .github/workflows/build-theme.yml
No `composer` interaction is necessary for V2. 
Expect to have it in V3-oriented pipelines.
=> Create a build pipeline

.github/workflows/build-theme-v3.yml
=> Create a pipeline for v3

src/app/route/CategoryPage/CategoryPage.container.js
Fixed loader loading behaviour.
=> Issue #698 fixed loader loading

src/app/component/Form/Form.config.js
Remove unnecessary password check from the frontend.
=> Issue #761 form validation fix

src/app/component/CategoryDetails/CategoryDetails.style.scss
Pull request for issue https://github.com/scandipwa/base-theme/issues/830 to allow multi-line category descriptions.
=> [BUGFIX] Multi-line category description

src/app/store/Meta/Meta.dispatcher.js
Show page title using product name, if meta_title not exist.
=> Added product page title fallback (to product name)

src/app/route/CartPage/CartPage.container.js
Now cart header on mobile can be translated!
=> [Issue #834] cart header translation fix

composer.json, src/app/component/CartItem/CartItem.component.js, src/app/component/CartItem/CartItem.container.js, src/app/component/CartItem/CartItem.style.scss, src/app/component/ProductActions/ProductActions.component.js, src/app/component/ProductActions/ProductActions.style.scss, src/app/component/ProductAttributeValue/ProductAttributeValue.style.scss, src/app/route/ProductPage/ProductPage.component.js, src/app/util/Product/Product.js
Now configurable products can have customizable options.
To apply this fix you'll need this [PR with fix for quote-graphql](https://github.com/scandipwa/quote-graphql/pull/37).
=> [Issue #840] configurable products fix

src/app/component/ProductCard/ProductCard.component.js, src/app/component/ProductCard/ProductCard.container.js, src/app/component/WishlistItem/WishlistItem.component.js
Fix #842 
Also improve situation with #985
=> The "as low as" price is shown without the discount

i18n/de_DE.json, src/app/component/TierPrices/TierPrices.component.js
=> [issue #798] fix tier price translation

src/app/component/MyAccountAddressBook/MyAccountAddressBook.container.js
=> [#901] My account address post-fixes are not translated.

src/app/component/ExpandableContent/ExpandableContent.component.js, src/app/component/NavigationTabs/NavigationTabs.component.js, src/app/component/ProductActions/ProductActions.component.js
=> [#903] "Write a review" button clips through the navigation menu

src/app/store/Cart/Cart.dispatcher.js, src/app/store/MyAccount/MyAccount.dispatcher.js
=> [#865] The current user cannot perform operations on cart

src/app/component/ExpandableContent/ExpandableContent.component.js, src/app/route/CartPage/CartPage.component.js
=> 903 fix clicking some expandable contents breaking the application 

src/app/component/CartOverlay/CartOverlay.container.js, src/app/component/CategorySubcategories/CategorySubcategories.container.js, src/app/component/Header/Header.container.js, src/app/component/MyAccountOverlay/MyAccountOverlay.container.js, src/app/component/SearchField/SearchField.component.js, src/app/route/Checkout/Checkout.component.js, src/app/route/Checkout/Checkout.container.js, src/app/route/MenuPage/MenuPage.container.js, src/app/route/MyAccount/MyAccount.container.js
Fix additional store code lacks
=> Fix links in my account not respecting store id in pathname

src/app/component/Menu/Menu.style.scss
=> Enable scroll for mobile subcategory list

src/app/component/Footer/Footer.component.js
Resolved duplicate footers #1009
**Description**:
Footer is showing two times. it should be one time
**Expected behavior**:
it should show one time
**Screenshots, Video, Logs**
**To Reproduce**:
only home page include it two times and the other pages it's look ok
**Versions**:
Magento 2.3.5-p2
scandipwa 3.1
=> Resolved duplicate footers #1009

src/app/component/CheckoutAddressForm/CheckoutAddressForm.component.js, src/app/component/CheckoutAddressForm/CheckoutAddressForm.container.js, src/app/component/CheckoutGuestForm/CheckoutGuestForm.component.js, src/app/component/CheckoutGuestForm/CheckoutGuestForm.container.js, src/app/component/CheckoutShipping/CheckoutShipping.component.js, src/app/component/CheckoutShipping/CheckoutShipping.container.js, src/app/route/Checkout/Checkout.component.js, src/app/route/Checkout/Checkout.container.js, src/app/store/Checkout/Checkout.action.js, src/app/store/Checkout/Checkout.reducer.js, src/app/store/index.js
- Remove legacy shipping/billing detection in guest form
- Fix not being able to go from billing to shipping
This resolves #795
=> Preserve state in checkout

src/app/component/Header/Header.config.js, src/app/component/Router/Router.component.js, src/app/component/Router/Router.container.js, src/app/route/NoMatch/NoMatch.component.js, src/app/route/NoMatch/NoMatch.container.js
NoMatchHandler is duplicating logic from url-rewrite so I removed it.
=> [Issue #926] no default 404 title fix

src/app/component/FieldSelect/FieldSelect.component.js, src/app/component/StoreSwitcher/StoreSwitcher.component.js
Removes placeholder from store select options.
=> [Issue #999] fix store select placeholder

src/app/component/Router/Router.container.js
=> fix meta_title error on plp

i18n/da_DK.json, i18n/de_DE.json, i18n/en_US.json, i18n/es_ES.json, i18n/fa_IR.json, i18n/fr_FR.json, i18n/it_IT.json, i18n/lv_LV.json, i18n/nb_NO.json, i18n/nl_NL.json, i18n/pl_PL.json, i18n/pt_BR.json, i18n/ru_RU.json, i18n/sl_SI.json, i18n/sv_SE.json, i18n/tr_TR.json, i18n/zh_TW.json, src/app/component/CartItem/CartItem.component.js, src/app/component/CartItem/CartItem.config.js, src/app/component/CartItem/CartItem.container.js, src/app/component/CartItem/CartItem.style.scss, src/app/component/CartOverlay/CartOverlay.component.js, src/app/component/CartOverlay/CartOverlay.container.js, src/app/component/CartOverlay/CartOverlay.style.scss, src/app/route/CartPage/CartPage.component.js, src/app/route/CartPage/CartPage.container.js, src/app/route/CartPage/CartPage.style.scss, src/app/util/Cart/Cart.js, src/app/util/Cart/index.js
If a product added to the cart becomes out of stock product will be marked as "Product is out of stock", grayscale filter applied to the image, and if the user tries to click "Secure checkout" it will show error notification.
Same on the Cart page.
=> [Issue #973] handle product is out of stock

src/app/component/MyAccountConfirmEmail/MyAccountConfirmEmail.component.js, src/app/component/MyAccountConfirmEmail/index.js, src/app/component/MyAccountCreateAccount/MyAccountCreateAccount.component.js, src/app/component/MyAccountCreateAccount/MyAccountCreateAccount.container.js, src/app/component/MyAccountCreateAccount/index.js, src/app/component/MyAccountForgotPassword/MyAccountForgotPassword.component.js, src/app/component/MyAccountForgotPassword/MyAccountForgotPassword.container.js, src/app/component/MyAccountForgotPassword/index.js, src/app/component/MyAccountForgotPasswordSuccess/MyAccountForgotPasswordSuccess.component.js, src/app/component/MyAccountForgotPasswordSuccess/index.js, src/app/component/MyAccountOverlay/MyAccountOverlay.component.js, src/app/component/MyAccountOverlay/MyAccountOverlay.container.js, src/app/component/MyAccountSignIn/MyAccountSignIn.component.js, src/app/component/MyAccountSignIn/MyAccountSignIn.container.js, src/app/component/MyAccountSignIn/index.js, src/app/type/Account.js
5 more components have been created from render functions in `MyAccountOverlay`:
- `MyAccountConfirmEmail`
- `MyAccountCreateAccount`
- `MyAccountForgotPassword`
- `MyAccountForgotPasswordSuccess`
- `MyAccountSignIn`
Now extension these components should be much easier.
=> [Feature #877] refactor myaccount component

src/app/component/ProductListPage/ProductListPage.style.scss
=> Add x padding on mobile for productlistpage

src/app/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js, src/app/route/CartPage/CartPage.component.js, src/app/route/Checkout/Checkout.component.js, src/app/route/Checkout/Checkout.style.scss
=> added discount code field to Payment method/Shipping step

src/app/component/ExpandableContent/ExpandableContent.component.js, src/app/component/Header/Header.component.js, src/app/component/NavigationTabs/NavigationTabs.component.js, src/app/component/ProductActions/ProductActions.component.js, src/app/route/CartPage/CartPage.component.js, src/app/util/CSS/CSS.js, src/app/util/CSS/index.js
[#1384 ] Added check if the content is bigger than the screen - other fixed elements, then scroll down that height.
=> [#1363] - ExpandableContent auto scrolling adjustments.

src/public/index.development.html, src/public/index.production.phtml
Tested on iPhone X via Browser stack. With this fix works.
=> SWPWA-1373 - Fix for IOS 12

src/app/component/CheckoutGuestForm/CheckoutGuestForm.component.js, src/app/component/CheckoutGuestForm/CheckoutGuestForm.container.js, src/app/component/CheckoutGuestForm/CheckoutGuestForm.style.scss, src/app/component/MyAccountSignIn/MyAccountSignIn.component.js, src/app/component/MyAccountSignIn/MyAccountSignIn.container.js, src/app/route/Checkout/Checkout.config.js, src/app/route/Checkout/Checkout.container.js, src/app/store/Checkout/Checkout.action.js, src/app/store/Checkout/Checkout.dispatcher.js, src/app/store/Checkout/Checkout.reducer.js
Now if user email is recognized there will be sign-in form in checkout.
=> [Feature #923] email recognition in checkout

src/app/component/ProductAttributeValue/ProductAttributeValue.component.js, src/app/component/ProductAttributeValue/ProductAttributeValue.config.js
=> SWPWA-967 - Color swatch fix

src/app/component/CategoryConfigurableAttributes/CategoryConfigurableAttributes.component.js, src/app/component/ExpandableContentShowMore/ExpandableContentShowMore.component.js, src/app/component/ExpandableContentShowMore/ExpandableContentShowMore.container.js, src/app/component/ExpandableContentShowMore/ExpandableContentShowMore.style.scss, src/app/component/ExpandableContentShowMore/index.js
Created ExpandableContentShowMore component, which allows to handle show more functionality.
=> SWPWA-1388 - PLP Show more functionality

src/app/component/Footer/Footer.style.scss, src/app/component/Header/Header.style.scss, src/app/route/CartPage/CartPage.style.scss, src/app/style/base/_reset.scss
- Fix screen heights.
*Should think of global/dynamic solutions, otherwise cant make those fixed elements dynamic and screen heights are hardcoded depending on fixed elements.
=> SWPWA-1438 - Mobile page layout fix on mobile app

src/app/component/Field/Field.component.js, src/app/component/Field/Field.style.scss, src/app/component/Header/Header.component.js, src/app/component/Header/Header.config.js, src/app/component/Header/Header.container.js, src/app/component/Header/Header.style.scss, src/app/component/Menu/Menu.component.js, src/app/component/MyAccountMyWishlist/MyAccountMyWishlist.component.js, src/app/component/MyAccountMyWishlist/MyAccountMyWishlist.container.js, src/app/component/MyAccountMyWishlist/MyAccountMyWishlist.style.scss, src/app/component/NavigationAbstract/NavigationAbstract.component.js, src/app/component/ProductCard/ProductCard.component.js, src/app/component/SwipeToDelete/SwipeToDelete.component.js, src/app/component/SwipeToDelete/SwipeToDelete.config.js, src/app/component/SwipeToDelete/SwipeToDelete.container.js, src/app/component/SwipeToDelete/SwipeToDelete.style.scss, src/app/component/SwipeToDelete/index.js, src/app/component/WishlistItem/WishlistItem.component.js, src/app/component/WishlistItem/WishlistItem.container.js, src/app/component/WishlistItem/WishlistItem.style.scss, src/app/route/MyAccount/MyAccount.component.js, src/app/route/MyAccount/MyAccount.container.js, src/app/route/MyAccount/MyAccount.style.scss, src/app/store/Wishlist/Wishlist.dispatcher.js, src/app/style/abstract/_icons.scss, src/app/style/base/_input.scss
Created the SwipeToDelete component, which allows having swipe action on mobile.
Styled input number field, when mod={ style: 'inline' } passed.
Added option to header to disableElements ( header buttons ).
Added option to header shouldNotGoToPrevState to avoid going back to prevstate for buttons that have by default it.
Adjusted header logic for MyAccount, added option to changeHeaderState depending on the current myaccount tab.
Redesigned Wishlist.
=> SWPWA-1428 - Wishlist redesign

src/app/component/SliderWidget/SliderWidget.component.js, src/app/component/SliderWidget/SliderWidget.container.js, src/app/query/Slider.query.js
Auto-scroll functionality for slider.
If in BE slide speed on slider is set to 0 then no auto-scroll. (default)
If > 0 then activate scroll functionality.
=> SWPWA-1440 - Add auto-scroll functional for slider

src/app/component/CategoryConfigurableAttributes/CategoryConfigurableAttributes.component.js
do not call function inside __() or the proxy will fail fouding the correct function definition
follow up to https://github.com/scandipwa/base-theme/issues/1330 and https://github.com/scandipwa/base-theme/pull/1331
=> fix formatPrice undefined

src/app/component/ProductReviewItem/ProductReviewItem.component.js, src/app/component/ProductReviewItem/ProductReviewItem.style.scss, src/app/component/ProductReviewItem/index.js, src/app/component/ProductReviewList/ProductReviewList.component.js, src/app/component/ProductReviewList/ProductReviewList.style.scss
I simply split the code up in 2 components for easier override, none new function or renders has been made.
=> Splitted up Product Review List for easier override

README.md
=> Removed README branch badges

src/app/component/Header/Header.container.js, src/app/component/MyAccountOverlay/MyAccountOverlay.container.js, src/app/component/MyAccountTabList/MyAccountTabList.component.js, src/app/store/MyAccount/MyAccount.action.js, src/app/store/MyAccount/MyAccount.dispatcher.js, src/app/store/MyAccount/MyAccount.reducer.js, src/app/util/Auth/Token.js
- When auth token expires and user press account button or any tab-item in account dashboard - forces user logout.
- If same action is performed but auth token is not expired - refreshes auth token.
- Added "Your session is over, you are logged out!" notification.
Issue #1549
=> Issue #1549 fix

src/app/component/CheckoutGuestForm/CheckoutGuestForm.component.js, src/app/component/MyAccountSignIn/MyAccountSignIn.component.js, src/app/component/MyAccountSignIn/MyAccountSignIn.container.js, src/app/route/Checkout/Checkout.container.js, src/app/store/Checkout/Checkout.dispatcher.js
=> Issue #1572 fix

src/app/route/CmsPage/CmsPage.style.scss, src/app/style/base/_list.scss
Fixed multiple nesting ul ol lists.
Added more space for lists in CmsPage-Content
=> Patch of <ul> and <ol> behavior (style)

src/app/component/Header/Header.component.js, src/app/component/Header/Header.style.scss
#1608 Fixed display of edit button in header on desktop layout
=> Fixed display of edit button in header on desktop layout

src/app/component/Field/Field.container.js
Fix issue #1359 (newsletter subscription save)
=> Issue #1359 fix

src/app/component/CheckoutGuestForm/CheckoutGuestForm.component.js, src/app/component/CheckoutShipping/CheckoutShipping.component.js, src/app/route/Checkout/Checkout.container.js, src/app/store/Checkout/Checkout.dispatcher.js
Issue #1589 fix
Uncaught promise err fix in guest form
=> Issue #1589 fix

src/app/component/ExpandableContentShowMore/ExpandableContentShowMore.component.js, src/app/component/ExpandableContentShowMore/ExpandableContentShowMore.style.scss, src/app/component/ProductConfigurableAttributes/ProductConfigurableAttributes.style.scss
Feature #1462 implementation offer
=> Feature #1462

src/app/component/MyAccountSignIn/MyAccountSignIn.component.js
This issue appear when guest at first writes existing email into create account form and appears login form where autocomplete for email input set on. Seems that some browsers prefills into it after user full delete email and it goes endless so that login form can't be closed.
=> SWPWA-1682

composer.json, src/app/component/CartOverlay/CartOverlay.container.js, src/app/component/CurrencySwitcher/CurrencySwitcher.component.js, src/app/component/CurrencySwitcher/CurrencySwitcher.container.js, src/app/component/CurrencySwitcher/CurrencySwitcher.style.scss, src/app/component/CurrencySwitcher/index.js, src/app/component/Header/Header.component.js, src/app/component/Menu/Menu.component.js, src/app/component/StoreSwitcher/StoreSwitcher.style.scss, src/app/query/Config.query.js, src/app/store/Config/Config.dispatcher.js, src/app/store/Config/Config.reducer.js, src/app/util/Currency/Currency.js, src/app/util/Currency/index.js, src/app/util/Request/Request.js
To add support for Currency Switcher, some resolvers where created so please check PR first: https://github.com/scandipwa/catalog-graphql/pull/75
- Add support for Currency Switcher in ScandiPwa
=> #433 Currency Switcher Support in ScandiPwa

src/app/route/CmsPage/CmsPage.container.js
Added meta-description for CMS pages
Original issue: #1563
=> #1563 CMS page meta-description

src/app/component/DemoNotice/DemoNotice.component.js, src/app/component/SwipeToDelete/SwipeToDelete.style.scss
=> Issue 1678 fix

src/app/query/Category.query.js, src/app/route/CategoryPage/CategoryPage.component.js, src/app/route/CategoryPage/CategoryPage.config.js, src/app/route/CategoryPage/CategoryPage.style.scss, src/app/type/Category.js
Added ablity to switch category contents display mode
=> Categories Display Mode / M2 Support

src/app/component/CartOverlay/CartOverlay.component.js, src/app/component/CartOverlay/CartOverlay.style.scss
Reverts scandipwa/base-theme#1730
Wrong base branch in the intial PR
=> Revert "SWPWA-1630 - Empty mini-cart redesign"

src/app/query/Category.query.js, src/app/route/CategoryPage/CategoryPage.component.js, src/app/route/CategoryPage/CategoryPage.config.js, src/app/route/CategoryPage/CategoryPage.style.scss, src/app/type/Category.js
Reverts scandipwa/base-theme#1721
Wrong inital PR's base branch
=> Revert "Categories Display Mode / M2 Support"

src/app/component/CheckoutPayments/CheckoutPayments.container.js, src/app/util/Braintree/Braintree.js
* https://github.com/scandipwa/quote-graphql/pull/47
When enabling 3D security braintree returns error.
Added necessary extra fields for braintree API to enable 3D security.
=> #1024 3d security support for braintree

src/app/route/CategoryPage/CategoryPage.component.js
See #1526
Added check if display mode is null.
=> Category Display Mode Fix

src/app/component/Footer/Footer.component.js, src/app/component/Footer/Footer.config.js, src/app/component/Footer/Footer.style.scss
Fixes #1398
Added ability to display newsletter subcription component if footer contents comes from the cms.
=> Newsletter in the footer if cms block is visible

src/app/component/ProductGallery/ProductGallery.component.js, src/app/component/Slider/Slider.component.js
=> Fixed single product image zoom

src/app/component/MyAccountAddressTable/MyAccountAddressTable.container.js
Fixes #1806
Fixed order details crashing issue when shipping address did not have a region.
=> Order details crashing issue

src/app/component/MyAccountOrderPopup/MyAccountOrderPopup.container.js, src/app/store/Popup/Popup.reducer.js
Fixes #1808
Fixed order details popup loading state
=> Never-ending loader in order details popup

src/app/route/ContactPage/ContactPage.style.scss
=> Add margin contact page

src/app/component/Header/Header.component.js, src/app/component/Header/Header.config.js, src/app/component/Header/Header.container.js, src/app/route/Checkout/Checkout.component.js
=> Issue 1802 fix

src/app/component/Header/Header.container.js
=> Issue #1694 fix

src/app/component/CookiePopup/CookiePopup.style.scss
Mobile: Can’t see menu if user didn't agree with privacy policy and T&C
=> Bug 1677 - Mobile: Can’t see menu if user didn't agree with privacy policy and T&C

src/app/component/Popup/Popup.style.scss
Mobile:Firefox: Button 'Submit review' is missing on write review page
=> Bug 1670 - Mobile:Firefox: Button 'Submit review' is missing on write review page

src/app/component/ProductGallery/ProductGallery.component.js, src/app/component/Slider/Slider.component.js, src/app/component/Slider/Slider.config.js, src/app/component/Slider/Slider.style.scss, src/app/component/SliderWidget/SliderWidget.component.js, src/app/component/SliderWidget/SliderWidget.container.js, src/app/component/SliderWidget/SliderWidget.style.scss
- Infinite home page slider if >=2 slides. 
- Part of next and previous slides is visible on mobile.
- Work both with vertical and horizontal mode.
- Posibility to change to not infinite with one line.
=> Mobile slider redesign

src/app/style/abstract/_icons.scss, src/app/style/abstract/_media.scss
The delete button in mini cart was looking broken due to strange behavior of box-shadow in mozilla (the top part was comming down and hiding the horizontal line)
=> Firefox (Win): Delete icon looks broken in mini-cart #1698

src/app/query/Wishlist.query.js
=> Wishlist Item Query Fix

src/app/component/InstallPrompt/InstallPrompt.style.scss
Removed CMS page margin when InstallPrompt is present.
=> Removed margin from Install Prompt

src/app/component/CartItem/CartItem.style.scss
Fixes #1873
Fixed product quantity control position in the minicart.
=> Product quantity control in minicart

packages/scandipwa/src/component/CategoryProductList/CategoryProductList.style.scss, packages/scandipwa/src/component/Header/Header.style.scss, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss, packages/scandipwa/src/component/ProductList/ProductList.style.scss
Reverts scandipwa/scandipwa#1913
=> Revert "fix: bugs"

src/app/component/NewProducts/NewProducts.component.js, src/app/component/NewProducts/NewProducts.container.js, src/app/component/ProductAttributeValue/ProductAttributeValue.component.js, src/app/component/ProductCard/ProductCard.component.js, src/app/component/ProductCard/ProductCard.style.scss, src/app/component/ProductLinks/ProductLinks.component.js, src/app/component/ProductLinks/ProductLinks.container.js, src/app/component/ProductListPage/ProductListPage.component.js, src/app/component/RecentlyViewedWidget/RecentlyViewedWidget.component.js, src/app/component/RecentlyViewedWidget/RecentlyViewedWidget.container.js
Aligned product card elements horizontally according to position of appropriate elements in other cards in grid.
=> Fixed product cards display issue

src/app/component/Slider/Slider.config.js, src/app/component/Slider/Slider.style.scss, src/app/component/SliderWidget/SliderWidget.component.js
Reverted slider animation speed.
Reverted slider crumbs display settings.
Hid slider crumbs on home page mobile layout using  prop.
=> Slider animation and crumbs display issues

packages/scandipwa/composer.json, packages/scandipwa/package.json
=> Composer Dependencies

packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js, packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.style.scss
Fixes #1628
Fixed shipping price display on shipping and billing pages.
=> Shipping Price Display on Checkout

packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
=> issue #1762 grouped product '+' and '-' now appears inside box

packages/scandipwa/src/component/ProductGallery/ProductGallery.component.js
Fixes #1648
Fixed page crash when navigation to PDP was made from minicart
=> PDP Crash From Minicart

packages/scandipwa/src/component/Menu/Menu.component.js, packages/scandipwa/src/component/Menu/Menu.style.scss
Fixes #1825 
repeat for github.com/scandipwa/scandipwa/pull/1870 , recreated PR because old has problem with branch and tries to replace items in master with same.
=> #1825 hide on desktop class

packages/scandipwa/src/store/Meta/Meta.dispatcher.js
=> Fix typo with meta_keywords for categories

packages/scandipwa/src/component/CartOverlay/CartOverlay.component.js, packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js, packages/scandipwa/src/query/Cart.query.js, packages/scandipwa/src/route/CartPage/CartPage.component.js, packages/scandipwa/src/route/CartPage/CartPage.container.js
Fixes #1796
Shipping tax is subtracted from the taxes until we select the shipping method
Related PR
scandipwa/quote-graphql/pull/53
=> Shipping Tax Display

packages/scandipwa/src/component/CategoryProductList/CategoryProductList.style.scss, packages/scandipwa/src/component/Header/Header.style.scss, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss, packages/scandipwa/src/component/ProductList/ProductList.style.scss
1.Removed min-size:100vw in CategoryProductList, ProductList #1737
2.Add to ProductActions-AttributesWrapper z-index:2 #1846
3.On Header-Button_type_share removed padding and border in mobile #1734
=> Reworked: styles of ProductList, Share Button, AttributesWrapper

packages/scandipwa/src/component/CartItem/CartItem.style.scss, packages/scandipwa/src/component/ProductCard/ProductCard.style.scss, packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss, packages/scandipwa/src/route/CartPage/CartPage.component.js
1.Added styles on after-mobile
1.1.Removed paddings.
1.2.Limited item heading.#1921
1.3.Layout reworked with grid.
2.Removed isEditing mod from isLikeTable mods elements.
=> Reworked CartItem, WishlistItme element styles. 

packages/scandipwa/src/component/CartItem/CartItem.container.js, packages/scandipwa/src/component/SwipeToDelete/SwipeToDelete.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js
fixes #1969 
Add loader when removing item with SwipeToDelete
=> Add loader for SwipeToDelete

packages/scandipwa/src/component/AddToCart/AddToCart.container.js
fixes #1782 
Default magento has ability to add products from grouped product without rule to select each product.
=> Change grouped product validation

packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.style.scss
1.Removed max-width on mobile
#1862
=>  Fix on ProductCustomizableOptions

packages/scandipwa/src/component/CartItem/CartItem.component.js, packages/scandipwa/src/component/CartItem/CartItem.style.scss, packages/scandipwa/src/component/CartOverlay/CartOverlay.style.scss, packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.style.scss, packages/scandipwa/src/component/Header/Header.style.scss, packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.component.js, packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.style.scss, packages/scandipwa/src/component/Notification/Notification.style.scss, packages/scandipwa/src/component/ProductCard/ProductCard.style.scss, packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss, packages/scandipwa/src/component/TierPrices/TierPrices.style.scss, packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss, packages/scandipwa/src/route/CartPage/CartPage.component.js, packages/scandipwa/src/route/CartPage/CartPage.style.scss, packages/scandipwa/src/style/abstract/_icons.scss, packages/scandipwa/src/style/base/_reset.scss
fixes #1984 
fixes #1983 
Get back old styles and restyle it a bit to be more responsive on tablet (Cart Page table)
=> Restyle CarItems and CartPage table

packages/scandipwa/src/component/Header/Header.component.js, packages/scandipwa/src/component/Header/Header.style.scss, packages/scandipwa/src/component/Menu/Menu.style.scss, packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.style.scss, packages/scandipwa/src/component/ProductCompare/ProductCompare.component.js, packages/scandipwa/src/component/ProductCompare/ProductCompare.style.scss, packages/scandipwa/src/component/ProductCompareAttributeRow/ProductCompareAttributeRow.style.scss, packages/scandipwa/src/component/ProductCompareButton/ProductCompareButton.component.js, packages/scandipwa/src/component/ProductCompareButton/ProductCompareButton.container.js, packages/scandipwa/src/component/ProductCompareButton/ProductCompareButton.style.scss, packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js, packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.container.js, packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.style.scss, packages/scandipwa/src/component/SharedWishlistItem/SharedWishlistItem.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/query/ProductCompare.query.js, packages/scandipwa/src/style/abstract/_icons.scss
Fixes #1980
Fixed compare page UI issues
=> Compare Page UI Fixes

packages/scandipwa/src/component/RecentlyViewedWidget/RecentlyViewedWidget.container.js
=> Fix recently viewed products widget

packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
#1938 
Scrollbar on windows browsers stay hidden
=> #1938 scrollbar on windows is hidden

packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.component.js
#1950 
Prices by checkmark now display with the discount applied
=> #1950: price with discount is displayed

packages/scandipwa/src/route/CartPage/CartPage.container.js
Fixed - https://github.com/scandipwa/scandipwa/issues/1843
=> #1843 - Fixed Product Count

packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.container.js, packages/scandipwa/src/component/ProductCard/ProductCard.style.scss, packages/scandipwa/src/component/ProductCompareButton/ProductCompareButton.component.js, packages/scandipwa/src/component/ProductCompareButton/ProductCompareButton.container.js, packages/scandipwa/src/component/ProductCompareButton/ProductCompareButton.style.scss, packages/scandipwa/src/component/Router/Router.container.js, packages/scandipwa/src/query/ProductCompare.query.js, packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js, packages/scandipwa/src/store/ProductCompare/ProductCompare.action.js, packages/scandipwa/src/store/ProductCompare/ProductCompare.dispatcher.js, packages/scandipwa/src/store/ProductCompare/ProductCompare.reducer.js, packages/scandipwa/src/style/abstract/_icons.scss
Added persistence for the Add to Compare Button state.
=> Persistent Compare Button State

packages/scandipwa/src/component/ProductCompare/ProductCompare.style.scss, packages/scandipwa/src/component/ProductCompareAttributeRow/ProductCompareAttributeRow.style.scss
Fixes #2004
Fixed sticky element display when main menu is open
=> Compare Page Sticky Labels

packages/scandipwa/src/route/MyAccount/MyAccount.container.js
=> SWPWA-1724 - Mobile: Button 'Ok' changes to 'Edit' in edit mode if user removed product from Wishlist

packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.component.js, packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.container.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js
Fixed https://github.com/scandipwa/scandipwa/issues/2016
=> #2016 - Fixed loader when deleting items from wishlist

packages/scandipwa/src/component/ProductActions/ProductActions.container.js, packages/scandipwa/src/component/ProductBundleItems/ProductBundleItems.container.js, packages/scandipwa/src/route/ProductPage/ProductPage.component.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js
Fixes #2003
Fixed bundle product excluding tax price display
=> Bundled product price

packages/scandipwa/src/store/NewsletterSubscription/NewsletterSubscription.dispatcher.js
=> #2024 - Changed the Newsletter Subscription's success notification message

packages/scandipwa/src/component/ProductCompare/ProductCompare.config.js, packages/scandipwa/src/component/ProductCompare/ProductCompare.container.js
Fixes #1999
Fixed comparable attribute values.
=> Comparable Attribute Values

packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js, packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.style.scss, packages/scandipwa/src/component/ShareWishlistPopup/ShareWishlistPopup.container.js
Fixes #2061
Fixed add to cart button appearance on compare page on mobile layout.
Fixed share wishlist popup translation issue that crashed project start
=> Add To Cart Button In Compare Page

packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.container.js, packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.container.js, packages/scandipwa/src/route/Checkout/Checkout.container.js
Fixes #1809
Fixed checkout duplicate address issue.
Relatad PR:
scandipwa/quote-graphql/pull/55
=> Checkout Duplicate Address

packages/scandipwa/src/component/CartOverlay/CartOverlay.container.js
Fixes #2088
Fixed cartDisplayConfig typo.
=> Zero Tax Display

packages/m2-theme/package.json
=> Update webpack-fallback-plugin to prevent breaking version mismatch

packages/scandipwa/src/component/CartOverlay/CartOverlay.component.js, packages/scandipwa/src/route/CartPage/CartPage.component.js
Fixes #2020
Added check in order to hide zero discount.
=> Zero Discount

packages/scandipwa/src/util/Auth/Token.js, packages/scandipwa/src/util/Cart/Token.js
Fixes #1498
Added cookie lifetime setting to the auth token.
=> Cookie Lifetime Auth Token

packages/scandipwa/src/route/NoMatchHandler/NoMatchHandler.component.js, packages/scandipwa/src/route/ProductPage/ProductPage.component.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js
Fixes #2098
Fixed product page endless loading when product is missing in the response
=> Product Page Endless Loading

packages/scandipwa/src/component/ProductList/ProductList.container.js
Fixes #2177
Removed filters data request from product list component, if it is rendered as a widget.
=> Product List Widget

packages/scandipwa/src/component/Field/Field.container.js, packages/scandipwa/src/component/Form/Form.component.js
=> SWPWA-2153 - Field validation is missing

packages/scandipwa/src/component/App/App.component.js, packages/scandipwa/src/store/index.js, packages/scandipwa/src/util/Auth/Token.js, packages/scandipwa/src/util/Media/Media.js, packages/scandipwa/src/util/Store/index.js, packages/scandipwa/src/util/Url/Url.js
Replacement for https://github.com/scandipwa/scandipwa/pull/2203
Resolves #2018
=> IoC store logic in order to prevent circular deps

packages/scandipwa/src/component/Popup/Popup.component.js
=> issue-2227 - Fix popup header titles

packages/scandipwa/src/route/CartPage/CartPage.container.js
=> Fix ooops page on first website->cart visit

packages/scandipwa/src/component/Field/Field.component.js, packages/scandipwa/src/component/Field/Field.container.js, packages/scandipwa/src/component/NewsletterSubscription/NewsletterSubscription.component.js, packages/scandipwa/src/component/NewsletterSubscription/NewsletterSubscription.container.js, packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.component.js, packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.container.js, packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.style.scss, packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
Fixes #2085
Fixed account confirmation form validation.
Fixed account confirmation form submission steps on failure.
Fixed field invalid prop type error from the console.
=> Account Confirmation Form Validation And Submission

packages/scandipwa/src/component/CategoryDetails/CategoryDetails.component.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
Original issue: #2216 
In this PR:
* Added placeholders while category is still loading.
=> #2216 Category description show placeholders

packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.container.js, packages/scandipwa/src/query/Config.query.js
Fixes #1496 
Added check whether customer should be redirected to the dashboard page after login.
Additional PR: scandipwa/store-graphql#17
=> Login Dashboard Redirect

packages/scandipwa/src/route/CartPage/CartPage.container.js, packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.container.js, packages/scandipwa/src/route/ContactPage/ContactPage.container.js, packages/scandipwa/src/route/NoMatch/NoMatch.component.js, packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.container.js, packages/scandipwa/src/route/ProductComparePage/ProductComparePage.container.js, packages/scandipwa/src/route/SearchPage/SearchPage.container.js, packages/scandipwa/src/store/Breadcrumbs/Breadcrumbs.dispatcher.js, yarn.lock
=> Removed duplicate breadcrumb home item

packages/scandipwa/src/component/MyAccountDownloadable/MyAccountDownloadable.component.js, packages/scandipwa/src/component/MyAccountDownloadable/MyAccountDownloadable.container.js, packages/scandipwa/src/component/MyAccountDownloadable/index.js, packages/scandipwa/src/component/MyAccountDownloadableTableRow/MyAccountDownloadableTableRow.component.js, packages/scandipwa/src/component/MyAccountDownloadableTableRow/MyAccountDownloadableTableRow.container.js, packages/scandipwa/src/component/MyAccountDownloadableTableRow/MyAccountDownloadableTableRow.style.scss, packages/scandipwa/src/component/MyAccountDownloadableTableRow/index.js, packages/scandipwa/src/query/Order.query.js, packages/scandipwa/src/route/MyAccount/MyAccount.component.js, packages/scandipwa/src/route/MyAccount/MyAccount.container.js, packages/scandipwa/src/type/Account.js
Fixes #794 
Added downloadable product support.
Backend implementation: scandipwa/customer-downloadable-graphql
=> Downloadable Product Support

packages/scandipwa/src/component/ProductGallery/ProductGallery.container.js, packages/scandipwa/src/query/ProductList.query.js
=> Refactored media gallery positioning

packages/scandipwa/src/component/CartItem/CartItem.component.js, packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.container.js, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.style.scss, packages/scandipwa/src/component/ProductDownloadableLinks/index.js, packages/scandipwa/src/query/Cart.query.js, packages/scandipwa/src/query/ProductList.query.js, packages/scandipwa/src/route/ProductPage/ProductPage.component.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js, packages/scandipwa/src/store/Cart/Cart.dispatcher.js, packages/scandipwa/src/util/Product/Product.js, packages/scandipwa/src/util/Product/Types.js
Requires PR: https://github.com/scandipwa/quote-graphql/pull/63
Original issue: #2269 
In this PR:
* Support for samples
* Support for links
=> #2269 Downloadble product links & samples

packages/scandipwa/src/component/CmsBlock/CmsBlock.component.js, packages/scandipwa/src/component/CmsBlock/CmsBlock.container.js, packages/scandipwa/src/component/CmsBlock/CmsBlock.style.scss, packages/scandipwa/src/component/Footer/Footer.style.scss, packages/scandipwa/src/component/Menu/Menu.component.js, packages/scandipwa/src/component/Menu/Menu.config.js
Added possibility to style/position different types of CMS blocks based on their type set up in Magento.
=> bugfix #1920 cms block order

packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.container.js
=> Carved out breadcrumbs from password change page

packages/scandipwa/src/route/ProductPage/ProductPage.container.js
Original issue: #2328 
In this PR:
Due to #2057 bundle & downloadable product selections weren't saving, so:
* Fixed issue for bundle product selection
* Fixed issue for downloadable product selection
=> #2328 Fixing product selectable options

packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.component.js, packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.container.js
Fixes: scandipwa/scandipwa#2330
=> bugfix #2330 - proper check supplementation

packages/scandipwa/src/component/MyAccountDownloadable/MyAccountDownloadable.component.js, packages/scandipwa/src/component/MyAccountDownloadableTableRow/MyAccountDownloadableTableRow.component.js, packages/scandipwa/src/component/MyAccountMyOrders/MyAccountMyOrders.style.scss, packages/scandipwa/src/component/MyAccountOrderTableRow/MyAccountOrderTableRow.style.scss
Fixes scandipwa/scandipwa#2339
=> bugfix #2339 - prettified tables and made them responsive

packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/2340
Fix ratings position
=> #2340 - ratings position list layout

packages/scandipwa/src/component/SharedWishlistItem/SharedWishlistItem.container.js, packages/scandipwa/src/component/SharedWishlistItem/SharedWishlistItem.style.scss
=> bugfix #2042 - lost method return with style improvements

packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
Fixes: scandipwa/scandipwa#2345
=> bugfix scandipwa/scandipwa#2345 - supplementing plpTypes check for the CategoryPage

packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
=> Disabling view mode on list mode config fix

packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js, packages/scandipwa/src/route/CmsPage/CmsPage.container.js
This PR supplements CmsPages with a missing scrollTop behavior on page change through the footer links
=> Supplemented scrollTo behavior for CmsPage mount

packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.container.js
This is fix for FE side.
Issue also requires a fix on BE side - out of stock items should be filtered out when adding to cart (https://github.com/scandipwa/wishlist-graphql/pull/10)
=> Bugfix #1765 - add all wishlist items to cart error handling

packages/scandipwa/src/component/CartItem/CartItem.component.js, packages/scandipwa/src/component/CartItem/CartItem.style.scss, packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.style.scss
Fixes: scandipwa#2341
Related:
https://github.com/scandipwa/customer-downloadable-graphql/pull/2
=> Improvement for downloadable products styles

packages/scandipwa/src/component/ProductGallery/ProductGallery.container.js, packages/scandipwa/src/query/ProductList.query.js
=> Supplemented missing query with the condition

packages/scandipwa/package-lock.json, packages/scandipwa/package.json, yarn.lock
=> Merge 4.2.0 To Master

packages/scandipwa/src/component/Popup/Popup.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/2397
=> #2397 - backdrop wrong position

packages/scandipwa/package.json, packages/scandipwa/src/component/Header/Header.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/2348
=> #2348 - return header truncation with "..." instead of multiline

packages/scandipwa/src/component/GroupedProductList/GroupedProductList.component.js, packages/scandipwa/src/component/Klarna/Klarna.component.js, packages/scandipwa/src/component/Link/Link.component.js, packages/scandipwa/src/store/LinkedProducts/LinkedProducts.dispatcher.js
Fixed scandipwa/scandipwa#2244
Fixed some issues found after update.
=> After Update Issues

packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js
Fixes: scandipwa/scandipwa#2365
=> bugfix #2365 - supplemented isMobile check for plp

packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.component.js, packages/scandipwa/src/component/CheckoutRegisterForm/CheckoutRegisterForm.component.js, packages/scandipwa/src/component/CheckoutRegisterForm/CheckoutRegisterForm.container.js, packages/scandipwa/src/component/CheckoutRegisterForm/CheckoutRegistrationForm.config.js, packages/scandipwa/src/component/CheckoutRegisterForm/CheckoutRegistrationForm.style.scss, packages/scandipwa/src/component/CheckoutRegisterForm/index.js, packages/scandipwa/src/component/CheckoutSuccess/CheckoutSuccess.component.js, packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.component.js, packages/scandipwa/src/query/Order.query.js, packages/scandipwa/src/route/Checkout/Checkout.component.js
Original issue: #2148 
Required PR for this issue: https://github.com/scandipwa/quote-graphql/pull/61
In this PR:
* Removed registration from shipping, but kept login form
* Added new form for guest customer to create account after checkout
* Added linking of order and customer to add order to newly created customer.
=> #2148 Create user after checkout

packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductWishlistButton/ProductWishlistButton.container.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss, packages/scandipwa/src/query/Wishlist.query.js, packages/scandipwa/src/store/Cart/Cart.dispatcher.js, packages/scandipwa/src/store/Wishlist/Wishlist.dispatcher.js, packages/scandipwa/src/util/Wishlist/Wishlist.js, packages/scandipwa/src/util/Wishlist/index.js
Original issue: #1876  #1877 
PR required: 
* https://github.com/scandipwa/wishlist-graphql/pull/16
* https://github.com/scandipwa/quote-graphql/pull/66
In this PR:
* Downloadable product configuration support
* Bundle product configuration support
* Grouped product configuration support
* Price display based on options for grouped & downloadable products
* Purchase of downloadable, bundle, grouped products based on their configuration
* Show Details button: Shows selected configurations
* Shows badge for grouped product
Old PR (_deprecated_): https://github.com/scandipwa/scandipwa/pull/2259
=> #1876 Wishlist item option support

packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
Fixes: scandipwa/scandipwa#2474
=> bugfix #2474 - shipped left padding to the ProductCard

packages/scandipwa/src/component/ProductActions/ProductActions.container.js, packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.container.js
Fixes: scandipwa/scandipwa#2239
=> feature #2239 - implemented simple product customizable options price calculation

packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js, packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.config.js, packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.container.js, packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.style.scss, packages/scandipwa/src/component/CheckoutDeliveryOptions/CheckoutDeliveryOptions.container.js
Fixes #2499 
Added support of unavailable delivery method if "display if not applicable" setting is enabled.
=> Added Unavailable Delivery Method Support

packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js
Fixes: scandipwa/scandipwa#2523
=> bugfix #2523 - changed destruction for PCO fileField

packages/scandipwa/src/component/FieldTextarea/FieldTextarea.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
Issue: #1725 
Comment is now a scrollable textarea.
=> Bugfix #1725 - one line from the comment is displayed in wishlist

packages/scandipwa/src/component/ProductAttributes/ProductAttributes.component.js, packages/scandipwa/src/component/ProductAttributes/ProductAttributes.style.scss, packages/scandipwa/src/query/ProductList.query.js
PR for feature request https://github.com/scandipwa/scandipwa/issues/2280
=> Display product attributes per group

packages/scandipwa/src/component/NewProducts/NewProducts.component.js, packages/scandipwa/src/component/RecentlyViewedWidget/RecentlyViewedWidget.component.js
Issue: https://github.com/scandipwa/scandipwa/issues/2404
=> #2404 - titles different font

packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js
Fixes: scandipwa/scandipwa#2444
=> bugfix #2444 - shipped update method on isMobile props

packages/scandipwa/src/component/CategoryProductList/CategoryProductList.container.js, packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductListPage/ProductListPage.component.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.config.js
Task: https://github.com/scandipwa/scandipwa/issues/2347
Save selected user layout to localstorage.
=> #2347 - save layout to localstorage

packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
Issue: #2308 
Quantity field's frame is not turning green anymore.
=> Bugfix #2308 - Green frame for qty field on product page

packages/scandipwa/src/component/ImageZoomPopup/ImageZoomPopup.container.js
=> Fix issue with back button on gallery zoom

packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js
Fixes: scandipwa/scandipwa#2520
=> bugfix #2520 - changed max_characters destructuring

packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
=> Added missing key prop to CategoryPage buttons

packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.config.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js
Fixes: scandipwa/scandipwa#2347
=> bugfix #2347 - store selected plpType choice on page refresh

packages/scandipwa/src/component/NavigationTabs/NavigationTabs.container.js
=> Added account url to routeMap

packages/scandipwa/src/component/Form/Form.config.js
Issue: https://github.com/scandipwa/scandipwa/issues/2483
=> #2483 - fix phone validation

packages/scandipwa/src/component/ProductGallery/ProductGallery.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/2403
=> #2403 - product gallery images position

packages/scandipwa/src/component/Breadcrumbs/Breadcrumbs.component.js
=> #2528 - Fixed itemprop position for breadcrumbs

packages/scandipwa/src/component/ImageZoomPopup/ImageZoomPopup.component.js, packages/scandipwa/src/component/TranslateOnCursorMove/TranslateOnCursorMove.component.js
Fixes #2453
Fixed photo gallery fullscreen issue when photo should move with the cursor.
=> Photo Gallery Fullscreen Issue

packages/scandipwa/src/component/CheckoutSuccess/CheckoutSuccess.component.js
- Fixed bug where logged in user sees possibility to create account after checkout if he created account after checkout in the previous order
=> Fix issue #2537

packages/scandipwa/src/component/ProductActions/ProductActions.config.js, packages/scandipwa/src/component/ProductActions/ProductActions.container.js, packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.component.js, packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.config.js, packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.container.js, packages/scandipwa/src/component/ProductBundleItems/ProductBundleItems.container.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.container.js, packages/scandipwa/src/query/ProductList.query.js, packages/scandipwa/src/route/ProductPage/ProductPage.component.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js, packages/scandipwa/src/util/Product/Product.js
Fixes #2416, #2479, #1476
BE PR: https://github.com/scandipwa/catalog-graphql/pull/97
⚠️  **BACKEND NEEDS TO BE MERGED FIRST.**
=> DON'T MERGE BEFORE BE: #1476 - Improve price calculation for bundle products

packages/scandipwa/src/util/Product/Product.js
Fixes: scandipwa/scandipwa#2648
=> bugfix #2648 - shipped undefined check

packages/scandipwa/src/component/ProductActions/ProductActions.container.js
Fixes: scandipwa/scandipwa#2519
=> bugfix #2519 – shipped customizable type support

packages/scandipwa/src/component/ProductActions/ProductActions.container.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.container.js
Fixes: scandipwa/scandipwa#2527
=> bugfix #2527 - shipped proper prices and discount values

packages/scandipwa/src/component/ProductActions/ProductActions.container.js
Fixes: scandipwa/scandipwa#2542
=> bugfix #2542 - shipped undefined validation for product custom price

packages/scandipwa/src/component/MyAccountNewsletterSubscription/MyAccountNewsletterSubscription.container.js
Fixes: scandipwa/scandipwa#2610
=> bugfix #2610 - replaced newsletter successful notification message

packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.component.js, packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.container.js
Fixes: scandipwa/scandipwa#2630
=> bugfix #2630 - shipped newsletter status check for checkbox

packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js
=> Remove hide/shows details for not grouped or bundle products

packages/scandipwa/src/component/MyAccountNewsletterSubscription/MyAccountNewsletterSubscription.container.js
Fixes: scandipwa/scandipwa#2680
=> bugfix #2680 - shipped notification determining logic

packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.container.js, packages/scandipwa/src/store/Wishlist/Wishlist.dispatcher.js
Problem was that in stock items are not adding to cart from wishlist when there are out of stock items in it. This is the FE part of the fix.
=> Fix for #2533 Products which in stock aren't added to cart from Wishlist if user has products out of stock in Wishlist 

packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.container.js
=> issue-1639 - Fix confirm account message appear

packages/scandipwa/src/store/NewsletterSubscription/NewsletterSubscription.dispatcher.js
Fixes: scandipwa/scandipwa#2700
=> bugfix #2700 – replaced notification message on form submit

packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
=> issue-2702 - Adjust wishlist item styling

packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.container.js, packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.component.js
Fixes: scandipwa/scandipwa#2682
=> feature #2682 - shipped final price to the percent option label

packages/scandipwa/src/store/Wishlist/Wishlist.dispatcher.js
Fixes: scandipwa/scandipwa#2248
=> bugfix #2248 - removed redundant console logs

packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductBundleItems/ProductBundleItems.component.js, packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.container.js, packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.component.js
Fixes: scandipwa/scandipwa#2721
=> bugfix #2721 - refactored product price format for options

packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.container.js, packages/scandipwa/src/store/MyAccount/MyAccount.action.js, packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js, packages/scandipwa/src/store/MyAccount/MyAccount.reducer.js
Fixes #2223 
related: https://github.com/scandipwa/customer-graph-ql/pull/18
=> issue-2223 - Fix incorrect message appear on error password reset

packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.component.js, packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.config.js, packages/scandipwa/src/query/ProductList.query.js, packages/scandipwa/src/store/ProductListInfo/ProductListInfo.reducer.js
**DON'T MERGE BEFORE BE**
BE PR: https://github.com/scandipwa/catalog-graphql/pull/96
=> #1439 Bugfix/boolean attributes 

packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.container.js
Fixes: scandipwa/scandipwa#2736
=> bugfix #2736 - refactored bundle and simple price calculation

packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.component.js, packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.style.scss, packages/scandipwa/src/route/MyAccount/MyAccount.container.js
Fixes: scandipwa/scandipwa#2630
=> bugfix #2630 - disabled newsletter from account and styled legend

packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js
=> issue-2724 Checkout issue getting value from undefined country 

packages/scandipwa/src/component/Router/Router.container.js
Fixes #2733
Removed undefined method call.
=> Update Compare Data Method Issue

packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.container.js
Fixes: scandipwa/scandipwa#2745, scandipwa/scandipwa#2736
=> bugfix #2745 - shipped proper per cent price calculation

packages/scandipwa/src/component/MyAccountOrderPopup/MyAccountOrderPopup.container.js, packages/scandipwa/src/store/Config/Config.reducer.js
Fixes #2271
Fixed some console errors
Related PR: scandipwa/quote-graphql/pull/75
=> Order popup FE

packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js
=> issue-2730 -Fix undefined props

packages/scandipwa/src/component/ProductCard/ProductCard.container.js, packages/scandipwa/src/query/Config.query.js, packages/scandipwa/src/store/Config/Config.reducer.js
Fixes #2750
Related PR: scandipwa/store-graphql/pull/25
Fixed product card url computation and fixed the issue when page crashed.
=> Product Card Url Fix FE

packages/scandipwa/src/component/ProductActions/ProductActions.container.js
=> issue-2683 - Fix equal price issue

packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.container.js, packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.component.js, packages/scandipwa/src/route/CreateAccount/CreateAccount.component.js
=> Confirm account message for landing page

packages/scandipwa/src/route/UrlRewrites/UrlRewrites.component.js
Fixes #2688 
related: https://github.com/scandipwa/urlrewrite-graphql/pull/8
=> Fix noMatchUrlHangler

packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.component.js, packages/scandipwa/src/component/ProductConfigurableAttributes/ProductConfigurableAttributes.container.js, packages/scandipwa/src/util/Product/Product.js
Issue: https://github.com/scandipwa/scandipwa/issues/2747
=> #2747 fix ExpandableContent subheading for boolean attributes

packages/scandipwa/src/component/FieldInput/FieldInput.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.container.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.component.js
Fixes #2759
Fixed wishlist page crashing.
Fixed some errors from the console.
=> Wishlist Page Crashing

packages/scandipwa/src/component/StoreInPickUp/StoreInPickUp.component.js, packages/scandipwa/src/component/StoreInPickUpStore/StoreInPickUpStore.component.js, packages/scandipwa/src/component/StoreInPickUpStore/StoreInPickUpStore.container.js
=> issue-2766 - Fix StoreInPickUp method

packages/scandipwa/src/component/MyAccountOrderPopup/MyAccountOrderPopup.container.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/store/Config/Config.reducer.js, packages/scandipwa/src/store/Order/Order.dispatcher.js
Fixed invalid request on order popup close.
Fixed some console errors.
=> Order Popup Fix

packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.component.js, packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.container.js, packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js, packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.container.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.container.js
Fixes scandipwa/scandipwa#2761
=> bugfix #2761 - inadequate product prices work

packages/scandipwa/src/component/ProductActions/ProductActions.container.js, packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.component.js, packages/scandipwa/src/component/ProductBundleItem/ProductBundleItem.container.js, packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js, packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.container.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.container.js, packages/scandipwa/src/query/ProductList.query.js
Issue: https://github.com/scandipwa/scandipwa/issues/2674
BE PR: https://github.com/scandipwa/catalog-graphql/pull/105
:warning: **BE needs to be merged first (new GQL fields are requested on FE)**
=> #2674 wrong prices for simple product with customizable options

packages/scandipwa/src/component/Header/Header.component.js, packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.container.js
Issue was that the user wasn't notified if auth token expired after page is refreshed.
=> Fixed issue #2505 User isn't notified for automatically signing out after cookie lifetime expires and he/she refreshes the page

packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.container.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js, packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js, packages/scandipwa/src/util/Product/Product.js
Fixes #2734
Filtered out of stock variants so they are not selected by default if filters are filled partially.
=> Configurable Product Price Fix On PDP

packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.container.js
=> bugfix #2814 – options price missing fix

packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js, packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.style.scss
Fixes scandipwa/scandipwa#2069
=> feature #2069 - add to wishlist button for compare list product

packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
Fixes: scandipwa/scandipwa#2017
=> feature #2017 - shipped quantity control buttons

packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
Fixes: scandipwa/scandipwa#2469
=> feature - #2469 - changed skuAndStock padding and order

packages/scandipwa/mosaic.jsconfig.json, packages/scandipwa/package.json, yarn.lock
Updated dependencies:
- @scandipwa/scandipwa-scripts: 2.4.9
- @scandipwa/service-worker: 0.0.10
- @scandipwa/webpack-i18n-runtime: 0.0.21
=> Npm dependencies update

packages/scandipwa/src/component/SearchField/SearchField.component.js, packages/scandipwa/src/query/ProductList.query.js, packages/scandipwa/src/route/SearchPage/SearchPage.component.js
Fixed so the search URL is better UX
=> Change the URL structure for each so its easier to see and UX is better.

packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.component.js, packages/scandipwa/src/query/ProductList.query.js, packages/scandipwa/src/store/ProductListInfo/ProductListInfo.reducer.js
Issue: https://github.com/scandipwa/scandipwa/issues/2649
=> #2649 - fix broken color swatch

packages/scandipwa/src/component/ProductGallery/ProductGallery.container.js
[https://github.com/scandipwa/scandipwa/issues/2504](url)
=> fixed base image isn't displayed issue in PDP, now shows base as expected

packages/scandipwa/src/component/CartItem/CartItem.style.scss, packages/scandipwa/src/route/CartPage/CartPage.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/2425
=> #2425 - decrease distance between header and options for cart items

packages/postcss-config/README.md, packages/postcss-config/build-config/postcss-logical-properties.js, packages/postcss-config/package.json
Added a postcss plugin in order to support logical CSS properties.
=> Logical CSS Properties Support

packages/scandipwa/src/component/CheckoutAddressBook/CheckoutAddressBook.component.js, packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.component.js
Issue: https://github.com/scandipwa/scandipwa/issues/2696
=> #2696 - show address form on billing step

packages/scandipwa/src/component/CarouselScroll/CarouselScroll.style.scss, packages/scandipwa/src/component/ProductGallery/ProductGallery.component.js, packages/scandipwa/src/component/ProductList/ProductList.component.js
=> Plp scroll

packages/scandipwa/src/component/Header/Header.component.js, packages/scandipwa/src/component/SearchField/SearchField.component.js
Fixes #2896 
Combined chunks that are using overlay in order to fix overrided style issue.
=> PLP Broken Style Fix

packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.component.js, packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.component.js, packages/scandipwa/src/component/MyAccountForgotPassword/MyAccountForgotPassword.component.js, packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.component.js
Fixes scandipwa/scandipwa#1664
=> bugfix #1664 – shipped proper field types

packages/scandipwa/src/component/Router/Router.component.js, packages/scandipwa/src/route/SomethingWentWrong/SomethingWentWrong.component.js, packages/scandipwa/src/util/Product/Product.js
Fixes scandipwa/scandipwa#2914
=> bugfix #2914 – suspense and router improvements

packages/scandipwa/src/component/Header/Header.component.js, packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.container.js
Reverts scandipwa/scandipwa#2594
=> Revert bugfix – #2505 user notification on log out

packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.container.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js
Original issue: https://github.com/scandipwa/scandipwa/issues/2615
Required PR: https://github.com/scandipwa/wishlist-graphql/pull/20
In this PR:
* Changed logic of how success message is outputted, so that only on successful response.
* Returning error message from BE side (out of stock / failed to place order).
=> #2615 Wishlist error and success message correction

packages/scandipwa/src/component/Breadcrumb/Breadcrumb.component.js, yarn.lock
Fixes scandipwa/scandipwa#2892
=> bugfix #2892 – shipped clean breadcrumbs name

packages/m2-theme/public/index.php
Fixes #2917 
`<html>` tag `dir` attribute is managed by admin panel configuration.
=> LTR / RTL Switch FE

packages/scandipwa/src/component/ProductActions/ProductActions.container.js
Original issue: #2928 
In this PR: added check to see if configurable option is selected.
=> #2928 Ooops on PDP from compare list

packages/scandipwa/src/component/CartOverlay/CartOverlay.component.js, packages/scandipwa/src/component/CartOverlay/CartOverlay.container.js
Original issue: #2741 
In this PR: scrolls up to page top when clicked on cart page.
=> #2741 Scroll to top when click cart

packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js
Original issue: https://github.com/scandipwa/scandipwa/issues/2789
In this PR: Fixing configuration to output error messages in myaccount address form
=> #2789 Error messages for editting/creating address

packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/2713
=> #2713 - scroll MyAccount Overlay

packages/scandipwa/src/component/Header/Header.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/2952
=> 2592 - cart icon is missing

packages/scandipwa/src/component/Header/Header.style.scss, packages/scandipwa/src/component/MyAccountDownloadableTableRow/MyAccountDownloadableTableRow.component.js, packages/scandipwa/src/component/MyAccountDownloadableTableRow/MyAccountDownloadableTableRow.config.js, packages/scandipwa/src/component/MyAccountDownloadableTableRow/MyAccountDownloadableTableRow.style.scss, packages/scandipwa/src/route/MyAccount/MyAccount.component.js
Issue: https://github.com/scandipwa/scandipwa/issues/2661
=> #2661 - hide downloadable links for expired products

packages/scandipwa/src/component/CheckoutAddressBook/CheckoutAddressBook.component.js, packages/scandipwa/src/component/CheckoutAddressForm/CheckoutAddressForm.component.js, packages/scandipwa/src/component/CheckoutDeliveryOptions/CheckoutDeliveryOptions.component.js, packages/scandipwa/src/component/CheckoutDeliveryOptions/CheckoutDeliveryOptions.container.js, packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.component.js, packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.container.js, packages/scandipwa/src/component/StoreInPickUp/StoreInPickUp.container.js
Exactly same fixes as https://github.com/scandipwa/scandipwa/pull/2965, but I recreated the branch from rc-5.0.0, not master this time.
Issues: #2953, #2954, #2955
=> 2953/shipping step fixes 5.0.0 rc

packages/scandipwa/src/component/CheckoutAddressForm/CheckoutAddressForm.component.js, packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.container.js, packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.component.js, packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js
Original issue: #2927 
In this PR: Added missing 'null' value checks
=> #2927  Ooops for logedin user on shipping page

packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductActions/ProductActions.container.js
=> #2928 Ooops when opening config product from compare list

packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.style.scss
=> #2932 - align checkbox top

packages/scandipwa/src/component/NavigationTabs/NavigationTabs.container.js, packages/scandipwa/src/route/CartPage/CartPage.container.js
Original issue: https://github.com/scandipwa/scandipwa/issues/2741
In this PR:
* Added scroll to top for mobile cart button
* Added scroll to top when going to shipping step on mobile
=> #2741 Scroll to top on mobile cart

packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.container.js
**Original Issue:**
* https://github.com/scandipwa/scandipwa/issues/2956
**Required PR:**
* https://github.com/scandipwa/wishlist-graphql/pull/23
* Added option to output array of errors.
=> #2956 Wishlist configurable product error messages

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/component/StoreInPickUpPopup/StoreInPickUpPopup.style.scss
master was broken due to using nonexistenent mixin
=> replace unused mixin + add missing translations

packages/scandipwa/src/component/CheckoutAddressForm/CheckoutAddressForm.component.js, packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js, packages/scandipwa/src/util/Address/index.js
Issue: https://github.com/scandipwa/scandipwa/issues/2988
=> #2988 - default country in my account fix

packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.style.scss, packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js
Issue: https://github.com/scandipwa/scandipwa/issues/3015
Also fixed "Forgot password" label a bit shifted to the right.  (Was asked by Aleksandra to fix it before release.)
=> #3015 - fix error on downloadable product load

packages/scandipwa/src/component/ProductActions/ProductActions.container.js
=> issue-3002 - Added default value for bundle prices

packages/scandipwa/src/component/ProductCard/ProductCard.style.scss, packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss
Add flex-wrap for price to move to next line, if it doesn't fit.
=> fix long price product card

packages/scandipwa/src/component/Field/Field.style.scss
Issues: https://github.com/scandipwa/scandipwa/issues/3055 + https://github.com/scandipwa/scandipwa/issues/3056
=> fix missing labels

packages/framework/public/index.html, packages/m2-theme/public/index.php
Issue: https://github.com/scandipwa/scandipwa/issues/3073
This fix has already applied done for template used in storefront mode. But not for the one for Magento theme.
=> #3973 - fix page zoom on keyboard activate

packages/scandipwa/src/style/Icons/Compare/Compare.scss, packages/scandipwa/src/style/Icons/Heart/Heart.scss
Issue: https://github.com/scandipwa/scandipwa/issues/3069
=> #3069 - fix icons stay hovered

packages/scandipwa/src/component/CategorySort/CategorySort.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/3064
=> #3064 - fix odd arrows on PLP

package.json, packages/chunk-optimizer/build-config/craco.js, yarn.lock
Chunk optimizer was tested on build, but didn't tested on start.
This plugin failed start.
=> Chunk Optimizer Fix

packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/style/Icons/Edit/Edit.js
=> issue-3070 - Pass onClick function for edit icon

packages/scandipwa/src/component/Slider/Slider.component.js, packages/scandipwa/src/component/SliderWidget/SliderWidget.component.js, packages/scandipwa/src/component/SliderWidget/SliderWidget.config.js
Issue: https://github.com/scandipwa/scandipwa/issues/2868
=> #2868 - wrong slider direction

packages/scandipwa/src/util/Request/DataContainer.js
=> Fixed a typo

packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.style.scss, packages/scandipwa/src/style/abstract/_button.scss
Fixes https://github.com/scandipwa/scandipwa/issues/3079 and https://github.com/scandipwa/scandipwa/issues/3080.
=> #3079 - missing hover effect

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/component/ProductAlerts/ProductAlerts.component.js, packages/scandipwa/src/component/ProductAlerts/ProductAlerts.container.js
Fixed eslint error.
Added translation changes.
=> Master Branch Fixes

packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.component.js, packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.container.js, packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.style.scss
Fixes #2731 
Added error message if params are not present
=> Email Confirmation Page Fix

packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.style.scss, packages/scandipwa/src/component/StoreSwitcher/StoreSwitcher.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/3138
I removed right margin from currency selector and added left margin to the store selector.
=> #3138 - align currecny switcher

packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.style.scss, packages/scandipwa/src/route/SearchPage/SearchPage.container.js
Issue: https://github.com/scandipwa/scandipwa/issues/3149
=> #3149 - handle no search results UX

packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.container.js, packages/scandipwa/src/route/CreateAccount/CreateAccount.container.js, packages/scandipwa/src/route/ForgotPassword/ForgotPassword.container.js
Issue: https://github.com/scandipwa/scandipwa/issues/3113
=> #3113 - fix missing props

packages/scandipwa/src/component/ImageZoomPopup/ImageZoomPopup.style.scss
issue: https://github.com/scandipwa/scandipwa/issues/3159
Fixed height for android
=> Image height fix

packages/scandipwa/src/component/CartItem/CartItem.style.scss, packages/scandipwa/src/component/SwipeToDelete/SwipeToDelete.component.js, packages/scandipwa/src/component/SwipeToDelete/SwipeToDelete.style.scss, packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/3142
Added gap by adding left margin to Delete button and applying background-color to button only, not the whole container.
=> #3142 - swipe to delete fix no gap

packages/scandipwa/composer.json, packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/package.json, packages/scandipwa/src/component/ProductCompare/ProductCompare.style.scss
Updated catalog-graphql version, updated translations, fixed type in css.
=> Some Fixes

packages/scandipwa/src/route/Checkout/Checkout.container.js, packages/scandipwa/src/util/Address/index.js
* https://github.com/scandipwa/scandipwa/issues/3273
* https://github.com/scandipwa/scandipwa/issues/3268
**Problem:**
* Passing null as one of the street returns error for mysql
* Filtering out null street values.
=> #3273 Filter out empty address on shipping

packages/scandipwa/src/component/CartItem/CartItem.component.js, packages/scandipwa/src/component/Field/Field.component.js, packages/scandipwa/src/component/Field/Field.container.js
* https://github.com/scandipwa/scandipwa/issues/3286
* Added so that quantity is changed for items in cart / mini-cart based on their defined increment.
=> #3286 Cart item qty change, based on increment.

packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.component.js, packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/3152
=> #3152 - fix empty wishlist overlaps buttons

packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js
Issue: https://github.com/scandipwa/scandipwa/issues/3164
=> #3164 - add wishlist item rating mobile

packages/scandipwa/src/component/Header/Header.component.js, packages/scandipwa/src/component/Header/Header.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/3140
=> #3140 - remove back arrow search

packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js, packages/scandipwa/src/util/Address/index.js
Issues: https://github.com/scandipwa/scandipwa/issues/3212 + https://github.com/scandipwa/scandipwa/issues/2970
=> #2998 - fix region select for country without regions

packages/scandipwa/src/route/CartPage/CartPage.component.js, packages/scandipwa/src/route/CartPage/CartPage.container.js
Issue: https://github.com/scandipwa/scandipwa/issues/3028
=> #3028 - change mobile cart layout

packages/scandipwa/src/component/CartItem/CartItem.component.js, packages/scandipwa/src/component/CartItem/CartItem.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/2998
=> #2998 - change delete button position

packages/scandipwa/src/component/ResetAttributes/ResetAttributes.container.js
Issue: https://github.com/scandipwa/scandipwa/issues/3003
=> #3003 - yes no label for reset attributes

packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.component.js, packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.container.js
Issue: https://github.com/scandipwa/scandipwa/issues/3237
=> #3237 - checkbox not selectable

packages/scandipwa/src/component/MyAccountAddressTable/MyAccountAddressTable.container.js, packages/scandipwa/src/component/MyAccountCustomerTable/MyAccountCustomerTable.container.js
Fixes #3216 
Fixed title prop propagation
=> MyAccount Table Header Fix

packages/scandipwa/src/component/StarIcon/StarIcon.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/3109
=> #3109 - fix star icon not mirrored

packages/scandipwa/src/route/CartPage/CartPage.style.scss
* https://github.com/scandipwa/scandipwa/issues/3297
Problem:
* Missing style rule for border on mobile
In this PR:
* Added style rule for border on mobile
=> #3297 Border in cart between discount on mobile

packages/scandipwa/src/component/Header/Header.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/3202
=> #3202 - center welcome message

packages/scandipwa/src/store/Breadcrumbs/Breadcrumbs.dispatcher.js
Issue: https://github.com/scandipwa/scandipwa/issues/3330
Also mentioned in https://docs.google.com/spreadsheets/d/1W6xvVq30yHWK26DNzu8CjuykG2-hRlleT_ugQv1jmqs/edit#gid=163523011
=> #3330 - fix loader instead of breadcrumbs

build-packages/next-emulator/lib/generate-pages.js
Removed pages dir geneartion if no pages config found.
=> Removed pages dir geneartion if no pages config found

packages/scandipwa/magento/etc/view.xml
=> #3346 - Add sizes image thumbnail

packages/scandipwa/src/query/ProductList.query.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.component.js
Note: requires this scandipwa/catalog-graphql update to work
https://github.com/scandipwa/catalog-graphql/pull/122
=> Performance optimization - switching PDP to load by ID

packages/scandipwa/src/component/Header/Header.container.js, packages/scandipwa/src/route/CreateAccount/CreateAccount.container.js, packages/scandipwa/src/route/LoginAccount/LoginAccount.container.js, packages/scandipwa/src/route/MyAccount/MyAccount.container.js, packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
Issue: https://github.com/scandipwa/scandipwa/issues/3350
Fixed several faulty cases (for mobile and desktop).
Mobile issue reason: odd redirect for mobile version (should be only for desktop)
Desktop issues reason: change of auth state is accompanied with redirect to page X. When you try to go back after being redirected and previous URL that is not available after change of auth state, user is redirected page X again => it looks like navigate back doesn't have effect at all.
=> #3350 - navigate back my account fixes

packages/scandipwa/src/component/InstallPromptAndroid/InstallPromptAndroid.style.scss
Issue: https://github.com/scandipwa/scandipwa/issues/3343
=> #3343 - change android a2hs popup styling

packages/scandipwa/src/route/NoMatch/NoMatch.component.js
Issue: https://github.com/scandipwa/scandipwa/issues/3220
=> #3320 - 404 scroll top

packages/scandipwa/src/component/ProductCompare/ProductCompare.component.js
Issue: https://github.com/scandipwa/scandipwa/issues/3364
=> #3364 - fix no message after compare list clear

packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.component.js
Issue: https://github.com/scandipwa/scandipwa/issues/3217
=> #3217 - fix change default address not working

packages/scandipwa/src/component/ContactForm/ContactForm.form.js, packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.component.js, packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.container.js, packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss, packages/scandipwa/src/component/PureForm/Form/Form.component.js, packages/scandipwa/src/component/PureForm/Form/Form.container.js
* https://github.com/scandipwa/scandipwa/issues/3395
Problem:
* Form was missing mix prop, thus form contained missing class names
In this PR:
* Added mix prop
* Added font size & cursor
* Fixed loading state
* Removed `...`
=> #3395 Review form style & submit fix

packages/scandipwa/src/component/GroupedProductsItem/GroupedProductsItem.component.js, packages/scandipwa/src/component/GroupedProductsItem/GroupedProductsItem.style.scss
* https://github.com/scandipwa/scandipwa/issues/3403
**Problem:**
* Missing functionality
* Added out of stock message for bundle item
=> [3403] Out of stock msg for bundle

packages/scandipwa/src/component/Product/Product.container.js
* https://github.com/scandipwa/scandipwa/issues/3406
**Problem:**
* Sometimes when calling function getDerivedStateFromProps, the items value is not yer returned from graphql, thus outputs error + qty is 0
* Moved logic to didComponentUpdate
=> [3406] Bundle Ooops page

packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.component.js, packages/scandipwa/src/component/Product/Product.container.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js
* https://github.com/scandipwa/scandipwa/issues/3408
**Required PR:**
* https://github.com/scandipwa/wishlist-graphql/pull/26
**Problem:**
* Placeholder for wishlist isn't passing product prop
* Added few fallback values
* Added product prop for placeholder
=> [3408] MyAccount wishlist ooops

packages/scandipwa/src/component/GroupedProductsItem/GroupedProductsItem.style.scss, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
**Original issues:**
* https://github.com/scandipwa/scandipwa/issues/3423
* https://github.com/scandipwa/scandipwa/issues/3422
**Problem:**
* Padding added to title for grouped item on mobile
* Missing style for qty changer on mobile
=> [3423] Mobile qty changer & grouped title

packages/scandipwa/src/component/Product/Product.component.js
* https://github.com/scandipwa/scandipwa/issues/3424
**Problem:**
* Some products have only one tier price that is the same as default price
=> [3424] As low as for tier prices

packages/scandipwa/src/route/ProductPage/ProductPage.container.js
*  Fixes https://github.com/scandipwa/scandipwa/issues/3439
=> Add missing location prop to containerprops

packages/scandipwa/src/component/Product/Product.component.js
**Issue:**
* Fixes https://github.com/scandipwa/scandipwa/issues/3434
**Problem:**
* missing `priceTiers` check for non-null value
* Added check for `priceTiers`
=> [3434] TierPrice access check

packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.component.js, packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3442
**Problem:**
* Missing style rules
* Added missing style rules
* Added more class names for label and sublabel
=> [3442] Space for Layered Navigation item count

packages/scandipwa/src/store/ProductCompare/ProductCompare.reducer.js
* Fixes https://github.com/scandipwa/scandipwa/pull/3466
**Problem:**
* no way no show immediate icon status without caching
* adding storing compare list to localstorage + update in on every compare list update
=> #3367 - add storing compare list data in localstorage

packages/scandipwa/src/component/GroupedProductsItem/GroupedProductsItem.component.js, packages/scandipwa/src/component/GroupedProductsItem/GroupedProductsItem.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3443 
**Problem:**
* 3 column,1 row layout doesn't match expected behaviour 
* Change layout to 3 column, 2 row grid, move the content that doesn't fit in to 5th and 6th cells of the grid.
=> #3443 - tiered price mobile position

packages/scandipwa/src/component/Product/Product.component.js, packages/scandipwa/src/component/Product/Product.container.js, packages/scandipwa/src/type/ProductList.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3507
**Problem:**
* child component value not updated on parent component state update
* Fixed by passing ready object to child component instead of passing reference to function
=> #3507 - wishlist only first letter from textfield

packages/scandipwa/src/component/PureForm/Field/Field.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3461
**Problem:**
* Double click on checkbox occurs => checkbox selection doesn't change
* get rid of second odd click action
=> #3461 - checkbox not selected

packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js, packages/scandipwa/src/component/PureForm/Field/Field.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3461
**Problem:**
* Cursor is not pointer
* Used a better solution that avoids this problem
=> #3461 - fix cursor not pointer shipping step

packages/scandipwa/src/component/StoreInPickUpPopup/StoreInPickUpPopup.container.js, packages/scandipwa/src/component/StoreInPickUpPopup/StoreInPickUpPopup.style.scss, packages/scandipwa/src/util/Address/index.js
* Fixes #3373 
**Problem:**
* Store disappear after new fetch of stores
* Countries not sorted
*  Change check for checking if store is present in new fetched stores
* Use util to sort countries
=> issue-3373 - Change check is selected store is in new fetched stores

packages/scandipwa/package.json, packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/2493
* Fixed styling
* Reverted proxy change in `package.json`
=> 3593 - cropped price windows

packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3674
**Problem:**
* Data taken from wrong field
* Changed calculation logic
=> 3674 - wrong total price

packages/scandipwa/src/component/PureForm/FieldSelect/FieldSelect.component.js, packages/scandipwa/src/component/PureForm/FieldSelect/FieldSelect.container.js
* Fixes #3676 
* Fixes #3678
**Problem:**
* dropdowns on mobile not working
* handle native select option to get value from in on change instead of full object
=> issue-3676 - Check for value on dropdown select option for native input

packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.style.scss, packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3681
**Problem:**
* Missing width rules for wishlist
* Added max-with for grid wrapper & width for flex wrapper
=> [3681] Wishlist indents for mobile

packages/scandipwa/src/query/MyAccount.query.js, packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
* Fixes #3662
**Problem:**
* Token is not revoked after user logout so it still exist in Database
* And token revoke on customer logout
=> issue-3662 - Add token revoke mutation after user logout

packages/scandipwa/src/route/Checkout/Checkout.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3290
* Added scroll to top when checkout step changes.
=> scandipwa#3290 - shipping scroll to top fix

packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.container.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js, packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
* Fixes #3707 
**Problem:**
* User can send request to server when its token is expired if he is on wishlist page.
* Check if user is signed in before making actions
=> issue-3707 - Set check if user is signed in

packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.form.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3650
**Problem:**
* VAT field frame does not turn green with valid info inside
* Added validation to VAT field, similar to other fields.
=> [3650] Added validation to VAT field

.gitignore
* Fixes https://github.com/scandipwa/scandipwa/issues/3762
**Problem:**
* Margin above button is 24px, it should be 16px
* Changed margin above the button
=> [3762] Changed margin above the button (recreated)

packages/scandipwa/src/component/Draggable/Draggable.style.scss, packages/scandipwa/src/component/SwipeToDelete/SwipeToDelete.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3843
**Problem:**
* A grey line was appearing next to delete button
* Changed background(padding) of delete button to standard color of background
=> [3843] Changed background of overlay button to white

packages/scandipwa/src/component/SliderWidget/SliderWidget.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3887
**Problem:**
* wrong context
* 
* fixed problem with context
=> #scandipwa-3887 - fix slider error

packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.container.js, packages/scandipwa/src/util/Address/index.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3741
**Problem:**
* Region information was being lost during field data manipulation
* Deleted faulty and otherwise useless address trimming function
=> [3741] Fixed region not being sent to backend

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/component/MyAccountDownloadable/MyAccountDownloadable.component.js, packages/scandipwa/src/component/MyAccountDownloadable/MyAccountDownloadable.config.js, packages/scandipwa/src/component/MyAccountDownloadable/MyAccountDownloadable.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3686
**Problem:**
* Wrong text on my downloadable page
* Change text on my downloadable page without purchase
=> #3686 - Change text on my downloadable page without purchase

packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js, packages/scandipwa/src/component/Product/Product.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3692
**Problem:**
*  Wrong value in dropdown on PDP
* Set to output the correct value to the dropdown on PDP
=> #3692 - Display correct value in dropdown on PDP

packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
* Fixes #3707 
**Problem:**
* Typo in function call when checking if user is signed in
* fix typo
=> #3707 - Fix typo in function call

packages/scandipwa/src/route/ProductComparePage/ProductComparePage.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3604
**Problem:**
* User would appear at the bottom of a page when opening compare list
* Added scrollToTop(); when compare page mounts
=> [3604] Added scrollToTop(); when compare page mounts

packages/scandipwa/src/component/AddToCart/AddToCart.style.scss, packages/scandipwa/src/component/Header/Header.style.scss, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss, packages/scandipwa/src/component/ProductAttributes/ProductAttributes.style.scss, packages/scandipwa/src/component/ProductInformation/ProductInformation.style.scss, packages/scandipwa/src/component/ProductReviewItem/ProductReviewItem.style.scss, packages/scandipwa/src/component/ProductReviews/ProductReviews.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3743
**Problem:**
* Wrong line-height for buttons, title, attributes, product details, expanded description, elements in reviews
* Wrong font settings for '{rate} / {numberOfReviews} reviews', stock status, SKU
* Changed line-height values to the correct ones
* Added font-style, font-weight for SKU and stock status
* Changed font-size for SKU and stock status
=> [3743] Font settings in PDP mobile

packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3715
**Problem:**
* Products have a different style on PLP if product is out of stock
* Out of stock products on PLP had the same style
=> #3715 - Add the same style for out of stock products on PLP

packages/scandipwa/src/component/Field/Field.component.js, packages/scandipwa/src/component/Field/Field.container.js, packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js, packages/scandipwa/src/component/Product/Product.container.js, packages/scandipwa/src/component/ProductConfigurableAttributeDropdown/ProductConfigurableAttributeDropdown.component.js, packages/scandipwa/src/component/ProductConfigurableAttributeDropdown/ProductConfigurableAttributeDropdown.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3952
* Fixes https://github.com/scandipwa/scandipwa/issues/3951
**Problem:**
* Empty value in the dropdown if user selected twice same option
* Add new attribute to change the label if user selected twice same option in the dropdown
=> #3952 - Add a new attribute to change the label by double click

packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3964
**Problem:**
* In some cases, the dropdown becomes empty
* Dropdown always contains some value
=> #3964 - Fix empty dropdown

packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3942
**Problem:**
* Same style for in stock and out of stock in wishlist
* Change product card for out of stock product in Wishlist
=> #3942 - Change product card for out of stock product in Wishlist

packages/scandipwa/src/component/MyAccountDashboard/MyAccountDashboard.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3315
**Problem:**
* Horizontal scroll appears in My account if user has long name
* Allow hyphenation for a table with custom data
=> #3315 - Allow hyphenation for a table with custom data

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/component/Menu/Menu.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3255
**Problem:**
* The mobile version does not have a link to open all products in the category
* Add "All" menu links for categories
=> #3255 - Add All menu links for mobile

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/component/MyAccountOrderInformation/MyAccountOrderInformation.component.js, packages/scandipwa/src/component/MyAccountOrderInformation/MyAccountOrderInformation.style.scss, packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.component.js, packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.style.scss, packages/scandipwa/src/component/MyAccountOrderTotals/MyAccountOrderTotals.component.js, packages/scandipwa/src/query/Order.query.js
* https://github.com/scandipwa/sales-graphql/pull/4
* Fixes #3938 
**Problem:**
* Some issues regarding Orders after QA
* Fixing issues from list in task #3938
=> [#3938] - Adjust customer orders functionality and styles

packages/scandipwa/src/component/Header/Header.component.js, packages/scandipwa/src/component/Header/Header.config.js, packages/scandipwa/src/component/MyAccountAddressTable/MyAccountAddressTable.table.js, packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.component.js, packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.container.js, packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.style.scss, packages/scandipwa/src/component/MyAccountOrderInformation/MyAccountOrderInformation.component.js, packages/scandipwa/src/component/MyAccountOrderItemsTable/MyAccountOrderItemsTable.component.js, packages/scandipwa/src/component/MyAccountOrderItemsTable/MyAccountOrderItemsTable.style.scss, packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.component.js, packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.style.scss, packages/scandipwa/src/component/MyAccountOrderTotals/MyAccountOrderTotals.component.js, packages/scandipwa/src/query/Order.query.js, packages/scandipwa/src/route/MyAccount/MyAccount.style.scss, packages/scandipwa/src/store/Order/Order.dispatcher.js, packages/scandipwa/src/util/Manipulations/Date.js, packages/scandipwa/src/util/Orders/Orders.js
* https://github.com/scandipwa/store-graphql/pull/32
* https://github.com/scandipwa/sales-graphql/pull/3
* https://github.com/scandipwa/sales-graphql/pull/6
* Fixes #3926 
* Fixes https://github.com/scandipwa/scandipwa/issues/3938
**Problem:**
* Some issues regarding Orders after QA
* Fixing issues from list in task #3926
=> [#3926] - Adjust customer orders functionality and styling

packages/scandipwa/src/component/DateSelect/DateSelect.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3981
**Problem:**
* Horizontal scroll appears on PDP if product has date/time option on mobile
* Add wrap for date/time option on mobile
=> #3981 - Add wrap for date/time option on mobile

packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js, packages/scandipwa/src/util/Wishlist/Wishlist.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3982
**Problem:**
* Price excl. tax is missing for some product in Wishlist
* Add price excl.tax for all product in Wishlist
=> #3982 - Add price excl.tax for all product in Wishlist

packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3516
**Problem:**
* Buttons minus or plus are not disabled for limit Qty of product in Wishlist
* Add a limit on the quantity of product in the Wishlist
=> #3516 - Add a limit on the quantity of product in the Wishlist

packages/scandipwa/src/component/MyAccountCustomerForm/MyAccountCustomerForm.form.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3953
**Problem:**
* Email validation lost in "My account"
* Added email validation to "My account"
=> #3953 - Add validation of email in my account

packages/scandipwa/src/component/CartItem/CartItem.style.scss, packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.style.scss, packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss, packages/scandipwa/src/route/CartPage/CartPage.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3794
**Problem:**
* Wrong color and font settings on cart page
* Colors and size of fonts changed according to the issue
=> #3794 - Change color and font setting on cart page

packages/scandipwa/src/route/Checkout/Checkout.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3697
**Problem:**
* email value in state is empty in this case and logic checking if form can be submitted checks if email value in state is not empty
* Set initial email value in state to value from redux store.
=> #scandipwa-3697 - fix shipping form with prefilled guest email not submitted

packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3699
**Problem:**
* Header 'Confirm Your Account' has wrong style properties
* Fix style for 'Confirm Your Account' header
=> #3699 - Fix style for Confirm Your Account header

packages/scandipwa/src/component/Breadcrumb/Breadcrumb.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3545
**Problem:**
* Hover effect absent on breadcrumbs
* Add hover effect for breadcrumbs
=> #3545 - Add hover effect for breadcrumbs

packages/scandipwa/src/component/GridIcon/GridIcon.style.scss, packages/scandipwa/src/component/ListIcon/ListIcon.style.scss
* Fixes #3934
**Problem:**
* Hover effect absent on List/grid view icons
* Added hover effect  on ListIcon and GridIcon styles
=> Hover effect on List/grid view icons

packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3804
**Problem:**
* The price is displayed on FE regardless on the parameters in the admin panel
* The price is displayed on FE depending on the parameters in the admin panel
=> #3804 - The price is displayed on FE depending on the parameters

packages/scandipwa/src/component/ProductCompare/ProductCompare.style.scss
**Problem:**
* Error on building FE
* Adjust styles to use logic properties
=> Adjust styles to use logic properties

packages/scandipwa/src/component/MyAccountNewsletterSubscription/MyAccountNewsletterSubscription.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3845
**Problem:**
* Wrong notification message appears in my account on newsletter subscription page
* Change message on newsletter subscription page
=> #3845 - Change message on newsletter subscription page

packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3316
**Problem:**
* Wrong position of Stock status, SKU, Compare button, Write a review on PDP on mobile
* Right position of Stock status, SKU, Compare button, Write a review on PDP on mobile
=> #3316 - Fix position product action elements on mobile

packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js, packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.style.scss, packages/scandipwa/src/util/Product/Transform.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3534
* Fixes https://github.com/scandipwa/scandipwa/issues/3647
**Problem:**
* Missing styling and wrong class name
* Corrected class name for title
* Added missing styling for label space
=> [3534] Customizable options: bold title & space for price

packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.style.scss
**Problem:**
* StyleLint error
* Adjust styles
=> Add space after opening brace space

packages/scandipwa/src/util/Address/index.js
* Fixes #4022
**Problem:**
* State and country is not shown on order page
* Handle check for order address state and country
=> issue-4022 - Handle check for customer address if state and country for orders

packages/scandipwa/src/component/CartItem/CartItem.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3794
**Problem:**
* Wrong line height for Delete button
*  Set right line height for Delete button
=> #3794 - Fix line height for Delete button

packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.style.scss, packages/scandipwa/src/component/ProductInformation/ProductInformation.style.scss
**Problem:**
* In master branch issues regarding stylelint
* Fixing stylelint
=> Fixing styles according to stylelint

packages/scandipwa/src/route/CartPage/CartPage.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3795
**Problem:**
* Header and Promo blocks don't have rounded corners
* Rounded corners added to Header and Promo blocks
=> #3795 Rounded corners added to Header and Promo blocks

packages/scandipwa/src/route/MenuPage/MenuPage.container.js
* Fixes [#4060 Ooops page appears when opening /menu page in incognito mode](https://github.com/scandipwa/scandipwa/issues/4060)
**Problem:**
* Ooops page appears when opening /menu page in incognito mode
* Change MenuPage.container to only call function redirectIfNotOnMobile() once in componentDidUpdate()
* remove appendWithStoreCode because its block page to redirect
**Note**: The name of the branch got swapped but the code is fine :)
=> #4060 Ooops page appears when opening /menu page in incognito mode

packages/scandipwa/src/index.js
* Get back service-worker registration
=> Get back service-worker registration

packages/scandipwa/src/component/Field/Field.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3505
**Problem:**
* Textarea has different style than other fields
* Modified textarea style to match the other fields
=> [3505] modified textarea fontsize and placeholder styles

packages/scandipwa/src/component/ProductReviewItem/ProductReviewItem.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4126
**Problem:**
* Product review text was justify instead of left alignment
* Modified ProductReviewItem style. Text alignment set to "start"
=> [4126]  modified text align to start

packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3740
**Problem:**
* Padding missing below image
* Added padding bottom
=> [3740] added padding bottom to image

packages/scandipwa/src/component/Html/Html.component.js
* Fixes scandipwa/scandipwa/issues/4205
**Problem:**
* oops page displays instead of requested URL.
* Html.component.js
* lines from 240-244 handled data absence.
* lines from 259-261 handled script being a number.
=> [4205] oops page fix

packages/scandipwa/src/component/Header/Header.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4128
**Problem:**
* Line under the title absent on mobile on 'Write a review', 'Confirm delete', 'EDIT ADDRESS'
* doubling under pages where it was (PDP, Cart, My account, etc)
* appeared where it is not necessary (PLP, Menu, etc)
* Undo changes from PR https://github.com/scandipwa/scandipwa/pull/4141
* Gave higher Z index for popup_name on Header.style
=> [4128] previously added Header-Nav border, changed zindex for popup name to 450

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/component/MyAccountOrderItemsTable/MyAccountOrderItemsTable.component.js, packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.component.js, packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.container.js, packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4017
**Problem:**
* Order product list last product rendered border bottom on mobile
* Modified Style to render border top instead
=> [4017] modified to render top border instead of bottom

packages/scandipwa/src/component/TierPrices/TierPrices.component.js, packages/scandipwa/src/util/Price/Price.config.js, packages/scandipwa/src/util/Price/Price.js
* Fixes #4252
**Problem:**
* Saved % for tier price is not recalculated special price is applied to product too
* Util/Price created util function to return discount % from tier price over special price
* TierPrices component conditionally assign percentOff if special price is present
=> [4252] TierPrices component conditionally assign percentOff if special price is present

packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.component.js, packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss, packages/scandipwa/src/component/ReviewStar/ReviewStar.style.scss
* Fixes #2574
**Problem:**
* Margin between star and error message is 12px
* Margin between error message and next rate is missing
* Delete red/green line for stars
* Modified Product Review Form styling to fit specifications
**Related PRs:**
* #4095
=> [2574] Form re styling according to QA comments

packages/scandipwa/src/route/ConfirmAccountPage/ConfirmAccountPage.container.js, packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.container.js
* Fixes #4075 
**Problem:**
* Logged in user doesn't get redirect to My Account Page when opening Reset Password Page or Confirm Account Page
* Added redirect if user is logged in
=> [4075] added redirect if user is logged in

packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
* Fixes #4055 
**Problem:**
* Small part of background visible from the left side of scroll
* Removed scrollbar styling
**Related PRs:**
* #4079
=> [4055] removed scrollbar styling attributes

packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
* Fixes #4055 
**Problem:**
* Border missing
* Added border
=> [4055] Added border

packages/scandipwa/src/component/Header/Header.style.scss
* Fixes #4332 
**Problem:**
* If qty of products in cart more than 99 then sign of circle stay
* FIxed MiniCartItemQuantity so it became oval when user reaches more than 99 items
=> Modified InCartQuantity to become oval after 99

packages/scandipwa/src/component/ProductConfigurableAttributes/ProductConfigurableAttributes.config.js, packages/scandipwa/src/component/ProductConfigurableAttributes/ProductConfigurableAttributes.style.scss
* Fixes #4235 
**Problem:**
* Placeholders looks bad
* Change placeholders count
=> issue-4235 - Change placeholders count for filters overlay on categories

packages/scandipwa/src/component/CmsBlock/CmsBlock.container.js, packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.container.js, packages/scandipwa/src/component/Menu/Menu.container.js, packages/scandipwa/src/component/OfflineNotice/OfflineNotice.container.js, packages/scandipwa/src/component/SliderWidget/SliderWidget.container.js, packages/scandipwa/src/component/StoreSwitcher/StoreSwitcher.container.js, packages/scandipwa/src/route/CmsPage/CmsPage.container.js, packages/scandipwa/src/route/ContactPage/ContactPage.container.js, packages/scandipwa/src/route/ProductComparePage/ProductComparePage.container.js, packages/scandipwa/src/util/Request/DataContainer.js
* Fixes #3755 
**Problem:**
* Cms pages are not updating dynamically.
* Error in notification component with this.props undefined.
* Fetch cms page every time we visit it. If offline, then get from window cache
* Fix error in offline mode
=> issue-3775 - Fetch cms pages on visiting it

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.style.scss, packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
* Fixes #4350 
**Problem:**
* Mobile: line is missing under currency and line under compare is bold
* Fixed the missing line in mobile view and adjust their thickness
=> Fixed missing line in mobile view under currency

packages/scandipwa/src/component/CategorySort/CategorySort.style.scss
* Fixes #3446 
**Problem:**
* iOS: Arrow is shifted down
* Modified ios styles
* #4323
=> [3446] modified ios styling

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/component/Popup/Popup.component.js
* Fixes #4278 
**Problem:**
* All header works as a back button in pop-ups
* Fixed popup in mobile view, so it won't close when a user presses the header.
* closes only when user press close button
=> Fixed header working as back button in mobile

packages/scandipwa/src/component/ProductActions/ProductActions.style.scss, packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4411
**Problem:**
* Unnecessary indent is displayed in product cart for config product on PLP and PDP
* Remove unnecessary indent in product cart and product action for config product on PLP and PDP
=> #4411 - Change indent for product card

packages/scandipwa/src/component/SliderWidget/SliderWidget.container.js, packages/scandipwa/src/route/CmsPage/CmsPage.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3755 
**Problem:**
* Slider widget is updated not correctly
* Sometimes can see cms page content on other cms page.
* Fix slider widget updating, same for cms
=> issue-4298 - Dynamically update slider widgets 

packages/scandipwa/src/component/MyAccountOrderTotals/MyAccountOrderTotals.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4349
**Problem:**
* table data wasn't breaking into to lines.
* changed word wrap behaviour to break-word
=> #4349 - fixed table data data not breaking into two lines

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.component.js
* #4284 
**Problem:**
* Order of customizable option of a product on the website does not match the order on admin panel
* Fixed the order by sorting the options based on sort-order
=> Fixed order of customizable option

packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js
* Fixes #3587 
**Problem:**
* Links are marked as validated after closing tab with sample
* modified validation event trigger
=> [3587] modified validation event trigger

packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js, packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js, packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4344
**Problem:**
* Opacity for selected by default product option is missing on PDP if this product is out of stock
* Fixed the Opacity for selected by default product option
=> Issue 4344

packages/scandipwa/src/component/StoreItem/StoreItem.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4434
**Problem:**
* When hovering on the dropdown, cursor pointer didn't show up
* Added cursor: pointer;
=> #4434 - added cursor pointer to storeItem-item

packages/scandipwa/src/component/Header/Header.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4461
**Problem:**
* Mobile: Unnecessary line appears below search line when tapping search line
* Removed unnecessary line
=> #4461 Removed unnecessary line

packages/scandipwa/src/component/ProductCard/ProductCard.style.scss, packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4072
**Problem:**
* Margin absent between Excluding taxes and maximum price of bundle product
* Margin block set to design parameters
=> [4072] Margin block fix

packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4271
**Problem:**
* The problem was duplicating the success message of logging in on shipping step
* Added a check to the container component to see if the user has logged in. Removed the ability to send the form several times
=> #4271 Fixed duplication of the success message

packages/scandipwa/src/component/Header/Header.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4473
**Problem:**
* Special characters in header wasn't decoded
* imported decode function so now it displays actual symbols
=> #4473 - added decode function to header search term

packages/scandipwa/src/route/Checkout/Checkout.container.js, packages/scandipwa/src/store/Cart/Cart.dispatcher.js, packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js, packages/scandipwa/src/store/Order/Order.dispatcher.js, packages/scandipwa/src/store/ProductCompare/ProductCompare.dispatcher.js, packages/scandipwa/src/store/Wishlist/Wishlist.dispatcher.js
* Fixes #4413 
**Problem:**
* Issue with receiving customer information after user log out.
* Check when information received to not set it.
=> Add checks before setting data for customers after log out

packages/scandipwa/src/route/Checkout/Checkout.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4457
**Problem:**
* Padding was 16px
* Increased Checkout-Wrapper padding to 32px
=> [4457] - Increased Checkout-Wrapper padding

packages/scandipwa/src/component/ProductLinks/ProductLinks.style.scss, packages/scandipwa/src/component/ProductListWidget/ProductListWidget.style.scss, packages/scandipwa/src/component/RecentlyViewedWidget/RecentlyViewedWidget.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4489
**Problem:**
* Product cards become bigger in Catalog product list/Recently viewed product widget if user re-sized window
* Added styles to component
=> #4489 Added styles to component

build-packages/create-scandipwa-app/index.js
* Fixes #4531 
* Changes to code that fix telemetry timing
=> #4531 - moved to collecting telemetry in ms

packages/scandipwa/src/type/Account.type.js
* Fixes #4527 
**Problem:**
* There is no type 'date' for dates
* Changed it to instanceOf(Date)
=> changed prop-type for date to instanceOf(Date)

packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3965
**Problem:**
* Dropdown is closed for config product on PDP when clicking on disabled option
* Added a check for the dropdown list items.
=> #3965 Fixed dropdown opened

packages/scandipwa/src/route/MyAccount/MyAccount.style.scss, packages/scandipwa/src/type/Order.type.js
* Fixes #4553 
**Problem:**
* propType for discounts was PropTypes.DiscountType
* charged to PropTypes.arrayOf(DiscountType) as this comes as an array
=> Issue 4553 disc prop types

packages/scandipwa/src/component/SearchItem/SearchItem.style.scss, packages/scandipwa/src/component/SearchOverlay/SearchOverlay.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4256
**Problem:**
* Hover effect is missing for product card in search overlay.
* Added hover effect for product card in search overlay.
=> Search hovering fixed

packages/scandipwa/src/component/Header/Header.component.js, packages/scandipwa/src/component/Header/Header.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3530
**Problem:**
* Mobile: Share button is active in Wishlist
* Added wishlist check
=> Added wishlist check

packages/scandipwa/src/component/Notification/Notification.component.js
* Fixes #4592 
**Problem:**
* TypeError appeared when closing the notification by clicking the close button
* Bound the hideNotification method where it's been called
=> Bound the hideNotification method triggered by onClick

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.style.scss
* Fixes #4530 
**Problem:**
* There was a placeholder under layout buttons, that was unnecessary  
* Removed that placeholder
=> removed placeholder under layout buttons

packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js
* Fixes #3965 
**Problem:**
* Dropdown was closing when clicked on a disabled option
* Corrected checks for changing closing state
=> fixed dropdown closing by clicking on disabled option

packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.style.scss
* Fixes scandipwa/scandipwa/issues/4375
**Problem:**
* In some other commit the method that renders the placeholder navigation was removed from where it should be.
* It's back in its place
=> [4375] - Placeholder for layered navigation on PLP is missing - fixed

packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js, packages/scandipwa/src/component/FieldNumber/FieldNumber.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4625
**Problem:**
* Numbers is changing if user change the size of screen
* Added value check
=> #4625 Numbers is changing if user change the size of screen

packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.style.scss
* Fixes #4663 
**Problem:**
* Button in Firefox for mobile was cropped
* Position sticky works not properly for FF and made its position fixed
=> changed position of the button to fixed

packages/scandipwa/src/component/AddToCart/AddToCart.container.js, packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js, packages/scandipwa/src/component/FieldNumber/FieldNumber.container.js
* Fixes #4625 
**Problem:**
* Min value was set incorrectly in some cases and value changed when resizing the screen
* Corrected the implementation
=> corrected the way how min default value is set

packages/scandipwa/src/component/FieldGroup/FieldGroup.style.scss, packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
* Fixes #4664
**Problem:**
* Indent was missing between stars and error message in IOS devices
* Changed properties if styles in order to get the same style
=> changed the properties for styles

packages/scandipwa/src/component/AddToCart/AddToCart.container.js, packages/scandipwa/src/component/FieldNumber/FieldNumber.container.js
* Fixes #4703 
**Problem:**
* Infinite loop occured in componentDidUpdate
* removed the condition which caused it and corrected notification if the Max quantity is less than min quantity
=> removed condition which caused infinite loop and corrected notifcation if the max is less than min

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/component/Field/Field.component.js
* Fixes #4500 
**Problem:**
* The checkboxes and radio inputs didn't checked from the first time
* Replaced defaultChecked value in defaultChecked prop as it should be.
=> put defaultChecked value in defaultChecked prop for type radio 

packages/scandipwa/src/component/GroupedProductsItem/GroupedProductsItem.style.scss
* Fixes #4632
**Problem:**
* There was margin -10px for the message:
* removed that negative margin
=> fixed padding for error messages

packages/scandipwa/src/component/CartItem/CartItem.component.js, packages/scandipwa/src/component/Field/Field.component.js, packages/scandipwa/src/component/Field/Field.container.js, packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js, packages/scandipwa/src/component/FieldNumber/FieldNumber.container.js
* Fixes #4718 
**Problem:**
* The number didn't update in a numberField in mini cart because the value should've been taken from attr 
* Take the value from attr if it is not undefined
=> value is taken from attr in fieldNumber

packages/scandipwa/src/route/Checkout/Checkout.style.scss
* Fixes #4706
**Problem:**
* There was padding that shifted the coupon block 
* Removed that padding
=> removed padding

packages/scandipwa/i18n/da_DK.json, packages/scandipwa/i18n/de_DE.json, packages/scandipwa/i18n/es_ES.json, packages/scandipwa/i18n/fa_IR.json, packages/scandipwa/i18n/fi_FI.json, packages/scandipwa/i18n/fr_FR.json, packages/scandipwa/i18n/it_IT.json, packages/scandipwa/i18n/lv_LV.json, packages/scandipwa/i18n/nb_NO.json, packages/scandipwa/i18n/nl_NL.json, packages/scandipwa/i18n/pl_PL.json, packages/scandipwa/i18n/pt_BR.json, packages/scandipwa/i18n/ru_RU.json, packages/scandipwa/i18n/sl_SI.json, packages/scandipwa/i18n/sv_SE.json, packages/scandipwa/i18n/tr_TR.json, packages/scandipwa/i18n/zh_TW.json, packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.component.js, packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.style.scss
* Fixes #4261 
**Problem:**
* The line broke in by word and button was pushed to the edge
* added custom media query and max-width for that line, think this is the only way to make it look better
=> added few custom media breakpoints in order to give max width of the line

packages/scandipwa/src/component/MyAccountOrderPrint/MyAccountOrderPrint.component.js, packages/scandipwa/src/component/MyAccountOrderPrint/MyAccountOrderPrint.style.scss
* Fixes #4678 
**Problem:**
* Missing comments block in print page for my orders
* Added comments block
=> added comments block for print

packages/scandipwa/src/route/MyAccount/MyAccount.style.scss
* Fixes #4656 
**Problem:**
* Had horizontal scroll on a page when resizing
* Made table to be scrollable if there is no more space
=> made parent block MyAccount-TabContent scrollable

packages/scandipwa/src/component/AddToCart/AddToCart.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4624
**Problem:**
* Wrong behavior on PDP if amount in stock less than 'Minimum Qty Allowed in Shopping Cart'
* Added extra checks for validate qty
=> #4624 Wrong behavior on PDP if amount in stock less than 'Minimum Qty Allowed in Shopping Cart'

packages/scandipwa/src/component/Field/Field.component.js, packages/scandipwa/src/component/Field/Field.container.js, packages/scandipwa/src/component/FieldFile/FieldFile.component.js, packages/scandipwa/src/component/FieldFile/FieldFile.container.js, packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js
* Fixes #4650 
* Fixes #4715 
**Problem:**
* Field stayed green if the user decided to remove the selected file
* In issue #4715 the FF didn't support the onChange event on cancel
* Added blur event for validation 
* For #4715 implemented new method cancelFileField, and cleaning the state and force validating to get error because it didn't validate automatically
=> added event for validation blur

packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.component.js, packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.style.scss, packages/scandipwa/src/component/ProductAttributes/ProductAttributes.style.scss, packages/scandipwa/src/component/ProductCompareAttributeRow/ProductCompareAttributeRow.style.scss, packages/scandipwa/src/component/ResetAttributes/ResetAttributes.component.js, packages/scandipwa/src/component/ResetAttributes/ResetAttributes.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/3802
* Fixes https://github.com/scandipwa/scandipwa/issues/4721
**Problem:**
* 'Images Type Map' shown in html format
* 'Images Type Map' shown as image
=> #3802 - Render image for Image Type Map

packages/scandipwa/src/component/CategoryProductList/CategoryProductList.container.js, packages/scandipwa/src/component/ProductCard/ProductCard.component.js, packages/scandipwa/src/component/ProductCard/ProductCard.container.js, packages/scandipwa/src/component/ProductList/ProductList.component.js, packages/scandipwa/src/component/ProductList/ProductList.container.js, packages/scandipwa/src/component/ProductListPage/ProductListPage.component.js
* Fixes #4758 
**Problem:**
* The PLP started from the top after returning from PDP
* Removed a method that caused that behavior
=> removed a method which caused beginning the view from top on plp after pdp

packages/scandipwa/src/route/Checkout/Checkout.style.scss
* Fixes #4831 
**Problem:**
* Discount component needed padding. 
* Added padding.
=> #4831 added padding to discount code

packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
* Fixes #4785 
**Problem:**
* The order of items in the cart was incorrect. 
* Fixed the order.
=> #4785 - changed order of items in cart

packages/scandipwa/src/component/MyAccountAddressTable/MyAccountAddressTable.component.js, packages/scandipwa/src/component/MyAccountAddressTable/MyAccountAddressTable.container.js, packages/scandipwa/src/component/MyAccountAddressTable/MyAccountAddressTable.table.js, packages/scandipwa/src/component/MyAccountDashboard/MyAccountDashboard.component.js, packages/scandipwa/src/component/MyAccountOrderInformation/MyAccountOrderInformation.component.js
* Fixes #4800 
**Problem:**
* Address did not display country and region.
* Added country and region.
=> #4800 - added region, country and postal code in address.

packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
* Fixes #4753 
**Problem:**
* A line missing. 
*  Added line after currency in mobile.
=> #4753 added line after currency in mobile

packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.component.js, packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
* Fixes #4812 
**Problem:**
* Popup looked off when ratings were disabled.
* Made form spread 3 columns only when it's the first child, thus making it fill the entire popup.
=> #4812 adjusted form width when ratings are disabled

packages/scandipwa/src/route/CartPage/CartPage.style.scss
* Fixes #4786 
**Problem:**
* Loader was not centred on RTL
* Corrected the translate rule that caused the issue.
=> #4786 - corrected loader on RTL

packages/scandipwa/src/component/MyAccountAddressPopup/MyAccountAddressPopup.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4863 
**Problem:**
* The notification message about saving a new address in My account is wrong.
* Changed the notification message.
=> [4863] Corrected the new address notification message.

packages/scandipwa/src/component/MyAccountAddressTable/MyAccountAddressTable.table.js
* Fixes #4800 
**Problem:**
* State appeared as null, when there was no state.
*Fixed that.
=> #4800- corrected issue with state appearing as null

packages/scandipwa/src/component/CarouselScroll/CarouselScroll.style.scss, packages/scandipwa/src/component/CarouselScrollItem/CarouselScrollItem.style.scss, packages/scandipwa/src/component/ProductGallery/ProductGallery.style.scss
* Fixes #3215 
**Problem:**
* Image on PDP changes in size when opening
* Declare 2 variable for height of .CarouselScrollItem and margin-top .CarouselScroll in .ProductGallery
* Used these 2 variable in .CarouselScrollItem and .CarouselScroll
* Added min-height to .ProductGallery-Additional (sum of these 2 variables)
=> CTO2-545 - Image on PDP changes in size when opening

packages/scandipwa/src/route/MyAccount/MyAccount.component.js, packages/scandipwa/src/route/MyAccount/MyAccount.container.js
* Fixes #4850 
**Problem:**
* Page rendered error message instead of the styled 404 page.
* Redirected to 404 page.
=> #4850 change error to the 404 page

packages/scandipwa/src/component/StoreInPickUpPopup/StoreInPickUpPopup.style.scss
* Fixes #4760
**Problem:**
* The result block didn't shrink in height so it stood 300px 
* made the block flex so the result block can shring in height
=> Making the popup flex so the child can shrink

packages/scandipwa/src/util/Product/Transform.js
* Fixes #3478 
**Problem:**
* After the BE changed the data started coming in arrays so the changes should have been made on FE too
* Fixed how the data is taken and processed
=> fixed the data parsing

packages/scandipwa/src/component/SearchOverlay/SearchOverlay.component.js, packages/scandipwa/src/component/SearchOverlay/SearchOverlay.style.scss
* Fixes #4732
**Problem:**
* No padding in no match result for search overlay
* put for that padding as for search query
=> padding same as search query

packages/scandipwa/src/component/ErrorHandler/ErrorHandler.component.js, packages/scandipwa/src/component/ErrorHandler/index.js, packages/scandipwa/src/component/Router/Router.component.js, packages/scandipwa/src/component/Router/Router.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3768
**Problem:**
* Ooops page in offline mode, due to chunk loading error
* Chunk loading error tracking for offline mod
=> #3768 - Create handler for chunk load error in offline mode

packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.style.scss
* Fixes #4964
**Problem:**
* Add to Cart Button sizes were different in FF and Safari
* Fixed some style
=> fixed styles for FF and Safari

packages/scandipwa/src/route/CartPage/CartPage.style.scss
* Fixes #4786 
**Problem:**
* Loader shifted
* Fixed the loader
=> 4786 loader not centered 

packages/scandipwa/src/component/AddToCart/AddToCart.component.js, packages/scandipwa/src/component/AddToCart/AddToCart.container.js, packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js
* Fixes #4967 
**Problem:**
* Error was thrown because updateSelectedValues func, this func is needed for PDP, if it is not passed then it's null, so null can't be called
* added check
=> error caused because default func type is null

packages/scandipwa/src/component/Product/Product.component.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js, packages/scandipwa/src/component/ProductPrice/ProductPrice.container.js
* Fixes #4747 
**Problem:**
* Price was appearing while still loading and on out-of-stock items. 
* Corrected that.
=> #4747 hid price while the product was loading or out of stock

packages/scandipwa/src/component/Notification/Notification.style.scss, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
* Fixes https://scandiflow.atlassian.net/browse/CTO2-544
**Problem:**
* Notification has a fade-in and fade-out animation.
* Select fields have a shake animation when not selected.
* Removed notification fade in, fade out, and field shake animations.
=> [544] removed notification fade in, fade out, and field shake animations

packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.style.scss
* Fixes #4734 
**Problem:**
* Cursor was not pointer on attributes. 
* Fixed that.
=> #4734 corrected issue with cursor on attributes

packages/scandipwa/src/component/Field/Field.style.scss, packages/scandipwa/src/component/FieldFile/FieldFile.component.js, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.container.js
* Fixes scandipwa/scandipwa/issues/4931
**Problem:**
* Hover style rules for the Select Files button were missing
* added the button to the existing set of hover rules
=> [4931] - Select Files button missing hover effect - fixed

packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
Fixes: #5004
This is a fix from #5006
Created a new PR from a branch that has a different parent than the original one.
=> Missing Subtotal Fix

packages/scandipwa/src/query/Config.query.js
* Fixes https://github.com/scandipwa/scandipwa/issues/908
**Includes:**
* PR: https://github.com/scandipwa/catalog-graphql/pull/140
**Problem:**
* Don`t change price for product in cart when switch currency
* Change cart not using session manager
=> #809 - Get cart when switch currency

packages/scandipwa/src/component/Router/Router.component.js
**Problem:**
* Oops page on the master.
* Pushed a hotfix
=> Master oops page hotfix

packages/scandipwa/src/component/ProductTabs/ProductTabs.component.js, packages/scandipwa/src/route/ProductPage/ProductPage.component.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js
* Fixes #2454 
**Problem:**
* Reviews tab was still appearing even when reviews were disabled.
* Added a check for whether reviews are enabled.
=> #2454 - added a check for whether reviews are enabled

packages/scandipwa/src/component/Field/Field.style.scss
* Fixes #4970
**Problem:**
* The Label next to the checkbox or radio wasn't shrinkable
* allow the label to shrink
=> let the label shrink

packages/scandipwa/src/component/MyAccountForgotPassword/MyAccountForgotPassword.container.js
* Fixes #4909 
**Problem:**
* The message couldn't be parsed since the notifications are rendered through HTML component
* turned into string
=> message should be turned into string

packages/scandipwa/src/route/CartPage/CartPage.component.js, packages/scandipwa/src/route/CartPage/CartPage.container.js, packages/scandipwa/src/store/LinkedProducts/LinkedProducts.dispatcher.js
* Fixes https://github.com/scandipwa/scandipwa/issues/5000
**Problem:**
* Cross sell products not display on cart page
* Cross-sell product is shown in cart after user added to cart parent product with cross-sell product
=> #5000 - Display cross sell product in cart

packages/scandipwa/src/component/NavigationTabs/NavigationTabs.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3006
**Problem:**
* Menu icon is active in bottom navigation menu on checkout steps
* Cart icon is active in bottom navigation menu on checkout steps
=> #3006 - Made cart active on checkout steps

packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4325
**Problem:**
* 'Nickname' is not aligned with 'Price' in write a review popup
* 'Nickname' is aligned with 'Price' in write a review popup
=> #4325 - Change gaps for review popup

packages/scandipwa/src/component/ProductActions/ProductActions.component.js, packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4985
**Problem:**
* Product price is 0.00 when loading page
* Product price has placeholder when loading page
=> #4985 - Add placeholder for price on PLP

packages/scandipwa/src/component/Header/Header.container.js, packages/scandipwa/src/route/MyAccount/MyAccount.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/3012
**Problem:**
* Header disappear after refresh of any page in My account
* Number of items and share button present after refresh of wishlist
=> #3012 - Set header for my account page

packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4755
**Problem:**
* FF: horizontal scroll appears in currency dropdown
* FF: horizontal scroll is absent in currency dropdown
=> #4755 - Fix x scroll on firefox

packages/scandipwa/src/component/MyAccountMyOrders/MyAccountMyOrders.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/1656
**Problem:**
* Big table height on old versions on FF
* Normal table height on old versions on FF
=> #1656 - Set table height on my account

packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js, packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
* Fixes https://github.com/scandipwa/scandipwa/issues/4862
**Problem:**
* Encoded special characters are displayed in the Wishlist
* Characters are displayed in the Wishlist for options
=> #4862 - Render option text as html

packages/scandipwa/src/component/MyAccountOrderTableRow/MyAccountOrderTableRow.component.js
* Fixes https://github.com/scandipwa/scandipwa/issues/4928
**Problem:**
* Price 'Total' absent for 0$ price order in 'My orders'
* Show 0$ price for total in 'My orders' table
=> #4928 - Show zero price in my orders table

packages/scandipwa/src/route/OrderPrintPage/OrderPrintPage.component.js, packages/scandipwa/src/route/OrderPrintPage/OrderPrintPage.config.js, packages/scandipwa/src/route/OrderPrintPage/OrderPrintPage.style.scss
* Fixes #5124
**Problem:**
* Unnecessary elements were rendered on the order print page.
* Hid them from the order print page.
=> Order Print Page Fix

packages/scandipwa/composer.json, packages/scandipwa/package.json
=> Merge 5.3.2-rc to master

packages/scandipwa/src/route/Checkout/Checkout.container.js
* Fixes #5105
**Problem:**
* The payment methods were not updated if coupon code was applied or cancelled
* Updating the payment methods on coupon code update
=> updating the payment methods on coupon code change

packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.container.js, packages/scandipwa/src/component/Popup/Popup.container.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js, packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js, packages/scandipwa/src/route/ProductComparePage/ProductComparePage.container.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js
* Fixes https://github.com/scandipwa/scandipwa/issues/5173
**Problem:**
* In recent changes to history, not all use cases of history were updated properly, which caused some issues in different places
* We update all the usages of history properly
=> [5173 ] Fixed issues related to history changes

packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.container.js, packages/scandipwa/src/component/Popup/Popup.container.js, packages/scandipwa/src/route/ProductComparePage/ProductComparePage.container.js, packages/scandipwa/src/route/ProductPage/ProductPage.container.js
* Fixes https://github.com/scandipwa/scandipwa/pull/5199
**Problem:**
* We've pushed some changes which aren't ready to be published yet
* Reverted changes that shouldn't be published
=> Revert history changes 5199

packages/scandipwa/src/component/CheckoutDeliveryOptions/CheckoutDeliveryOptions.component.tsx, packages/scandipwa/src/component/CheckoutDeliveryOptions/CheckoutDeliveryOptions.container.tsx, packages/scandipwa/src/component/CheckoutPayments/CheckoutPayments.component.tsx, packages/scandipwa/src/component/NavigationAbstract/NavigationAbstract.component.tsx, packages/scandipwa/src/component/ProductActions/ProductActions.component.tsx, packages/scandipwa/src/component/ProductCard/ProductCard.component.tsx, packages/scandipwa/src/component/ProductCompareButton/ProductCompareButton.component.tsx, packages/scandipwa/src/component/VideoThumbnail/VideoThumbnail.component.tsx, packages/scandipwa/src/route/CreateAccount/CreateAccount.component.tsx, packages/scandipwa/src/route/ForgotPassword/ForgotPassword.component.tsx, packages/scandipwa/src/route/LoginAccount/LoginAccount.component.tsx
**Problem:**
* Some issues after renaming the components
* Fixed the imports and temporarily disabled unused variable rule in two files
=> fixes for component renames

packages/scandipwa/src/component/Router/Router.component.tsx
**Problem:**
* Search page throws an error when entering it.
* Pass match prop to SearchPage component.
=> TypeScript issue - Pass match prop to SearchPage component

packages/scandipwa/src/component/MyAccountInformation/MyAccountInformation.type.ts, packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.type.ts, packages/scandipwa/src/component/MyAccountOrderInformation/MyAccountOrderInformation.type.ts, packages/scandipwa/src/component/Router/Router.type.ts, packages/scandipwa/src/route/LoginAccount/LoginAccount.type.ts, packages/scandipwa/src/route/SomethingWentWrong/SomethingWentWrong.type.ts, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.type.ts, packages/scandipwa/src/route/WishlistSharedPage/WishlistSharedPage.type.ts, packages/scandipwa/src/type/Global.type.ts
* Refactoring empty object type
=> TypeScript issue - Refactor empty object type

packages/scandipwa/package.json, packages/scandipwa/src/component/App/App.component.tsx, packages/scandipwa/src/component/FieldSelect/FieldSelect.component.tsx, packages/scandipwa/src/component/FieldSelect/FieldSelect.type.ts, packages/scandipwa/src/component/Header/Header.component.tsx, packages/scandipwa/src/component/Meta/Meta.component.tsx, packages/scandipwa/src/component/ProductCard/ProductCard.container.tsx, packages/scandipwa/src/component/ProductGallery/ProductGallery.container.tsx, packages/scandipwa/src/component/Router/Router.container.tsx, packages/scandipwa/src/component/SharedTransition/SharedTransition.component.tsx, packages/scandipwa/src/component/SharedTransition/SharedTransition.container.tsx, packages/scandipwa/src/component/SharedTransition/SharedTransition.unstated.ts, packages/scandipwa/src/index.tsx, packages/scandipwa/src/route/NoMatch/NoMatch.container.tsx, yarn.lock
**Problem:**
* Errors in development mode in console
* Fix issues in console
=> TS-issue - Fix some console errors

packages/scandipwa/composer.json, packages/scandipwa/package.json, packages/scandipwa/src/component/CheckoutTermsAndConditionsPopup/CheckoutTermsAndConditionsPopup.component.tsx, packages/scandipwa/src/component/ImageZoomPopup/ImageZoomPopup.container.tsx, packages/scandipwa/src/component/MyAccountAddressPopup/MyAccountAddressPopup.component.tsx, packages/scandipwa/src/component/NewVersionPopup/NewVersionPopup.component.tsx, packages/scandipwa/src/component/Popup/Popup.component.tsx, packages/scandipwa/src/component/Popup/Popup.container.tsx, packages/scandipwa/src/component/Popup/Popup.type.ts, packages/scandipwa/src/component/ProductList/ProductList.container.tsx, packages/scandipwa/src/component/ShareWishlistPopup/ShareWishlistPopup.component.tsx, packages/scandipwa/src/component/StoreInPickUpPopup/StoreInPickUpPopup.component.tsx, packages/scandipwa/src/route/CategoryPage/CategoryPage.component.tsx, packages/scandipwa/src/route/CategoryPage/CategoryPage.container.tsx, packages/scandipwa/src/route/CategoryPage/CategoryPage.type.ts, packages/scandipwa/src/util/Request/Request.ts
Merge master and 5.3.6-rc to TS branch
=> TS-issue - merge master and 5.3.6-rc to TS branch

packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.container.tsx, packages/scandipwa/src/query/Config.query.ts, packages/scandipwa/src/store/Config/Config.dispatcher.ts, packages/scandipwa/src/util/Currency/Currency.ts, packages/scandipwa/src/util/Request/Request.ts
**Problem:**
* Currency switcher is not working at all. Same as prev implementation of switching currency is not correct.
* Put currency code into the headers
=> TypeScript issue - Fix currency switcher issue. Set currency as header for requests

packages/scandipwa/src/component/ResetAttributes/ResetAttributes.container.tsx
**Problem:**
* Filters for price is shown not correct for selected price filter
* Set correct selected price filter label
=> TypeScript - Fix price filter showing not correct

package.json
* Check if typescript builds packages in ./packages file when making push to branch
=> TypeScript issue - Add typescript build hook for pre-push

build-packages/csa-generator-theme/index.js, build-packages/csa-generator-theme/template/.eslintrc.js, build-packages/csa-generator-theme/template/package.json, build-packages/csa-generator-theme/template/tsconfig.json, build-packages/csa-generator-theme/template/yarn.lock.cached, build-packages/ts-server-plugin/build-config/before.js
**Problem:**
* Theme creation missing come configs for typescript
* Adjust theme creation
=> TypeScript issue - Adjust CSA generation && ts-server-plugin adjustments

packages/scandipwa/src/component/CheckoutAddressTable/CheckoutAddressTable.component.tsx, packages/scandipwa/src/store/Cart/Cart.dispatcher.ts
=> issue-5244 - Fix cart adding to cart flow && opening checkout with saved address

packages/scandipwa/src/component/FieldNumberWithControls/FieldNumberWithControls.container.tsx, packages/scandipwa/src/component/Notification/Notification.component.tsx, packages/scandipwa/src/store/Cart/Cart.dispatcher.ts, packages/scandipwa/src/util/Validator/Validator.ts
=> Fix min/max qty for adding product into cart

packages/scandipwa/src/component/Field/Field.container.tsx
=> issue-5242 - Fix validation for fields

packages/scandipwa/src/component/FieldSelect/FieldSelect.component.tsx
=> issue-5239 - Fix selecting option for field select

packages/scandipwa/src/component/CartItem/CartItem.component.tsx
=> issue-5259 - Change order for selected options in cart overlay

packages/scandipwa/src/component/NewProducts/NewProducts.style.scss, packages/scandipwa/src/component/ProductListWidget/ProductListWidget.style.scss
=> issue-5258 - Adjust selector for product widgets on mobile

packages/scandipwa/src/component/CheckoutAddressForm/CheckoutAddressForm.component.tsx, packages/scandipwa/src/component/FieldGroup/FieldGroup.type.ts
=> issue-5240 - Fix on first checkout load shipping estimates

packages/scandipwa/src/component/Product/Product.container.tsx
=> issue-5241 - Fix scroll for configurable products

packages/scandipwa/src/component/Header/Header.style.scss
=> issue-5253 - Adjust width for header checkout icons

packages/scandipwa/src/util/Currency/Currency.ts
=> issue-5263 - Adjust logic for setting default currency

packages/scandipwa/src/component/Overlay/Overlay.component.tsx
=> issue-5254 - Fix popup jumping on opening

packages/scandipwa/src/component/CheckoutTermsAndConditionsPopup/CheckoutTermsAndConditionsPopup.component.tsx, packages/scandipwa/src/component/MyAccountAddressPopup/MyAccountAddressPopup.component.tsx, packages/scandipwa/src/component/ShareWishlistPopup/ShareWishlistPopup.component.tsx
=> issue-5256 - Enable on outside click close for some popups

packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.style.scss
=> issue-5249 - Adjust selector for product compare add to cart styles

packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
=> issue-5280 - Fix margin for wishlist items on mobile

packages/scandipwa/src/component/CheckoutAddressForm/CheckoutAddressForm.component.tsx, packages/scandipwa/src/component/FieldGroup/FieldGroup.type.ts, packages/scandipwa/src/route/Checkout/Checkout.config.ts, packages/scandipwa/src/route/Checkout/Checkout.container.tsx
=> issue-5279 - Fix on autofill checkout address form

build-packages/csa-generator-theme/template/.eslintrc.js
=> issue-5282 - Fix compiling project with eslint parses error

packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
=> Remove redundant margin for wishlist items

packages/bundle-analyzer/build-config/analyzer.js
=> issue-5294 - Fix bundle analyzer

packages/scandipwa/src/util/Price/Price.ts
Fixes [5131](https://github.com/scandipwa/scandipwa/issues/5131)
Updated version of this: #5137
=> 5131 Added fallback for nonexistent prices formatting

packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.container.tsx, packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.type.ts
Fixes #4974 
Updated version of this PR: #5157
=> 4974 Modified same as shipping checkbox behavior

packages/scandipwa/src/component/Menu/Menu.component.tsx, packages/scandipwa/src/component/Menu/Menu.style.scss, packages/scandipwa/src/component/Router/Router.component.tsx, packages/scandipwa/src/component/Router/Router.style.scss, packages/scandipwa/src/style/base/_root.scss
* Added placeholder for the header, border for the fallback and menu height adjustments
=> Performance heder and menu adjustments for the fallback

packages/scandipwa/src/component/Router/Router.component.tsx, packages/scandipwa/src/component/Router/Router.type.ts, packages/scandipwa/src/route/UrlRewrites/UrlRewrites.component.tsx
* Fixes [link for issue]
**Problem:**
* [Describe the problem briefly]
=> Fix for performance

packages/scandipwa/src/component/Fallback/Fallback.component.tsx, packages/scandipwa/src/component/Fallback/Fallback.style.scss
* Fixes [link for issue]
**Problem:**
* [Describe the problem briefly]
=> Category details fallback adjustments

packages/scandipwa/src/component/ProductList/ProductList.container.tsx
* Fixes https://github.com/scandipwa/scandipwa/issues/5152
=> Fixed infinite scroll on mobile plp

packages/scandipwa/src/route/CmsPage/CmsPage.container.tsx, packages/scandipwa/src/route/CmsPage/CmsPage.type.ts
* Fixes #5437 
**Problem:**
* CMS page was not updating in CmsReducer since no load of the page was happening
* Added action to trigger cms page change
=> Added change to the original CMS page

packages/scandipwa/src/util/Auth/IsSignedIn.ts
* Fixes [[link for issue](https://scandiflow.atlassian.net/browse/TEAMS-861)]
**Problem:**
* When user logs in message "Your session is over, you are logged out!" appears
=> TEAMS-861 - fix wrong sign out notifictation

packages/scandipwa/src/util/Product/Product.ts
* Fixes [[link for issue](https://scandiflow.atlassian.net/browse/TEAMS-859)]
**Problem:**
* Error when accessing the "TV, Audio, Photo, Video" page
* Putting some guard conditions
=> TEAMS-859 - added some guard conditions

packages/scandipwa/src/component/Router/Router.style.scss, packages/scandipwa/src/style/base/_root.scss
* Fixes [[link for issue](https://scandiflow.atlassian.net/browse/TEAMS-879)]
**Problem:**
* "Go to "Address Book", to configure them!" text is not visible
=> TEAMS-879 - added bottom padding to myAccount page on mobile view

packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.container.tsx, packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.type.ts, packages/scandipwa/src/store/Config/Config.reducer.ts, packages/scandipwa/src/util/Currency/Currency.ts
* Fixes [[link for issue](https://scandiflow.atlassian.net/browse/TEAMS-852)]
**Problem:**
* changing currency switcher doesn't do any thing
* used correct action to update Redux store accordingly
=> TEAMS-852 - change currency on switcher select

packages/scandipwa/src/component/ProductCard/ProductCard.component.tsx, packages/scandipwa/src/component/ProductCard/ProductCard.container.tsx, packages/scandipwa/src/component/ProductCard/ProductCard.style.scss, packages/scandipwa/src/component/ProductCard/ProductCard.type.ts
* Fixes [[TEAMS-881](https://scandiflow.atlassian.net/browse/TEAMS-881)]
**Problem:**
* [Describe the problem briefly]
* Just added some jsx and scss to render required UI
[TEAMS-881]: https://scandiflow.atlassian.net/browse/TEAMS-881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEAMS-881 - added product actions on PLP on mobile view

packages/scandipwa/src/component/ProductList/ProductList.container.tsx
* Fixes [[TEAMS-882](https://scandiflow.atlassian.net/browse/TEAMS-882)]
**Problem:**
* [Describe the problem briefly]
* ProductList wasn't updating on sort and filter change (only on mobile) because of some condition so I tweaked a bit to work correctly
[TEAMS-882]: https://scandiflow.atlassian.net/browse/TEAMS-882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TEAMS-882 - fixed not updating productList on sort and filter change

packages/scandipwa/src/component/InstallPrompt/InstallPrompt.component.tsx, packages/scandipwa/src/component/InstallPrompt/InstallPrompt.container.tsx, packages/scandipwa/src/component/InstallPrompt/InstallPrompt.style.scss, packages/scandipwa/src/component/InstallPromptAndroid/InstallPromptAndroid.style.scss, packages/scandipwa/src/component/InstallPromptIOS/InstallPromptIOS.style.scss, packages/scandipwa/src/route/HomePage/HomePage.container.tsx, packages/scandipwa/src/route/HomePage/HomePage.style.scss, packages/scandipwa/src/type/Global.type.ts, packages/scandipwa/src/util/Preload/index.ts
* Fixes https://scandiflow.atlassian.net/browse/TEAMS-913
**Problem:**
* Prompt window on mobile didn't have a placeholder
* Added placeholder for the prompt, changed condition for the window to appear
=> TEAMS-913 Fixed prompt behavior

packages/scandipwa/src/route/Checkout/Checkout.container.tsx
* Fixes [[link for issue]](https://scandiflow.atlassian.net/browse/TEAMS-921)
**Problem:**
* Not logged in user can't make order
* Fixed issue - not logged in user can't make order
=> TEAMS-921 - fixed issue - not logged in user can't make order

packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.ts
* Fixes [TEAMS-914](https://scandiflow.atlassian.net/browse/TEAMS-914)
**Problem:**
* Products added to CART while not logged in are not appearing when you log in
* move updating initial cart data after authorization token is available
[TEAMS-914]: https://scandiflow.atlassian.net/browse/TEAMS-914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update cart after customer data is available

packages/scandipwa/src/component/ProductTabs/ProductTabs.component.tsx, packages/scandipwa/src/component/ProductTabs/ProductTabs.style.scss, packages/scandipwa/src/component/ProductTabs/ProductTabs.type.ts
* Fixes [PERF-26](https://scandiflow.atlassian.net/browse/PERF-26)
**Problem:**
* Animate tabs for product details on product page
* Animate tabs for product details on product page
[PERF-26]: https://scandiflow.atlassian.net/browse/PERF-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PERF-26 animate tabs for product details on PDP

packages/scandipwa/src/component/DemoNotice/DemoNotice.component.tsx, packages/scandipwa/src/component/DemoNotice/DemoNotice.container.tsx, packages/scandipwa/src/component/DemoNotice/DemoNotice.style.scss, packages/scandipwa/src/component/DemoNotice/DemoNotice.type.ts, packages/scandipwa/src/component/Router/Router.component.tsx, packages/scandipwa/src/component/Router/Router.config.ts, packages/scandipwa/src/component/Router/Router.container.tsx, packages/scandipwa/src/component/Router/Router.type.ts, packages/scandipwa/src/store/Config/Config.reducer.ts, packages/scandipwa/src/type/Global.type.ts
* Fixes https://scandiflow.atlassian.net/jira/software/c/projects/PERF/boards/1517?selectedIssue=PERF-15
**Problem:**
* Large CLS on HomePage
* I fixed CLS on homepage, fixed DemoNotice
* link to backend module PR - https://github.com/scandipwa/route717/pull/36
=> Fixed DemoNotice

packages/scandipwa/src/component/Breadcrumb/Breadcrumb.component.tsx, packages/scandipwa/src/component/Link/Link.component.tsx, packages/scandipwa/src/component/Link/Link.container.tsx, packages/scandipwa/src/component/Link/Link.style.scss, packages/scandipwa/src/component/Link/Link.type.ts, packages/scandipwa/src/component/MenuItem/MenuItem.component.tsx
* Fixes https://scandiflow.atlassian.net/jira/software/c/projects/PERF/boards/1517?selectedIssue=PERF-34
**Problem:**
* Large INP score on category change
* Fixed INP on category change
=> PERF-34 fixed INP for category change

packages/scandipwa/src/component/Menu/Menu.component.tsx, packages/scandipwa/src/component/Menu/Menu.config.ts, packages/scandipwa/src/component/Menu/Menu.container.tsx, packages/scandipwa/src/component/Menu/Menu.style.scss, packages/scandipwa/src/component/Menu/Menu.type.ts
Fixes [PERF-27](https://scandiflow.atlassian.net/browse/PERF-27)
**Problem:**
*  Adds Animate to menu dropdowns to expand collapse on Desktop
[PERF-27]: https://scandiflow.atlassian.net/browse/PERF-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PERF-27: Animate menu dropdowns to expand collapse on Desktop 

packages/scandipwa/src/component/ProductCard/ProductCard.component.tsx
* Fixes https://scandiflow.atlassian.net/jira/software/c/projects/PERF/boards/1517?selectedIssue=PERF-37
**Problem:**
* Large INP score on product card click
* Improved INP score
**Related PR:**
* Link: https://github.com/scandipwa/scandipwa/pull/5536
=> fixed INP for product card click

packages/scandipwa/src/component/ProductList/ProductList.container.tsx, packages/scandipwa/src/component/ProductListPage/ProductListPage.component.tsx
* Fixes [[PERF-39](https://scandiflow.atlassian.net/browse/PERF-39)]
**Problem:**
* product list jumps randomly on infinite scrolling and doesnt load all the products on prelaods
* to load the rest of the pages I disabled isPrefetchedValueused to enable rest page to be request but (after preloaded page loads)
[PERF-39]: https://scandiflow.atlassian.net/browse/PERF-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fixing issues with infinite scroll

packages/scandipwa/src/component/MyAccountCustomerTable/MyAccountCustomerTable.component.tsx, packages/scandipwa/src/component/MyAccountCustomerTable/MyAccountCustomerTable.style.scss, packages/scandipwa/src/component/MyAccountDashboard/MyAccountDashboard.component.tsx, packages/scandipwa/src/component/MyAccountDashboard/MyAccountDashboard.style.scss
* Fixes https://scandiflow.atlassian.net/jira/software/c/projects/PERF/boards/1517?selectedIssue=PERF-19
**Problem:**
* No placeholder for account info
* Added placeholder, fixed cls
=> Fixed cls on MyAccount page
